# Load file to bronze

## Imports

In [8]:
import os
from datetime import datetime
import pandas as pd

## Parameters

In [2]:
source_file_path = os.path.join(os.curdir, "menstrual_cycle.csv")

In [3]:
os.listdir()

['.git', 'menstrual_cycle.csv', 'NB_MC_FILE_BR.ipynb', 'README.md']

In [4]:
bronze_file_name = "menstrual_cycle.parquet"
bronze_path = os.path.join(os.curdir, "Data_Lake","Bronze")
bronze_file_path = os.path.join(bronze_path, bronze_file_name)

In [5]:
os.makedirs(bronze_path)

## Main

### Cargar el csv a un DataFrame

In [6]:
menstrual_cycle_df = pd.read_csv(source_file_path)

In [7]:
# Comprobamos si el fichero se ha cargado correctamente
menstrual_cycle_df.head()

,User ID,Age,BMI,Stress Level,Exercise Frequency,Sleep Hours,Diet,Cycle Start Date,Cycle Length,Period Length,Next Cycle Start Date,Symptoms
0,1.0,18,29.28,2,Moderate,5.4,Low Carb,52:34.9,26,7.0,52:34.9,Headache
1,1.0,18,29.28,2,Moderate,5.4,Low Carb,52:34.9,32,5.0,52:34.9,Fatigue
2,1.0,18,29.28,2,Moderate,5.4,Low Carb,52:34.9,41,7.0,52:34.9,Fatigue
3,1.0,18,29.28,2,Moderate,5.4,Low Carb,52:34.9,27,3.0,52:34.9,Fatigue
4,1.0,18,29.28,2,Moderate,5.4,Low Carb,52:34.9,42,5.0,52:34.9,Cramps

### Añadir el timestamp de carga

In [9]:
menstrual_cycle_df['_BronzeTimestamp'] = datetime.now()

In [10]:
menstrual_cycle_df.head()

,User ID,Age,BMI,Stress Level,Exercise Frequency,Sleep Hours,Diet,Cycle Start Date,Cycle Length,Period Length,Next Cycle Start Date,Symptoms,_BronzeTimestamp
0,1.0,18,29.28,2,Moderate,5.4,Low Carb,52:34.9,26,7.0,52:34.9,Headache,2025-11-06 17:24:13.627513
1,1.0,18,29.28,2,Moderate,5.4,Low Carb,52:34.9,32,5.0,52:34.9,Fatigue,2025-11-06 17:24:13.627513
2,1.0,18,29.28,2,Moderate,5.4,Low Carb,52:34.9,41,7.0,52:34.9,Fatigue,2025-11-06 17:24:13.627513
3,1.0,18,29.28,2,Moderate,5.4,Low Carb,52:34.9,27,3.0,52:34.9,Fatigue,2025-11-06 17:24:13.627513
4,1.0,18,29.28,2,Moderate,5.4,Low Carb,52:34.9,42,5.0,52:34.9,Cramps,2025-11-06 17:24:13.627513

### Guardar el DataFrame en parquet

In [11]:
menstrual_cycle_df.to_parquet(bronze_file_path, index=False)