# Load bronze to silver

In [478]:
import os
import pandas as pd
from datetime import datetime

## Parametros

In [479]:
bronze_path = os.path.join(
    os.curdir, "Data_Lake", "Bronze"
)
silver_path = os.path.join(
    os.curdir, "Data_Lake", "Silver"
)

In [480]:
bronze_file_name = "menstrual_cycle_bronze.parquet"

silver_file_name = "menstrual_cycle_silver.parquet"

In [481]:
bronze_file_path = os.path.join(
    bronze_path, bronze_file_name
)
silver_file_path = os.path.join(
    silver_path, silver_file_name
)

## Main

### Cargar los de datos de Bronze

In [482]:
bronze_menstrual_cycle_df = pd.read_parquet(bronze_file_path)

In [483]:
bronze_menstrual_cycle_df.head()

,User ID,Age,Stress Level,Exercise Frequency,Sleep Hours,Diet,Cycle Start Date,Cycle Length,Period Length,Next Cycle Start Date,Symptoms,BMI,_BronzeTimestamp
0,1.0,18.0,2.0,Moderate,54.0,Low Carb,13/11/2024 20:52,26,7.0,09/12/2024 20:52,Headache,29.28,2025-11-06 19:16:40.445350
1,1.0,18.0,2.0,Moderate,54.0,Low Carb,09/12/2024 20:52,32,5.0,10/01/2025 20:52,Fatigue,29.28,2025-11-06 19:16:40.445350
2,1.0,18.0,2.0,Moderate,54.0,Low Carb,10/01/2025 20:52,41,7.0,20/02/2025 20:52,Fatigue,29.28,2025-11-06 19:16:40.445350
3,1.0,18.0,2.0,Moderate,54.0,Low Carb,20/02/2025 20:52,27,3.0,19/03/2025 20:52,Fatigue,29.28,2025-11-06 19:16:40.445350
4,1.0,18.0,2.0,Moderate,54.0,Low Carb,19/03/2025 20:52,42,5.0,30/04/2025 20:52,Cramps,29.28,2025-11-06 19:16:40.445350

### Normalización de datos

#### Nulos
De cara a tratar los valores nulos, lo primero que debemos comprobar es que campos son críticos para la tabla.

Si tenemos un "id" que usaremos para identificar a una fila de manera única, no puede ser nulo.

De ahí en adelante debemos usar nuestro propio juicio para decidir que puede ser nulo y que no, y actuar en consecuencia:

- Eliminando las filas con valores nulos en esa columna
- Imputando los valores que faltan

In [484]:
bronze_menstrual_cycle_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 895 entries, 0 to 894
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   User ID                893 non-null    float64
 1   Age                    892 non-null    float64
 2   Stress Level           893 non-null    float64
 3   Exercise Frequency     894 non-null    object
 4   Sleep Hours            893 non-null    float64
 5   Diet                   895 non-null    object
 6   Cycle Start Date       895 non-null    object
 7   Cycle Length           895 non-null    int64
 8   Period Length          892 non-null    float64
 9   Next Cycle Start Date  895 non-null    object
 10  Symptoms               895 non-null    object
 11  BMI                    895 non-null    float64
 12  _BronzeTimestamp       895 non-null    datetime64[us]
dtypes: datetime64[us](1), float64(6), int64(1), object(5)
memory usage: 91.0+ KB

##### User ID

In [485]:
# compuebo los nulos de la columna User Id
bronze_menstrual_cycle_df[bronze_menstrual_cycle_df['User ID'].isnull() == True]

,User ID,Age,Stress Level,Exercise Frequency,Sleep Hours,Diet,Cycle Start Date,Cycle Length,Period Length,Next Cycle Start Date,Symptoms,BMI,_BronzeTimestamp
173,NaN,21.0,1.0,Low,80.0,Balanced,28/01/2025 20:52,33,7.0,02/03/2025 20:52,Headache,21.57,2025-11-06 19:16:40.445350
182,NaN,45.0,4.0,Low,75.0,Low Carb,29/03/2024 20:52,39,3.0,07/05/2024 20:52,Cramps,24.82,2025-11-06 19:16:40.445350

In [486]:
# antes de eliminar los user id nulos, buscamos posibles coincidencias de edad y bmi para identificar posibles registros nulos asiciados a personas ya registradas 
def reasignar_user_id_nulos(fila, df):
    if pd.isnull(fila['User ID']):
        coincidencia = df[(df['Age'] == fila['Age']) & 
                   (df['BMI'] == fila['BMI']) & 
                   (df['User ID'].notnull())]
        if len(coincidencia) > 0:
            return coincidencia['User ID'].iloc[0]
        else:
            return None
    else:
        return fila['User ID']

In [487]:
bronze_menstrual_cycle_df['User ID'] = bronze_menstrual_cycle_df.apply(
    lambda fila: reasignar_user_id_nulos(fila, bronze_menstrual_cycle_df),
    axis=1
)

In [488]:
# comprobamos si se han reasignado valores o si debemos ahora si eliminarlos
bronze_menstrual_cycle_df[bronze_menstrual_cycle_df['User ID'].isnull() == True]

Empty DataFrame
Columns: [User ID, Age, Stress Level, Exercise Frequency, Sleep Hours, Diet, Cycle Start Date, Cycle Length, Period Length, Next Cycle Start Date, Symptoms, BMI, _BronzeTimestamp]
Index: []

In [489]:
# comprobamos que todos ninguna fecha de comienzo de ciclo se solape y, por tanto, la reasignaciones fueron correctas
bronze_menstrual_cycle_df[bronze_menstrual_cycle_df['Age']==21]

,User ID,Age,Stress Level,Exercise Frequency,Sleep Hours,Diet,Cycle Start Date,Cycle Length,Period Length,Next Cycle Start Date,Symptoms,BMI,_BronzeTimestamp
172,19.0,21.0,1.0,Low,80.0,Balanced,21/12/2024 20:52,38,7.0,28/01/2025 20:52,Cramps,21.57,2025-11-06 19:16:40.445350
173,19.0,21.0,1.0,Low,80.0,Balanced,28/01/2025 20:52,33,7.0,02/03/2025 20:52,Headache,21.57,2025-11-06 19:16:40.445350
174,19.0,21.0,1.0,Low,80.0,Balanced,02/03/2025 20:52,46,4.0,17/04/2025 20:52,Mood Swings,200.00,2025-11-06 19:16:40.445350
175,19.0,21.0,1.0,Low,80.0,Balanced,17/04/2025 20:52,44,5.0,10/08/2077 20:52,Mood Swings,21.57,2025-11-06 19:16:40.445350
176,19.0,21.0,1.0,Low,80.0,Balanced,31/05/2025 20:52,42,3.0,12/07/2025 20:52,Mood Swings,21.57,2025-11-06 19:16:40.445350
178,19.0,21.0,1.0,Low,80.0,Balanced,09/08/2025 20:52,37,7.0,15/09/2025 20:52,Mood Swings,21.57,2025-11-06 19:16:40.445350
394,45.0,21.0,4.0,Moderate,66.0,Vegetarian,28/05/2023 20:52,30,3.0,27/06/2023 20:52,Headache,23.37,2025-11-06 19:16:40.445350
395,45.0,21.0,4.0,Moderate,66.0,Vegetarian,27/06/2023 20:52,27,6.0,24/07/2023 20:52,Bloating,23.37,2025-11-06 19:16:40.445350
396,45.0,21.0,4.0,Moderate,66.0,Vegetarian,24/07/2023 20:52,27,6.0,20/08/2023 20:52,Mood Swings,23.37,2025-11-06 19:16:40.445350
397,45.0,21.0,4.0,Moderate,66.0,Vegetarian,20/08/2023 20:52,25,3.0,14/09/2023 20:52,Headache,23.37,2025-11-06 19:16:40.445350
398,45.0,21.0,4.0,Moderate,66.0,Vegetarian,14/09/2023 20:52,43,6.0,27/10/2023 20:52,Cramps,23.37,2025-11-06 19:16:40.445350
399,45.0,21.0,4.0,Moderate,66.0,Vegetarian,27/10/2023 20:52,32,4.0,28/11/2023 20:52,Headache,23.37,2025-11-06 19:16:40.445350
400,45.0,21.0,4.0,Moderate,66.0,Vegetarian,28/11/2023 20:52,44,3.0,11/01/2024 20:52,Fatigue,23.37,2025-11-06 19:16:40.445350
401,45.0,21.0,4.0,Moderate,66.0,Vegetarian,11/01/2024 20:52,28,5.0,08/02/2024 20:52,Headache,23.37,2025-11-06 19:16:40.445350
554,63.0,21.0,3.0,Moderate,77.0,Balanced,28/09/2024 20:52,49,4.0,16/11/2024 20:52,Headache,23.94,2025-11-06 19:16:40.445350
555,63.0,21.0,3.0,Moderate,77.0,Balanced,16/11/2024 20:52,29,7.0,15/12/2024 20:52,Cramps,23.94,2025-11-06 19:16:40.445350
556,63.0,21.0,3.0,Moderate,77.0,Balanced,15/12/2024 20:52,25,7.0,09/01/2025 20:52,Cramps,23.94,2025-11-06 19:16:40.445350
557,63.0,21.0,3.0,Moderate,77.0,Balanced,09/01/2025 20:52,46,4.0,24/02/2025 20:52,Cramps,23.94,2025-11-06 19:16:40.445350
558,63.0,21.0,3.0,Moderate,77.0,Balanced,24/02/2025 20:52,46,7.0,11/04/2025 20:52,Fatigue,23.94,2025-11-06 19:16:40.445350
559,63.0,21.0,3.0,Moderate,77.0,Balanced,11/04/2025 20:52,47,6.0,28/05/2025 20:52,Fatigue,23.94,2025-11-06 19:16:40.445350
560,63.0,21.0,3.0,Moderate,77.0,Balanced,28/05/2025 20:52,29,5.0,26/06/2025 20:52,Bloating,23.94,2025-11-06 19:16:40.445350
561,63.0,21.0,3.0,Moderate,77.0,Balanced,26/06/2025 20:52,27,4.0,23/07/2025 20:52,Headache,23.94,2025-11-06 19:16:40.445350
562,63.0,21.0,3.0,Moderate,77.0,Balanced,23/07/2025 20:52,31,5.0,23/08/2025 20:52,Headache,23.94,2025-11-06 19:16:40.445350
563,63.0,21.0,3.0,Moderate,77.0,Balanced,23/08/2025 20:52,48,4.0,10/10/2025 20:52,Cramps,23.94,2025-11-06 19:16:40.445350
827,93.0,21.0,5.0,Low,86.0,Low Carb,07/12/2023 20:52,33,4.0,09/01/2024 20:52,Headache,24.41,2025-11-06 19:16:40.445350
828,93.0,21.0,5.0,Low,86.0,Low Carb,09/01/2024 20:52,29,5.0,07/02/2024 20:52,Mood Swings,24.41,2025-11-06 19:16:40.445350
829,93.0,21.0,5.0,Low,86.0,Low Carb,07/02/2024 20:52,33,6.0,11/03/2024 20:52,Cramps,24.41,2025-11-06 19:16:40.445350
830,93.0,21.0,5.0,Low,86.0,Low Carb,11/03/2024 20:52,35,4.0,15/04/2024 20:52,Fatigue,24.41,2025-11-06 19:16:40.445350
831,93.0,21.0,5.0,Low,86.0,Low Carb,15/04/2024 20:52,36,4.0,21/05/2024 20:52,Cramps,24.41,2025-11-06 19:16:40.445350
832,93.0,21.0,5.0,Low,86.0,Low Carb,21/05/2024 20:52,27,3.0,17/06/2024 20:52,Fatigue,24.41,2025-11-06 19:16:40.445350
833,93.0,21.0,5.0,Low,86.0,Low Carb,17/06/2024 20:52,35,3.0,22/07/2024 20:52,Bloating,24.41,2025-11-06 19:16:40.445350
834,93.0,21.0,5.0,Low,86.0,Low Carb,22/07/2024 20:52,49,5.0,09/09/2024 20:52,Mood Swings,24.41,2025-11-06 19:16:40.445350
835,93.0,21.0,5.0,Low,86.0,Low Carb,09/09/2024 20:52,35,3.0,14/10/2024 20:52,Mood Swings,24.41,2025-11-06 19:16:40.445350
836,93.0,21.0,5.0,Low,86.0,Low Carb,14/10/2024 20:52,46,5.0,29/11/2024 20:52,Bloating,24.41,2025-11-06 19:16:40.445350

In [490]:
bronze_menstrual_cycle_df[bronze_menstrual_cycle_df['Age']==45]

,User ID,Age,Stress Level,Exercise Frequency,Sleep Hours,Diet,Cycle Start Date,Cycle Length,Period Length,Next Cycle Start Date,Symptoms,BMI,_BronzeTimestamp
179,20.0,45.0,4.0,Low,75.0,Low Carb,19/12/2023 20:52,29,7.0,17/01/2024 20:52,Bloating,24.82,2025-11-06 19:16:40.445350
182,20.0,45.0,4.0,Low,75.0,Low Carb,29/03/2024 20:52,39,3.0,07/05/2024 20:52,Cramps,24.82,2025-11-06 19:16:40.445350
183,20.0,45.0,4.0,Low,75.0,Low Carb,07/05/2024 20:52,36,6.0,10/08/2077 20:52,Bloating,24.82,2025-11-06 19:16:40.445350
184,20.0,45.0,4.0,Low,75.0,Low Carb,12/06/2024 20:52,47,3.0,29/07/2024 20:52,Fatigue,24.82,2025-11-06 19:16:40.445350
185,20.0,45.0,4.0,Low,75.0,Low Carb,29/07/2024 20:52,34,7.0,01/09/2024 20:52,Fatigue,24.82,2025-11-06 19:16:40.445350
230,27.0,45.0,3.0,High,63.0,Vegetarian,26/12/2024 20:52,48,3.0,12/02/2025 20:52,Bloating,18.75,2025-11-06 19:16:40.445350
231,27.0,45.0,-3.0,Low,63.0,Vegetarian,12/02/2025 20:52,46,7.0,30/03/2025 20:52,Cramps,18.75,2025-11-06 19:16:40.445350
232,27.0,45.0,3.0,High,63.0,Vegetarian,30/03/2025 20:52,25,5.0,24/04/2025 20:52,Headache,18.75,2025-11-06 19:16:40.445350
233,27.0,45.0,3.0,High,63.0,Vegetarian,24/04/2025 20:52,26,4.0,20/05/2025 20:52,Fatigue,18.75,2025-11-06 19:16:40.445350
234,27.0,45.0,3.0,High,63.0,Vegetarian,20/05/2025 20:52,46,6.0,05/07/2025 20:52,Bloating,18.75,2025-11-06 19:16:40.445350
235,27.0,45.0,3.0,High,63.0,Vegetarian,05/07/2025 20:52,41,7.0,15/08/2025 20:52,Mood Swings,18.75,2025-11-06 19:16:40.445350
236,27.0,45.0,3.0,High,63.0,Vegetarian,15/08/2025 20:52,38,4.0,22/09/2025 20:52,Headache,18.75,2025-11-06 19:16:40.445350
329,38.0,45.0,4.0,Low,56.0,Low Carb,06/10/2024 20:52,31,6.0,06/11/2024 20:52,Cramps,18.72,2025-11-06 19:16:40.445350
330,38.0,45.0,4.0,Low,56.0,Low Carb,06/11/2024 20:52,42,5.0,18/12/2024 20:52,Mood Swings,18.72,2025-11-06 19:16:40.445350
331,38.0,45.0,4.0,Low,56.0,Low Carb,18/12/2024 20:52,31,4.0,18/01/2025 20:52,Headache,18.72,2025-11-06 19:16:40.445350
332,38.0,45.0,4.0,Low,56.0,Low Carb,18/01/2025 20:52,48,4.0,07/03/2025 20:52,Cramps,18.72,2025-11-06 19:16:40.445350
333,38.0,45.0,4.0,Low,56.0,Low Carb,07/03/2025 20:52,32,4.0,08/04/2025 20:52,Fatigue,18.72,2025-11-06 19:16:40.445350
334,38.0,45.0,4.0,Low,56.0,Low Carb,08/04/2025 20:52,29,6.0,07/05/2025 20:52,Headache,18.72,2025-11-06 19:16:40.445350
335,38.0,45.0,4.0,Low,56.0,Low Carb,07/05/2025 20:52,29,3.0,05/06/2025 20:52,Cramps,18.72,2025-11-06 19:16:40.445350
336,38.0,45.0,4.0,Low,56.0,Low Carb,05/06/2025 20:52,26,7.0,01/07/2025 20:52,Mood Swings,18.72,2025-11-06 19:16:40.445350
337,38.0,45.0,4.0,Low,56.0,Low Carb,01/07/2025 20:52,39,6.0,09/08/2025 20:52,Mood Swings,18.72,2025-11-06 19:16:40.445350
338,38.0,45.0,4.0,Low,56.0,Low Carb,09/08/2025 20:52,48,7.0,26/09/2025 20:52,Mood Swings,18.72,2025-11-06 19:16:40.445350
636,73.0,45.0,1.0,Moderate,87.0,Vegetarian,10/11/2023 20:52,27,4.0,07/12/2023 20:52,Headache,27.71,2025-11-06 19:16:40.445350
637,73.0,45.0,1.0,Moderate,87.0,Vegetarian,07/12/2023 20:52,35,5.0,11/01/2024 20:52,Cramps,27.71,2025-11-06 19:16:40.445350
638,73.0,45.0,1.0,Moderate,87.0,Vegetarian,11/01/2024 20:52,40,5.0,20/02/2024 20:52,Mood Swings,27.71,2025-11-06 19:16:40.445350
639,73.0,45.0,1.0,Moderate,87.0,Vegetarian,20/02/2024 20:52,32,5.0,23/03/2024 20:52,Mood Swings,27.71,2025-11-06 19:16:40.445350
640,73.0,45.0,1.0,Moderate,87.0,Vegetarian,23/03/2024 20:52,42,3.0,04/05/2024 20:52,Headache,27.71,2025-11-06 19:16:40.445350
641,73.0,45.0,1.0,Moderate,87.0,Vegetarian,04/05/2024 20:52,27,6.0,31/05/2024 20:52,Cramps,27.71,2025-11-06 19:16:40.445350
642,73.0,45.0,1.0,Moderate,87.0,Vegetarian,31/05/2024 20:52,31,5.0,01/07/2024 20:52,Headache,27.71,2025-11-06 19:16:40.445350
643,73.0,45.0,1.0,Moderate,87.0,Vegetarian,01/07/2024 20:52,31,6.0,01/08/2024 20:52,Cramps,27.71,2025-11-06 19:16:40.445350
644,73.0,45.0,1.0,Moderate,87.0,Vegetarian,01/08/2024 20:52,34,6.0,04/09/2024 20:52,Cramps,27.71,2025-11-06 19:16:40.445350
748,85.0,45.0,3.0,Low,83.0,High Sugar,27/03/2024 20:52,33,7.0,29/04/2024 20:52,Bloating,24.23,2025-11-06 19:16:40.445350
749,85.0,45.0,3.0,Low,83.0,High Sugar,29/04/2024 20:52,33,5.0,01/06/2024 20:52,Headache,24.23,2025-11-06 19:16:40.445350
750,85.0,45.0,3.0,Low,83.0,High Sugar,01/06/2024 20:52,29,6.0,30/06/2024 20:52,Fatigue,24.23,2025-11-06 19:16:40.445350
751,85.0,45.0,3.0,Low,83.0,High Sugar,30/06/2024 20:52,50,6.0,19/08/2024 20:52,Fatigue,24.23,2025-11-06 19:16:40.445350
752,85.0,45.0,3.0,Low,83.0,High Sugar,19/08/2024 20:52,32,3.0,20/09/2024 20:52,Bloating,24.23,2025-11-06 19:16:40.445350
753,85.0,45.0,3.0,Low,83.0,High Sugar,20/09/2024 20:52,35,7.0,25/10/2024 20:52,Mood Swings,24.23,2025-11-06 19:16:40.445350
754,85.0,45.0,3.0,Low,83.0,High Sugar,25/10/2024 20:52,37,4.0,01/12/2024 20:52,Bloating,24.23,2025-11-06 19:16:40.445350

##### Edad

In [491]:
bronze_menstrual_cycle_edades_df = bronze_menstrual_cycle_df

In [492]:
bronze_menstrual_cycle_edades_df[bronze_menstrual_cycle_df['Age'].isnull() == True]

,User ID,Age,Stress Level,Exercise Frequency,Sleep Hours,Diet,Cycle Start Date,Cycle Length,Period Length,Next Cycle Start Date,Symptoms,BMI,_BronzeTimestamp
177,19.0,NaN,1.0,Low,80.0,Balanced,12/07/2025 20:52,28,4.0,09/08/2025 20:52,Bloating,21.57,2025-11-06 19:16:40.445350
180,20.0,NaN,4.0,Low,75.0,Low Carb,17/01/2024 20:52,500,7.0,29/02/2024 20:52,Bloating,24.82,2025-11-06 19:16:40.445350
181,20.0,NaN,4.0,Low,75.0,Low Carb,29/02/2024 20:52,5000,5.0,29/03/2024 20:52,Bloating,24.82,2025-11-06 19:16:40.445350

In [493]:
# Edades asociadas a cada usuario
with pd.option_context('display.max_rows',None,'display.max_columns',None):
    print(bronze_menstrual_cycle_edades_df.groupby('User ID')['Age'].unique())

User ID
1.0                  [18.0]
2.0                  [34.0]
3.0                  [22.0]
4.0                  [25.0]
5.0                  [25.0]
6.0                  [44.0]
7.0                  [75.0]
8.0                  [37.0]
9.0                  [24.0]
10.0                 [33.0]
11.0                 [20.0]
12.0                 [29.0]
13.0                 [35.0]
14.0                 [26.0]
15.0                 [39.0]
16.0                 [23.0]
17.0                [140.0]
18.0                 [20.0]
19.0            [21.0, nan]
20.0            [45.0, nan]
21.0                 [19.0]
22.0                 [33.0]
23.0                 [44.0]
24.0                 [19.0]
25.0                 [26.0]
26.0                 [28.0]
27.0                 [45.0]
28.0                 [19.0]
29.0     [27.0, 38.0, 37.0]
31.0                 [37.0]
32.0                 [25.0]
33.0                 [44.0]
34.0                 [32.0]
35.0                 [29.0]
36.0                 [31.0]
37.0                 [44.0]
38.0                 [45.0]
39.0                 [23.0]
40.0                 [18.0]
41.0                 [33.0]
42.0                 [24.0]
43.0                 [28.0]
44.0                 [26.0]
45.0                 [21.0]
46.0                 [25.0]
47.0                 [25.0]
48.0                 [42.0]
49.0                 [35.0]
50.0                 [38.0]
51.0                 [35.0]
52.0                 [26.0]
53.0                 [43.0]
54.0                 [26.0]
55.0                 [31.0]
56.0                 [31.0]
57.0                 [39.0]
58.0                 [39.0]
59.0                 [30.0]
60.0                 [39.0]
61.0                 [33.0]
62.0                 [40.0]
63.0                 [21.0]
64.0                 [22.0]
65.0                 [41.0]
66.0                 [20.0]
67.0                 [25.0]
68.0                 [44.0]
69.0                 [31.0]
70.0                 [34.0]
71.0                 [34.0]
72.0                 [38.0]
73.0                 [45.0]
74.0                 [34.0]
75.0                 [27.0]
76.0                 [40.0]
77.0                 [28.0]
78.0                 [37.0]
79.0                 [22.0]
80.0                 [35.0]
81.0                 [36.0]
82.0                 [42.0]
83.0                 [25.0]
84.0                 [40.0]
85.0                 [45.0]
86.0                 [36.0]
87.0                 [44.0]
88.0                 [18.0]
89.0                 [20.0]
90.0                 [30.0]
91.0                 [32.0]
92.0                 [29.0]
93.0                 [21.0]
94.0                 [20.0]
95.0                 [27.0]
96.0                 [44.0]
97.0                 [37.0]
98.0                 [19.0]
99.0                 [39.0]
100.0                [22.0]
Name: Age, dtype: object

In [494]:
def reasignar_edades_nulas(fila, df):
    if pd.isnull(fila['Age']):
        coincidencia = df[(df['User ID'] == fila['User ID']) & 
                   (df['Age'].notnull())]
        if len(coincidencia) > 0:
            return coincidencia['Age'].iloc[0]
        else:
            return None
    else:
        return fila['Age']

In [495]:
bronze_menstrual_cycle_edades_df['Age'] = bronze_menstrual_cycle_edades_df.apply(
    lambda fila: reasignar_edades_nulas(fila, bronze_menstrual_cycle_edades_df),
    axis=1
)

In [496]:
with pd.option_context('display.max_rows',None,'display.max_columns',None):
    print(bronze_menstrual_cycle_edades_df.groupby('User ID')['Age'].unique())

User ID
1.0                  [18.0]
2.0                  [34.0]
3.0                  [22.0]
4.0                  [25.0]
5.0                  [25.0]
6.0                  [44.0]
7.0                  [75.0]
8.0                  [37.0]
9.0                  [24.0]
10.0                 [33.0]
11.0                 [20.0]
12.0                 [29.0]
13.0                 [35.0]
14.0                 [26.0]
15.0                 [39.0]
16.0                 [23.0]
17.0                [140.0]
18.0                 [20.0]
19.0                 [21.0]
20.0                 [45.0]
21.0                 [19.0]
22.0                 [33.0]
23.0                 [44.0]
24.0                 [19.0]
25.0                 [26.0]
26.0                 [28.0]
27.0                 [45.0]
28.0                 [19.0]
29.0     [27.0, 38.0, 37.0]
31.0                 [37.0]
32.0                 [25.0]
33.0                 [44.0]
34.0                 [32.0]
35.0                 [29.0]
36.0                 [31.0]
37.0                 [44.0]
38.0                 [45.0]
39.0                 [23.0]
40.0                 [18.0]
41.0                 [33.0]
42.0                 [24.0]
43.0                 [28.0]
44.0                 [26.0]
45.0                 [21.0]
46.0                 [25.0]
47.0                 [25.0]
48.0                 [42.0]
49.0                 [35.0]
50.0                 [38.0]
51.0                 [35.0]
52.0                 [26.0]
53.0                 [43.0]
54.0                 [26.0]
55.0                 [31.0]
56.0                 [31.0]
57.0                 [39.0]
58.0                 [39.0]
59.0                 [30.0]
60.0                 [39.0]
61.0                 [33.0]
62.0                 [40.0]
63.0                 [21.0]
64.0                 [22.0]
65.0                 [41.0]
66.0                 [20.0]
67.0                 [25.0]
68.0                 [44.0]
69.0                 [31.0]
70.0                 [34.0]
71.0                 [34.0]
72.0                 [38.0]
73.0                 [45.0]
74.0                 [34.0]
75.0                 [27.0]
76.0                 [40.0]
77.0                 [28.0]
78.0                 [37.0]
79.0                 [22.0]
80.0                 [35.0]
81.0                 [36.0]
82.0                 [42.0]
83.0                 [25.0]
84.0                 [40.0]
85.0                 [45.0]
86.0                 [36.0]
87.0                 [44.0]
88.0                 [18.0]
89.0                 [20.0]
90.0                 [30.0]
91.0                 [32.0]
92.0                 [29.0]
93.0                 [21.0]
94.0                 [20.0]
95.0                 [27.0]
96.0                 [44.0]
97.0                 [37.0]
98.0                 [19.0]
99.0                 [39.0]
100.0                [22.0]
Name: Age, dtype: object

##### Stress level

In [497]:
bronze_menstrual_cycle_stresslevel_df = bronze_menstrual_cycle_edades_df

In [498]:
bronze_menstrual_cycle_stresslevel_df[bronze_menstrual_cycle_stresslevel_df['Stress Level'].isnull() == True]

,User ID,Age,Stress Level,Exercise Frequency,Sleep Hours,Diet,Cycle Start Date,Cycle Length,Period Length,Next Cycle Start Date,Symptoms,BMI,_BronzeTimestamp
38,4.0,25.0,NaN,Moderate,83.0,Vegetarian,08/02/2025 20:52,29,5.0,09/03/2025 20:52,Fatigue,25.68,2025-11-06 19:16:40.445350
53,6.0,44.0,NaN,Low,61.0,Low Carb,03/06/2023 20:52,39,NaN,12/07/2023 20:52,Mood Swings,25.87,2025-11-06 19:16:40.445350

In [499]:
# Rellenamos los valores nulos con la media de valores de Stress level del usuario correspondiente (User ID).
bronze_menstrual_cycle_stresslevel_df['Stress Level'] = bronze_menstrual_cycle_stresslevel_df.groupby('User ID')['Stress Level'].transform(
    lambda x: x.fillna(x.mean())
)

##### Exercise frecuency

In [500]:
bronze_menstrual_cycle_exercisefrequency_df = bronze_menstrual_cycle_stresslevel_df

In [501]:
# Siendo un unico valor nulo, no añadimos una categoria mas "desconcocida" ya que a la hora de analizar perdemos agrupacion
# Rellenamos el nulo con la categoria mas repetida o moda
fill_values = {
    "Exercise Frequency": bronze_menstrual_cycle_exercisefrequency_df['Exercise Frequency'].mode()[0]
}
# [0] al final por si hay un empate que escoja el primer valor categorico mas repetido

In [502]:
# Aplico la limpieza
bronze_menstrual_cycle_exercisefrequency_df = bronze_menstrual_cycle_exercisefrequency_df.fillna(fill_values)

In [503]:
bronze_menstrual_cycle_exercisefrequency_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 895 entries, 0 to 894
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   User ID                895 non-null    float64
 1   Age                    895 non-null    float64
 2   Stress Level           895 non-null    float64
 3   Exercise Frequency     895 non-null    object
 4   Sleep Hours            893 non-null    float64
 5   Diet                   895 non-null    object
 6   Cycle Start Date       895 non-null    object
 7   Cycle Length           895 non-null    int64
 8   Period Length          892 non-null    float64
 9   Next Cycle Start Date  895 non-null    object
 10  Symptoms               895 non-null    object
 11  BMI                    895 non-null    float64
 12  _BronzeTimestamp       895 non-null    datetime64[us]
dtypes: datetime64[us](1), float64(6), int64(1), object(5)
memory usage: 91.0+ KB

##### Period length & Sleep hours

In [504]:
bronze_menstrual_cycle_periodlength_df = bronze_menstrual_cycle_exercisefrequency_df

In [505]:
# las filas asociadas a las variables numericas duracion del periodo y horas dormidas serán rellenadas con la media de duraciones de dicho usuario
bronze_menstrual_cycle_periodlength_df['Period Length'] = bronze_menstrual_cycle_periodlength_df.groupby('User ID')['Period Length'].transform(lambda x:x.fillna(x.mean()))

In [506]:
bronze_menstrual_cycle_sleephours_df = bronze_menstrual_cycle_periodlength_df

In [507]:
bronze_menstrual_cycle_sleephours_df['Sleep Hours'] = bronze_menstrual_cycle_sleephours_df.groupby('User ID')['Sleep Hours'].transform(lambda x:x.fillna(x.mean()))

In [508]:
bronze_menstrual_cycle_sleephours_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 895 entries, 0 to 894
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   User ID                895 non-null    float64
 1   Age                    895 non-null    float64
 2   Stress Level           895 non-null    float64
 3   Exercise Frequency     895 non-null    object
 4   Sleep Hours            895 non-null    float64
 5   Diet                   895 non-null    object
 6   Cycle Start Date       895 non-null    object
 7   Cycle Length           895 non-null    int64
 8   Period Length          895 non-null    float64
 9   Next Cycle Start Date  895 non-null    object
 10  Symptoms               895 non-null    object
 11  BMI                    895 non-null    float64
 12  _BronzeTimestamp       895 non-null    datetime64[us]
dtypes: datetime64[us](1), float64(6), int64(1), object(5)
memory usage: 91.0+ KB

In [509]:
bronze_menstrual_cycle_sleephours_df[bronze_menstrual_cycle_sleephours_df['Next Cycle Start Date'].isnull() == True]

Empty DataFrame
Columns: [User ID, Age, Stress Level, Exercise Frequency, Sleep Hours, Diet, Cycle Start Date, Cycle Length, Period Length, Next Cycle Start Date, Symptoms, BMI, _BronzeTimestamp]
Index: []

#### Duplicados

In [510]:
# User ID en este caso puede, y debe, estar duplicada ya que hay varios registros por persona para analizar 
# varios ciclos menstruales

In [511]:
# Las unicas columnas criticas en conjunto son User ID y Cycle start date. Si un mismo user tiene dos fechas de inicio
# de ciclo duplicadas, no tendría sentido (al igual que fechas de fin de periodo).
duplicados = bronze_menstrual_cycle_sleephours_df.duplicated(subset=['User ID', 'Cycle Start Date'], keep=False)
bronze_menstrual_cycle_sleephours_df[duplicados].sort_values(['User ID', 'Cycle Start Date'])

Empty DataFrame
Columns: [User ID, Age, Stress Level, Exercise Frequency, Sleep Hours, Diet, Cycle Start Date, Cycle Length, Period Length, Next Cycle Start Date, Symptoms, BMI, _BronzeTimestamp]
Index: []

In [512]:
# comprobamos si hay varias edades asociadas a un mismo user
# Si esas edades son contiguas puede tener sentido. Si no, las filas son eliminadas
with pd.option_context('display.max_rows',None,'display.max_columns',None):
    print(bronze_menstrual_cycle_sleephours_df.groupby('User ID')['Age'].unique())

User ID
1.0                  [18.0]
2.0                  [34.0]
3.0                  [22.0]
4.0                  [25.0]
5.0                  [25.0]
6.0                  [44.0]
7.0                  [75.0]
8.0                  [37.0]
9.0                  [24.0]
10.0                 [33.0]
11.0                 [20.0]
12.0                 [29.0]
13.0                 [35.0]
14.0                 [26.0]
15.0                 [39.0]
16.0                 [23.0]
17.0                [140.0]
18.0                 [20.0]
19.0                 [21.0]
20.0                 [45.0]
21.0                 [19.0]
22.0                 [33.0]
23.0                 [44.0]
24.0                 [19.0]
25.0                 [26.0]
26.0                 [28.0]
27.0                 [45.0]
28.0                 [19.0]
29.0     [27.0, 38.0, 37.0]
31.0                 [37.0]
32.0                 [25.0]
33.0                 [44.0]
34.0                 [32.0]
35.0                 [29.0]
36.0                 [31.0]
37.0                 [44.0]
38.0                 [45.0]
39.0                 [23.0]
40.0                 [18.0]
41.0                 [33.0]
42.0                 [24.0]
43.0                 [28.0]
44.0                 [26.0]
45.0                 [21.0]
46.0                 [25.0]
47.0                 [25.0]
48.0                 [42.0]
49.0                 [35.0]
50.0                 [38.0]
51.0                 [35.0]
52.0                 [26.0]
53.0                 [43.0]
54.0                 [26.0]
55.0                 [31.0]
56.0                 [31.0]
57.0                 [39.0]
58.0                 [39.0]
59.0                 [30.0]
60.0                 [39.0]
61.0                 [33.0]
62.0                 [40.0]
63.0                 [21.0]
64.0                 [22.0]
65.0                 [41.0]
66.0                 [20.0]
67.0                 [25.0]
68.0                 [44.0]
69.0                 [31.0]
70.0                 [34.0]
71.0                 [34.0]
72.0                 [38.0]
73.0                 [45.0]
74.0                 [34.0]
75.0                 [27.0]
76.0                 [40.0]
77.0                 [28.0]
78.0                 [37.0]
79.0                 [22.0]
80.0                 [35.0]
81.0                 [36.0]
82.0                 [42.0]
83.0                 [25.0]
84.0                 [40.0]
85.0                 [45.0]
86.0                 [36.0]
87.0                 [44.0]
88.0                 [18.0]
89.0                 [20.0]
90.0                 [30.0]
91.0                 [32.0]
92.0                 [29.0]
93.0                 [21.0]
94.0                 [20.0]
95.0                 [27.0]
96.0                 [44.0]
97.0                 [37.0]
98.0                 [19.0]
99.0                 [39.0]
100.0                [22.0]
Name: Age, dtype: object

In [513]:
# El user nº 29 tiene 3 edades distintas. Una de ellas muy alejada de lo real (27 años)
# Eliminamos dichas coincidencias
bronze_menstrual_cycle_variasedades_df = bronze_menstrual_cycle_sleephours_df[~(
    (bronze_menstrual_cycle_sleephours_df['Age'] == 27)
    &
    (bronze_menstrual_cycle_sleephours_df['User ID'] == 29))
]

In [514]:
with pd.option_context('display.max_rows',None,'display.max_columns',None):
    print(bronze_menstrual_cycle_variasedades_df.groupby('User ID')['Age'].unique())

User ID
1.0            [18.0]
2.0            [34.0]
3.0            [22.0]
4.0            [25.0]
5.0            [25.0]
6.0            [44.0]
7.0            [75.0]
8.0            [37.0]
9.0            [24.0]
10.0           [33.0]
11.0           [20.0]
12.0           [29.0]
13.0           [35.0]
14.0           [26.0]
15.0           [39.0]
16.0           [23.0]
17.0          [140.0]
18.0           [20.0]
19.0           [21.0]
20.0           [45.0]
21.0           [19.0]
22.0           [33.0]
23.0           [44.0]
24.0           [19.0]
25.0           [26.0]
26.0           [28.0]
27.0           [45.0]
28.0           [19.0]
29.0     [38.0, 37.0]
31.0           [37.0]
32.0           [25.0]
33.0           [44.0]
34.0           [32.0]
35.0           [29.0]
36.0           [31.0]
37.0           [44.0]
38.0           [45.0]
39.0           [23.0]
40.0           [18.0]
41.0           [33.0]
42.0           [24.0]
43.0           [28.0]
44.0           [26.0]
45.0           [21.0]
46.0           [25.0]
47.0           [25.0]
48.0           [42.0]
49.0           [35.0]
50.0           [38.0]
51.0           [35.0]
52.0           [26.0]
53.0           [43.0]
54.0           [26.0]
55.0           [31.0]
56.0           [31.0]
57.0           [39.0]
58.0           [39.0]
59.0           [30.0]
60.0           [39.0]
61.0           [33.0]
62.0           [40.0]
63.0           [21.0]
64.0           [22.0]
65.0           [41.0]
66.0           [20.0]
67.0           [25.0]
68.0           [44.0]
69.0           [31.0]
70.0           [34.0]
71.0           [34.0]
72.0           [38.0]
73.0           [45.0]
74.0           [34.0]
75.0           [27.0]
76.0           [40.0]
77.0           [28.0]
78.0           [37.0]
79.0           [22.0]
80.0           [35.0]
81.0           [36.0]
82.0           [42.0]
83.0           [25.0]
84.0           [40.0]
85.0           [45.0]
86.0           [36.0]
87.0           [44.0]
88.0           [18.0]
89.0           [20.0]
90.0           [30.0]
91.0           [32.0]
92.0           [29.0]
93.0           [21.0]
94.0           [20.0]
95.0           [27.0]
96.0           [44.0]
97.0           [37.0]
98.0           [19.0]
99.0           [39.0]
100.0          [22.0]
Name: Age, dtype: object

#### Valores atipicos

##### User ID

In [515]:
sorted(bronze_menstrual_cycle_variasedades_df['User ID'])

[1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 4.0,
 4.0,
 4.0,
 4.0,
 4.0,
 4.0,
 4.0,
 4.0,
 4.0,
 4.0,
 5.0,
 5.0,
 5.0,
 5.0,
 5.0,
 5.0,
 5.0,
 5.0,
 5.0,
 5.0,
 5.0,
 5.0,
 6.0,
 6.0,
 6.0,
 6.0,
 6.0,
 6.0,
 6.0,
 6.0,
 6.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 7.0,
 8.0,
 8.0,
 8.0,
 8.0,
 8.0,
 8.0,
 8.0,
 8.0,
 8.0,
 8.0,
 8.0,
 9.0,
 9.0,
 9.0,
 9.0,
 9.0,
 9.0,
 9.0,
 9.0,
 9.0,
 9.0,
 9.0,
 9.0,
 10.0,
 10.0,
 10.0,
 10.0,
 10.0,
 10.0,
 11.0,
 11.0,
 11.0,
 11.0,
 11.0,
 11.0,
 11.0,
 11.0,
 11.0,
 11.0,
 12.0,
 12.0,
 12.0,
 12.0,
 12.0,
 12.0,
 12.0,
 12.0,
 12.0,
 12.0,
 12.0,
 13.0,
 13.0,
 13.0,
 13.0,
 13.0,
 13.0,
 13.0,
 13.0,
 13.0,
 13.0,
 13.0,
 14.0,
 14.0,
 14.0,
 14.0,
 14.0,
 14.0,
 14.0,
 14.0,
 15.0,
 15.0,
 15.0,
 15.0,
 15.0,
 15.0,
 15.0,
 16.0,
 16.0,
 16.0,
 16.0,
 16.0,
 16.0,
 16.0,
 16.0,
 17.0,
 17.0,
 17.0,
 17.0,
 17.0,
 17.0,
 17.0,
 17.0,
 17.0,
 17.0,
 18.0,
 18.0,
 18.0,
 18.0,
 18.0,
 18.0,
 18.0,
 18.0,
 18.0,
 18.0,
 18.0,
 19.0,
 19.0,
 19.0,
 19.0,
 19.0,
 19.0,
 19.0,
 20.0,
 20.0,
 20.0,
 20.0,
 20.0,
 20.0,
 20.0,
 21.0,
 21.0,
 21.0,
 21.0,
 21.0,
 21.0,
 21.0,
 22.0,
 22.0,
 22.0,
 22.0,
 22.0,
 22.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 24.0,
 24.0,
 24.0,
 24.0,
 24.0,
 24.0,
 24.0,
 24.0,
 24.0,
 24.0,
 25.0,
 25.0,
 25.0,
 25.0,
 25.0,
 25.0,
 25.0,
 26.0,
 26.0,
 26.0,
 26.0,
 26.0,
 26.0,
 26.0,
 27.0,
 27.0,
 27.0,
 27.0,
 27.0,
 27.0,
 27.0,
 28.0,
 28.0,
 28.0,
 28.0,
 28.0,
 28.0,
 28.0,
 28.0,
 29.0,
 29.0,
 29.0,
 29.0,
 29.0,
 29.0,
 29.0,
 29.0,
 29.0,
 29.0,
 29.0,
 29.0,
 31.0,
 31.0,
 31.0,
 31.0,
 31.0,
 31.0,
 31.0,
 31.0,
 31.0,
 31.0,
 32.0,
 32.0,
 32.0,
 32.0,
 32.0,
 32.0,
 32.0,
 32.0,
 33.0,
 33.0,
 33.0,
 33.0,
 33.0,
 33.0,
 33.0,
 33.0,
 34.0,
 34.0,
 34.0,
 34.0,
 34.0,
 34.0,
 34.0,
 34.0,
 34.0,
 34.0,
 34.0,
 35.0,
 35.0,
 35.0,
 35.0,
 35.0,
 35.0,
 36.0,
 36.0,
 36.0,
 36.0,
 36.0,
 36.0,
 37.0,
 37.0,
 37.0,
 37.0,
 37.0,
 37.0,
 37.0,
 37.0,
 37.0,
 37.0,
 37.0,
 38.0,
 38.0,
 38.0,
 38.0,
 38.0,
 38.0,
 38.0,
 38.0,
 38.0,
 38.0,
 39.0,
 39.0,
 39.0,
 39.0,
 39.0,
 39.0,
 40.0,
 40.0,
 40.0,
 40.0,
 40.0,
 40.0,
 40.0,
 40.0,
 40.0,
 40.0,
 41.0,
 41.0,
 41.0,
 41.0,
 41.0,
 41.0,
 41.0,
 41.0,
 41.0,
 41.0,
 41.0,
 41.0,
 42.0,
 42.0,
 42.0,
 42.0,
 42.0,
 42.0,
 42.0,
 42.0,
 42.0,
 42.0,
 43.0,
 43.0,
 43.0,
 43.0,
 43.0,
 43.0,
 44.0,
 44.0,
 44.0,
 44.0,
 44.0,
 44.0,
 44.0,
 44.0,
 44.0,
 44.0,
 44.0,
 45.0,
 45.0,
 45.0,
 45.0,
 45.0,
 45.0,
 45.0,
 45.0,
 46.0,
 46.0,
 46.0,
 46.0,
 46.0,
 46.0,
 46.0,
 46.0,
 46.0,
 46.0,
 47.0,
 47.0,
 47.0,
 47.0,
 47.0,
 47.0,
 47.0,
 48.0,
 48.0,
 48.0,
 48.0,
 48.0,
 48.0,
 48.0,
 48.0,
 48.0,
 48.0,
 49.0,
 49.0,
 49.0,
 49.0,
 49.0,
 49.0,
 49.0,
 49.0,
 49.0,
 49.0,
 49.0,
 49.0,
 50.0,
 50.0,
 50.0,
 50.0,
 50.0,
 50.0,
 51.0,
 51.0,
 51.0,
 51.0,
 51.0,
 51.0,
 51.0,
 51.0,
 51.0,
 51.0,
 52.0,
 52.0,
 52.0,
 52.0,
 52.0,
 52.0,
 52.0,
 52.0,
 52.0,
 52.0,
 52.0,
 53.0,
 53.0,
 53.0,
 53.0,
 53.0,
 53.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 55.0,
 55.0,
 55.0,
 55.0,
 55.0,
 55.0,
 55.0,
 55.0,
 55.0,
 55.0,
 55.0,
 55.0,
 56.0,
 56.0,
 56.0,
 56.0,
 56.0,
 56.0,
 56.0,
 56.0,
 56.0,
 56.0,
 56.0,
 56.0,
 57.0,
 57.0,
 57.0,
 57.0,
 57.0,
 57.0,
 57.0,
 57.0,
 58.0,
 58.0,
 58.0,
 58.0,
 58.0,
 58.0,
 58.0,
 58.0,
 58.0,
 59.0,
 59.0,
 59.0,
 59.0,
 59.0,
 59.0,
 59.0,
 60.0,
 60.0,
 60.0,
 60.0,
 60.0,
 60.0,
 60.0,
 60.0,
 60.0,
 60.0,
 61.0,
 61.0,
 61.0,
 61.0,
 61.0,
 61.0,
 62.0,
 62.0,
 62.0,
 62.0,
 62.0,
 62.0,
 62.0,
 63.0,
 63.0,
 63.0,
 63.0,
 63.0,
 63.0,
 63.0,
 63.0,
 63.0,
 63.0,
 64.0,
 64.0,
 64.0,
 64.0,
 64.0,
 64.0,
 64.0,
 65.0,
 65.0,
 65.0,
 65.0,
 65.0,
 65.0,
 65.0,
 65.0,
 66.0,
 66.0,
 66.0,
 66.0,
 66.0,
 66.0,
 66.0,
 66.0,
 66.0,
 66.0,
 66.0,
 67.0,
 67.0,
 67.0,
 67.0,
 67.0,
 67.0,
 68.0,
 68.0,
 68.0,
 68.0,
 68.0,
 68.0,
 68.0,
 68.0,
 68.0,
 69.0,
 69.0,
 69.0,
 69.0,
 69.0,
 69.0,
 69.0,
 70.0,
 70.0,
 70.0,
 70.0,
 70.0,
 70.0,
 70.0,
 70.0,
 70.0,
 70.0,
 70.0,
 71.0,
 71.0,
 71.0,
 71.0,
 71.0,
 71.0,
 71.0,
 72.0,
 72.0,
 72.0,
 72.0,
 72.0,
 72.0,
 73.0,
 73.0,
 73.0,
 73.0,
 73.0,
 73.0,
 73.0,
 73.0,
 73.0,
 74.0,
 74.0,
 74.0,
 74.0,
 74.0,
 74.0,
 74.0,
 74.0,
 74.0,
 74.0,
 74.0,
 74.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 76.0,
 76.0,
 76.0,
 76.0,
 76.0,
 76.0,
 76.0,
 76.0,
 76.0,
 76.0,
 77.0,
 77.0,
 77.0,
 77.0,
 77.0,
 77.0,
 77.0,
 77.0,
 77.0,
 78.0,
 78.0,
 78.0,
 78.0,
 78.0,
 78.0,
 78.0,
 78.0,
 78.0,
 78.0,
 78.0,
 79.0,
 79.0,
 79.0,
 79.0,
 79.0,
 79.0,
 79.0,
 79.0,
 79.0,
 79.0,
 80.0,
 80.0,
 80.0,
 80.0,
 80.0,
 80.0,
 80.0,
 80.0,
 80.0,
 80.0,
 81.0,
 81.0,
 81.0,
 81.0,
 81.0,
 81.0,
 81.0,
 82.0,
 82.0,
 82.0,
 82.0,
 82.0,
 82.0,
 82.0,
 83.0,
 83.0,
 83.0,
 83.0,
 83.0,
 83.0,
 83.0,
 83.0,
 83.0,
 83.0,
 84.0,
 84.0,
 84.0,
 84.0,
 84.0,
 84.0,
 85.0,
 85.0,
 85.0,
 85.0,
 85.0,
 85.0,
 85.0,
 86.0,
 86.0,
 86.0,
 86.0,
 86.0,
 86.0,
 86.0,
 86.0,
 87.0,
 87.0,
 87.0,
 87.0,
 87.0,
 87.0,
 87.0,
 87.0,
 87.0,
 87.0,
 87.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 89.0,
 89.0,
 89.0,
 89.0,
 89.0,
 89.0,
 89.0,
 89.0,
 89.0,
 90.0,
 90.0,
 90.0,
 90.0,
 90.0,
 90.0,
 90.0,
 90.0,
 91.0,
 91.0,
 91.0,
 91.0,
 91.0,
 91.0,
 91.0,
 91.0,
 91.0,
 91.0,
 91.0,
 91.0,
 92.0,
 92.0,
 92.0,
 92.0,
 92.0,
 92.0,
 92.0,
 92.0,
 92.0,
 92.0,
 92.0,
 92.0,
 93.0,
 93.0,
 93.0,
 93.0,
 93.0,
 93.0,
 93.0,
 93.0,
 93.0,
 93.0,
 94.0,
 94.0,
 94.0,
 94.0,
 94.0,
 94.0,
 94.0,
 94.0,
 94.0,
 94.0,
 95.0,
 95.0,
 95.0,
 95.0,
 95.0,
 95.0,
 95.0,
 96.0,
 96.0,
 96.0,
 96.0,
 96.0,
 96.0,
 96.0,
 96.0,
 97.0,
 97.0,
 97.0,
 97.0,
 97.0,
 97.0,
 97.0,
 98.0,
 98.0,
 98.0,
 98.0,
 98.0,
 98.0,
 98.0,
 98.0,
 99.0,
 99.0,
 99.0,
 99.0,
 99.0,
 99.0,
 99.0,
 99.0,
 99.0,
 99.0,
 99.0,
 100.0,
 100.0,
 100.0,
 100.0,
 100.0,
 100.0,
 100.0]

##### Edad

In [516]:
# Comporbamos valores fuera de rango en la columna edad.
# La menstruación generalmente comienza a los 16-20 años, y finaliza en la edad de la menopausia, que ocurre a los 45-55 años.
bronze_menstrual_cycle_variasedades_df['Age'].value_counts()

Age
44.0     63
25.0     63
20.0     51
26.0     46
39.0     45
35.0     43
37.0     40
45.0     40
34.0     39
31.0     37
21.0     35
22.0     34
19.0     33
18.0     33
33.0     30
29.0     29
32.0     23
38.0     23
40.0     23
24.0     22
28.0     22
27.0     18
42.0     17
36.0     15
30.0     15
23.0     14
140.0    10
41.0      8
75.0      6
43.0      6
Name: count, dtype: int64

In [517]:
# eliminamos todos los registros asociados a edades erroneas
bronze_menstrual_cycle_sin_atipicos_df = bronze_menstrual_cycle_variasedades_df[bronze_menstrual_cycle_df['Age'] <= 55]

C:\Users\cadav\AppData\Local\Temp\ipykernel_11152\882517079.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  bronze_menstrual_cycle_sin_atipicos_df = bronze_menstrual_cycle_variasedades_df[bronze_menstrual_cycle_df['Age'] <= 55]

In [518]:
bronze_menstrual_cycle_sin_atipicos_df['Age'].value_counts()

Age
25.0    63
44.0    63
20.0    51
26.0    46
39.0    45
35.0    43
45.0    40
37.0    40
34.0    39
31.0    37
21.0    35
22.0    34
19.0    33
18.0    33
33.0    30
29.0    29
40.0    23
32.0    23
38.0    23
24.0    22
28.0    22
27.0    18
42.0    17
36.0    15
30.0    15
23.0    14
41.0     8
43.0     6
Name: count, dtype: int64

##### Stress level

In [519]:
bronze_menstrual_cycle_sin_atipicos_df['Stress Level'].value_counts()

Stress Level
 4.0      226
 1.0      183
 2.0      158
 5.0      156
 3.0      142
 200.0      1
-3.0        1
Name: count, dtype: int64

In [520]:
bronze_menstrual_cycle_abs_df = bronze_menstrual_cycle_sin_atipicos_df

In [521]:
bronze_menstrual_cycle_abs_df['Stress Level']=bronze_menstrual_cycle_abs_df['Stress Level'].abs()

C:\Users\cadav\AppData\Local\Temp\ipykernel_11152\2185569480.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bronze_menstrual_cycle_abs_df['Stress Level']=bronze_menstrual_cycle_abs_df['Stress Level'].abs()

In [522]:
bronze_menstrual_cycle_abs_df['Stress Level'].value_counts()

Stress Level
4.0      226
1.0      183
2.0      158
5.0      156
3.0      143
200.0      1
Name: count, dtype: int64

In [523]:
# Eliminamos todos los registros mayores a 5 (maximo de la escala)
bronze_menstrual_cycle_stresslevel2_df = bronze_menstrual_cycle_abs_df[bronze_menstrual_cycle_abs_df['Stress Level'] <= 5]

In [524]:
bronze_menstrual_cycle_stresslevel2_df['Stress Level'].value_counts()

Stress Level
4.0    226
1.0    183
2.0    158
5.0    156
3.0    143
Name: count, dtype: int64

##### BMI

In [525]:
bronze_menstrual_cycle_stresslevel2_df['BMI'].value_counts()

BMI
24.41     17
28.82     15
25.52     12
25.45     12
25.27     12
          ..
21.47      6
20.02      6
20.99      6
222.00     1
200.00     1
Name: count, Length: 97, dtype: int64

In [526]:
# Eliminamos todos los registros mayores a 80 (maximo valor en casos medicos extremos)
bronze_menstrual_cycle_BMI_df = bronze_menstrual_cycle_stresslevel2_df[bronze_menstrual_cycle_stresslevel2_df['BMI'] <= 80]

In [527]:
bronze_menstrual_cycle_BMI_df['BMI'].value_counts()

BMI
24.41    17
28.82    15
25.52    12
24.64    12
18.83    12
         ..
21.47     6
18.59     6
23.97     6
20.02     6
20.99     6
Name: count, Length: 95, dtype: int64

##### Period length

In [528]:
bronze_menstrual_cycle_BMI_df['Period Length'].value_counts()

Period Length
5.000000    189
4.000000    175
6.000000    173
7.000000    168
3.000000    157
5.625000      1
4.111111      1
Name: count, dtype: int64

##### Sleep hours

In [529]:
sorted(bronze_menstrual_cycle_BMI_df['Sleep Hours'])

[51.0,
 51.0,
 51.0,
 51.0,
 51.0,
 51.0,
 51.0,
 51.0,
 51.0,
 51.0,
 51.0,
 51.0,
 51.0,
 51.0,
 51.0,
 51.0,
 51.0,
 51.0,
 51.0,
 51.0,
 52.0,
 52.0,
 52.0,
 52.0,
 52.0,
 52.0,
 52.0,
 52.0,
 52.0,
 52.0,
 52.0,
 52.0,
 52.0,
 52.0,
 52.0,
 52.0,
 52.0,
 52.0,
 52.0,
 52.0,
 52.0,
 52.0,
 52.0,
 52.0,
 52.0,
 53.0,
 53.0,
 53.0,
 53.0,
 53.0,
 53.0,
 53.0,
 53.0,
 53.0,
 53.0,
 53.0,
 53.0,
 53.0,
 53.0,
 53.0,
 53.0,
 53.0,
 53.0,
 53.0,
 53.0,
 53.0,
 53.0,
 53.0,
 53.0,
 53.0,
 53.0,
 53.0,
 53.0,
 53.0,
 53.0,
 53.0,
 53.0,
 53.0,
 53.0,
 53.0,
 53.0,
 53.0,
 53.0,
 53.0,
 53.0,
 53.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 54.0,
 55.0,
 55.0,
 55.0,
 55.0,
 55.0,
 55.0,
 55.0,
 55.0,
 55.0,
 55.0,
 55.0,
 56.0,
 56.0,
 56.0,
 56.0,
 56.0,
 56.0,
 56.0,
 56.0,
 56.0,
 56.0,
 56.0,
 56.0,
 56.0,
 56.0,
 56.0,
 56.0,
 56.0,
 56.0,
 56.0,
 56.0,
 56.0,
 56.0,
 56.0,
 56.0,
 56.0,
 56.0,
 56.0,
 56.0,
 56.0,
 56.0,
 56.0,
 56.0,
 56.0,
 56.0,
 56.0,
 56.0,
 56.0,
 56.0,
 56.0,
 56.0,
 56.0,
 57.0,
 57.0,
 57.0,
 57.0,
 57.0,
 57.0,
 57.0,
 57.0,
 57.0,
 57.0,
 57.0,
 57.0,
 57.0,
 57.0,
 57.0,
 57.0,
 57.0,
 57.0,
 57.0,
 57.0,
 58.0,
 58.0,
 58.0,
 58.0,
 58.0,
 58.0,
 58.0,
 58.0,
 58.0,
 58.0,
 59.0,
 59.0,
 59.0,
 59.0,
 59.0,
 59.0,
 59.0,
 59.0,
 61.0,
 61.0,
 61.0,
 61.0,
 61.0,
 61.0,
 61.0,
 61.0,
 61.0,
 61.0,
 61.0,
 61.0,
 61.0,
 61.0,
 61.0,
 61.0,
 61.0,
 61.0,
 61.0,
 61.0,
 61.0,
 61.0,
 61.0,
 61.0,
 61.0,
 61.0,
 61.0,
 61.0,
 62.0,
 62.0,
 62.0,
 62.0,
 62.0,
 62.0,
 62.0,
 62.0,
 62.0,
 62.0,
 62.0,
 62.0,
 62.0,
 62.0,
 62.0,
 62.0,
 62.0,
 62.0,
 62.0,
 62.0,
 62.0,
 62.0,
 62.0,
 62.0,
 62.0,
 62.0,
 62.0,
 62.0,
 62.0,
 62.0,
 62.0,
 62.0,
 63.0,
 63.0,
 63.0,
 63.0,
 63.0,
 63.0,
 63.0,
 63.0,
 63.0,
 63.0,
 63.0,
 63.0,
 63.0,
 63.0,
 63.0,
 63.0,
 63.0,
 63.0,
 63.0,
 63.0,
 63.0,
 63.0,
 63.0,
 63.0,
 63.0,
 63.0,
 63.0,
 63.0,
 63.0,
 63.0,
 63.0,
 63.0,
 63.0,
 64.0,
 64.0,
 64.0,
 64.0,
 64.0,
 64.0,
 64.0,
 64.0,
 64.0,
 64.0,
 64.0,
 65.0,
 65.0,
 65.0,
 65.0,
 65.0,
 65.0,
 65.0,
 65.0,
 65.0,
 65.0,
 65.0,
 65.0,
 65.0,
 65.0,
 65.0,
 65.0,
 65.0,
 65.0,
 65.0,
 65.0,
 65.0,
 65.0,
 65.0,
 65.0,
 65.0,
 65.0,
 65.0,
 65.0,
 65.0,
 66.0,
 66.0,
 66.0,
 66.0,
 66.0,
 66.0,
 66.0,
 66.0,
 68.0,
 68.0,
 68.0,
 68.0,
 68.0,
 68.0,
 68.0,
 68.0,
 69.0,
 69.0,
 69.0,
 69.0,
 69.0,
 69.0,
 69.0,
 69.0,
 69.0,
 69.0,
 69.0,
 69.0,
 69.0,
 69.0,
 69.0,
 69.0,
 69.0,
 69.0,
 69.0,
 69.0,
 69.0,
 69.0,
 69.0,
 69.0,
 69.0,
 69.0,
 69.0,
 69.0,
 69.0,
 69.0,
 69.0,
 69.0,
 70.0,
 70.0,
 70.0,
 70.0,
 70.0,
 70.0,
 70.0,
 70.0,
 70.0,
 70.0,
 70.0,
 70.0,
 70.0,
 70.0,
 70.0,
 70.0,
 70.0,
 71.0,
 71.0,
 71.0,
 71.0,
 71.0,
 71.0,
 71.0,
 71.0,
 71.0,
 71.0,
 71.0,
 71.0,
 71.0,
 71.0,
 71.0,
 71.0,
 71.0,
 72.0,
 72.0,
 72.0,
 72.0,
 72.0,
 72.0,
 72.0,
 72.0,
 72.0,
 72.0,
 72.0,
 72.0,
 72.0,
 72.0,
 72.0,
 72.0,
 72.0,
 72.0,
 72.0,
 72.0,
 72.0,
 72.0,
 72.0,
 72.0,
 72.0,
 72.0,
 73.0,
 73.0,
 73.0,
 73.0,
 73.0,
 73.0,
 73.0,
 73.0,
 73.0,
 73.0,
 73.0,
 73.0,
 73.0,
 73.0,
 74.0,
 74.0,
 74.0,
 74.0,
 74.0,
 74.0,
 74.0,
 74.0,
 74.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 75.0,
 76.0,
 76.0,
 76.0,
 76.0,
 76.0,
 76.0,
 76.0,
 76.0,
 76.0,
 76.0,
 76.0,
 76.0,
 76.0,
 76.0,
 76.0,
 76.0,
 76.0,
 76.0,
 76.0,
 77.0,
 77.0,
 77.0,
 77.0,
 77.0,
 77.0,
 77.0,
 77.0,
 77.0,
 77.0,
 78.0,
 78.0,
 78.0,
 78.0,
 78.0,
 78.0,
 78.0,
 78.0,
 78.0,
 78.0,
 78.0,
 78.0,
 78.0,
 78.0,
 78.0,
 78.0,
 78.0,
 78.0,
 78.0,
 78.0,
 78.0,
 78.0,
 78.0,
 78.0,
 78.0,
 78.0,
 78.0,
 80.0,
 80.0,
 80.0,
 80.0,
 80.0,
 80.0,
 80.0,
 80.0,
 80.0,
 80.0,
 80.0,
 80.0,
 80.0,
 80.0,
 80.0,
 80.0,
 80.0,
 80.0,
 80.0,
 80.0,
 80.0,
 80.0,
 80.0,
 80.0,
 80.0,
 80.0,
 80.0,
 80.0,
 80.0,
 80.0,
 80.0,
 80.0,
 80.0,
 80.0,
 80.0,
 80.0,
 80.0,
 80.0,
 80.0,
 80.0,
 81.0,
 81.0,
 81.0,
 81.0,
 81.0,
 81.0,
 81.0,
 82.0,
 82.0,
 82.0,
 82.0,
 82.0,
 82.0,
 82.0,
 82.0,
 82.0,
 82.0,
 82.0,
 82.0,
 82.0,
 82.0,
 82.0,
 82.0,
 82.0,
 83.0,
 83.0,
 83.0,
 83.0,
 83.0,
 83.0,
 83.0,
 83.0,
 83.0,
 83.0,
 83.0,
 83.0,
 83.0,
 83.0,
 83.0,
 83.0,
 83.0,
 83.0,
 83.0,
 83.0,
 83.0,
 83.0,
 83.0,
 84.0,
 84.0,
 84.0,
 84.0,
 84.0,
 84.0,
 84.0,
 84.0,
 84.0,
 84.0,
 84.0,
 84.0,
 84.0,
 84.0,
 84.0,
 84.0,
 84.0,
 84.0,
 84.0,
 84.0,
 84.0,
 84.0,
 85.0,
 85.0,
 85.0,
 85.0,
 85.0,
 85.0,
 85.0,
 85.0,
 85.0,
 85.0,
 85.0,
 85.0,
 85.0,
 85.0,
 85.0,
 85.0,
 85.0,
 85.0,
 85.0,
 86.0,
 86.0,
 86.0,
 86.0,
 86.0,
 86.0,
 86.0,
 86.0,
 86.0,
 86.0,
 86.0,
 86.0,
 86.0,
 86.0,
 86.0,
 86.0,
 86.0,
 86.0,
 86.0,
 86.0,
 86.0,
 86.0,
 86.0,
 86.0,
 86.0,
 86.0,
 86.0,
 86.0,
 86.0,
 86.0,
 86.0,
 87.0,
 87.0,
 87.0,
 87.0,
 87.0,
 87.0,
 87.0,
 87.0,
 87.0,
 87.0,
 87.0,
 87.0,
 87.0,
 87.0,
 87.0,
 87.0,
 87.0,
 87.0,
 87.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 88.0,
 89.0,
 89.0,
 89.0,
 89.0,
 89.0,
 89.0,
 89.0,
 89.0,
 89.0,
 90.0,
 90.0,
 90.0,
 90.0,
 90.0,
 90.0,
 90.0,
 90.0,
 90.0,
 90.0]

##### Cycle length

In [530]:
sorted(bronze_menstrual_cycle_BMI_df['Cycle Length'])

[25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 500,
 5000]

In [531]:
# Eliminamos todos los registros con valores extremos
# Dejando un margen considerable de duracion (Ej: retrasos), eliminamos los valores >50
bronze_menstrual_cycle_cyclelength_df = bronze_menstrual_cycle_BMI_df[bronze_menstrual_cycle_BMI_df['Cycle Length'] <= 50]

In [532]:
sorted(bronze_menstrual_cycle_cyclelength_df['Cycle Length'])

[25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50]

#### Tipado

In [533]:
bronze_menstrual_cycle_cyclelength_df['Exercise Frequency'].value_counts()

Exercise Frequency
High        337
Moderate    274
Low         251
Name: count, dtype: int64

In [534]:
bronze_menstrual_cycle_cyclelength_df['Diet'].value_counts()

Diet
Vegetarian    266
Balanced      249
Low Carb      186
High Sugar    159
BALANCED        1
BL              1
Name: count, dtype: int64

In [535]:
def normalizar_dietas(valor: str)->str:
    valores_balanced = ["Balanced","BALANCED","BL"]
    if valor in valores_balanced:
        return "Balanced"
    else:
        return valor

In [536]:
bronze_menstrual_cycle_diet_df = bronze_menstrual_cycle_cyclelength_df

In [537]:
bronze_menstrual_cycle_diet_df['Diet'] = bronze_menstrual_cycle_diet_df['Diet'].apply(normalizar_dietas)

C:\Users\cadav\AppData\Local\Temp\ipykernel_11152\3485568097.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bronze_menstrual_cycle_diet_df['Diet'] = bronze_menstrual_cycle_diet_df['Diet'].apply(normalizar_dietas)

In [538]:
bronze_menstrual_cycle_diet_df['Diet'].value_counts()

Diet
Vegetarian    266
Balanced      251
Low Carb      186
High Sugar    159
Name: count, dtype: int64

In [539]:
bronze_menstrual_cycle_diet_df['Symptoms'].value_counts()

Symptoms
Bloating       195
Fatigue        172
Headache       170
Cramps         168
Mood Swings    157
Name: count, dtype: int64

In [540]:
bronze_menstrual_cycle_diet_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 862 entries, 0 to 894
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   User ID                862 non-null    float64
 1   Age                    862 non-null    float64
 2   Stress Level           862 non-null    float64
 3   Exercise Frequency     862 non-null    object
 4   Sleep Hours            862 non-null    float64
 5   Diet                   862 non-null    object
 6   Cycle Start Date       862 non-null    object
 7   Cycle Length           862 non-null    int64
 8   Period Length          862 non-null    float64
 9   Next Cycle Start Date  862 non-null    object
 10  Symptoms               862 non-null    object
 11  BMI                    862 non-null    float64
 12  _BronzeTimestamp       862 non-null    datetime64[us]
dtypes: datetime64[us](1), float64(6), int64(1), object(5)
memory usage: 94.3+ KB

In [541]:
bronze_menstrual_cycle_diet_df.head()

,User ID,Age,Stress Level,Exercise Frequency,Sleep Hours,Diet,Cycle Start Date,Cycle Length,Period Length,Next Cycle Start Date,Symptoms,BMI,_BronzeTimestamp
0,1.0,18.0,2.0,Moderate,54.0,Low Carb,13/11/2024 20:52,26,7.0,09/12/2024 20:52,Headache,29.28,2025-11-06 19:16:40.445350
1,1.0,18.0,2.0,Moderate,54.0,Low Carb,09/12/2024 20:52,32,5.0,10/01/2025 20:52,Fatigue,29.28,2025-11-06 19:16:40.445350
2,1.0,18.0,2.0,Moderate,54.0,Low Carb,10/01/2025 20:52,41,7.0,20/02/2025 20:52,Fatigue,29.28,2025-11-06 19:16:40.445350
3,1.0,18.0,2.0,Moderate,54.0,Low Carb,20/02/2025 20:52,27,3.0,19/03/2025 20:52,Fatigue,29.28,2025-11-06 19:16:40.445350
4,1.0,18.0,2.0,Moderate,54.0,Low Carb,19/03/2025 20:52,42,5.0,30/04/2025 20:52,Cramps,29.28,2025-11-06 19:16:40.445350

In [542]:
bronze_menstrual_cycle_diet_df['Cycle Start Date'] = pd.to_datetime(bronze_menstrual_cycle_diet_df['Cycle Start Date'])

C:\Users\cadav\AppData\Local\Temp\ipykernel_11152\64442064.py:1: UserWarning: Parsing dates in %d/%m/%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  bronze_menstrual_cycle_diet_df['Cycle Start Date'] = pd.to_datetime(bronze_menstrual_cycle_diet_df['Cycle Start Date'])
C:\Users\cadav\AppData\Local\Temp\ipykernel_11152\64442064.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bronze_menstrual_cycle_diet_df['Cycle Start Date'] = pd.to_datetime(bronze_menstrual_cycle_diet_df['Cycle Start Date'])

In [543]:
bronze_menstrual_cycle_diet_df.head()

,User ID,Age,Stress Level,Exercise Frequency,Sleep Hours,Diet,Cycle Start Date,Cycle Length,Period Length,Next Cycle Start Date,Symptoms,BMI,_BronzeTimestamp
0,1.0,18.0,2.0,Moderate,54.0,Low Carb,2024-11-13 20:52:00,26,7.0,09/12/2024 20:52,Headache,29.28,2025-11-06 19:16:40.445350
1,1.0,18.0,2.0,Moderate,54.0,Low Carb,2024-12-09 20:52:00,32,5.0,10/01/2025 20:52,Fatigue,29.28,2025-11-06 19:16:40.445350
2,1.0,18.0,2.0,Moderate,54.0,Low Carb,2025-01-10 20:52:00,41,7.0,20/02/2025 20:52,Fatigue,29.28,2025-11-06 19:16:40.445350
3,1.0,18.0,2.0,Moderate,54.0,Low Carb,2025-02-20 20:52:00,27,3.0,19/03/2025 20:52,Fatigue,29.28,2025-11-06 19:16:40.445350
4,1.0,18.0,2.0,Moderate,54.0,Low Carb,2025-03-19 20:52:00,42,5.0,30/04/2025 20:52,Cramps,29.28,2025-11-06 19:16:40.445350

In [544]:
sorted(bronze_menstrual_cycle_diet_df['Cycle Start Date'])

[Timestamp('2023-03-20 20:52:00'),
 Timestamp('2023-03-22 20:52:00'),
 Timestamp('2023-03-25 20:52:00'),
 Timestamp('2023-03-29 20:52:00'),
 Timestamp('2023-04-16 20:52:00'),
 Timestamp('2023-04-16 20:52:00'),
 Timestamp('2023-04-17 20:52:00'),
 Timestamp('2023-04-21 20:52:00'),
 Timestamp('2023-04-22 20:52:00'),
 Timestamp('2023-04-24 20:52:00'),
 Timestamp('2023-04-29 20:52:00'),
 Timestamp('2023-05-01 20:52:00'),
 Timestamp('2023-05-01 20:52:00'),
 Timestamp('2023-05-04 20:52:00'),
 Timestamp('2023-05-06 20:52:00'),
 Timestamp('2023-05-12 20:52:00'),
 Timestamp('2023-05-17 20:52:00'),
 Timestamp('2023-05-22 20:52:00'),
 Timestamp('2023-05-23 20:52:00'),
 Timestamp('2023-05-28 20:52:00'),
 Timestamp('2023-05-29 20:52:00'),
 Timestamp('2023-06-03 20:52:00'),
 Timestamp('2023-06-03 20:52:00'),
 Timestamp('2023-06-04 20:52:00'),
 Timestamp('2023-06-06 20:52:00'),
 Timestamp('2023-06-09 20:52:00'),
 Timestamp('2023-06-10 20:52:00'),
 Timestamp('2023-06-21 20:52:00'),
 Timestamp('2023-06-23 20:52:00'),
 Timestamp('2023-06-25 20:52:00'),
 Timestamp('2023-06-27 20:52:00'),
 Timestamp('2023-06-28 20:52:00'),
 Timestamp('2023-07-02 20:52:00'),
 Timestamp('2023-07-07 20:52:00'),
 Timestamp('2023-07-08 20:52:00'),
 Timestamp('2023-07-10 20:52:00'),
 Timestamp('2023-07-10 20:52:00'),
 Timestamp('2023-07-10 20:52:00'),
 Timestamp('2023-07-11 20:52:00'),
 Timestamp('2023-07-11 20:52:00'),
 Timestamp('2023-07-12 20:52:00'),
 Timestamp('2023-07-12 20:52:00'),
 Timestamp('2023-07-13 20:52:00'),
 Timestamp('2023-07-14 20:52:00'),
 Timestamp('2023-07-17 20:52:00'),
 Timestamp('2023-07-20 20:52:00'),
 Timestamp('2023-07-22 20:52:00'),
 Timestamp('2023-07-24 20:52:00'),
 Timestamp('2023-08-01 20:52:00'),
 Timestamp('2023-08-01 20:52:00'),
 Timestamp('2023-08-01 20:52:00'),
 Timestamp('2023-08-01 20:52:00'),
 Timestamp('2023-08-02 20:52:00'),
 Timestamp('2023-08-05 20:52:00'),
 Timestamp('2023-08-06 20:52:00'),
 Timestamp('2023-08-08 20:52:00'),
 Timestamp('2023-08-11 20:52:00'),
 Timestamp('2023-08-14 20:52:00'),
 Timestamp('2023-08-14 20:52:00'),
 Timestamp('2023-08-15 20:52:00'),
 Timestamp('2023-08-17 20:52:00'),
 Timestamp('2023-08-19 20:52:00'),
 Timestamp('2023-08-20 20:52:00'),
 Timestamp('2023-08-21 20:52:00'),
 Timestamp('2023-08-21 20:52:00'),
 Timestamp('2023-08-23 20:52:00'),
 Timestamp('2023-08-24 20:52:00'),
 Timestamp('2023-08-25 20:52:00'),
 Timestamp('2023-08-26 20:52:00'),
 Timestamp('2023-08-26 20:52:00'),
 Timestamp('2023-08-29 20:52:00'),
 Timestamp('2023-08-31 20:52:00'),
 Timestamp('2023-09-01 20:52:00'),
 Timestamp('2023-09-03 20:52:00'),
 Timestamp('2023-09-04 20:52:00'),
 Timestamp('2023-09-05 20:52:00'),
 Timestamp('2023-09-10 20:52:00'),
 Timestamp('2023-09-10 20:52:00'),
 Timestamp('2023-09-13 20:52:00'),
 Timestamp('2023-09-14 20:52:00'),
 Timestamp('2023-09-14 20:52:00'),
 Timestamp('2023-09-15 20:52:00'),
 Timestamp('2023-09-16 20:52:00'),
 Timestamp('2023-09-17 20:52:00'),
 Timestamp('2023-09-19 20:52:00'),
 Timestamp('2023-09-21 20:52:00'),
 Timestamp('2023-09-22 20:52:00'),
 Timestamp('2023-09-23 20:52:00'),
 Timestamp('2023-09-23 20:52:00'),
 Timestamp('2023-09-27 20:52:00'),
 Timestamp('2023-09-28 20:52:00'),
 Timestamp('2023-09-29 20:52:00'),
 Timestamp('2023-09-30 20:52:00'),
 Timestamp('2023-09-30 20:52:00'),
 Timestamp('2023-10-02 20:52:00'),
 Timestamp('2023-10-02 20:52:00'),
 Timestamp('2023-10-04 20:52:00'),
 Timestamp('2023-10-06 20:52:00'),
 Timestamp('2023-10-07 20:52:00'),
 Timestamp('2023-10-09 20:52:00'),
 Timestamp('2023-10-10 20:52:00'),
 Timestamp('2023-10-11 20:52:00'),
 Timestamp('2023-10-12 20:52:00'),
 Timestamp('2023-10-15 20:52:00'),
 Timestamp('2023-10-18 20:52:00'),
 Timestamp('2023-10-18 20:52:00'),
 Timestamp('2023-10-19 20:52:00'),
 Timestamp('2023-10-19 20:52:00'),
 Timestamp('2023-10-20 20:52:00'),
 Timestamp('2023-10-20 20:52:00'),
 Timestamp('2023-10-20 20:52:00'),
 Timestamp('2023-10-21 20:52:00'),
 Timestamp('2023-10-23 20:52:00'),
 Timestamp('2023-10-24 20:52:00'),
 Timestamp('2023-10-26 20:52:00'),
 Timestamp('2023-10-27 20:52:00'),
 Timestamp('2023-10-27 20:52:00'),
 Timestamp('2023-10-28 20:52:00'),
 Timestamp('2023-10-29 20:52:00'),
 Timestamp('2023-10-29 20:52:00'),
 Timestamp('2023-10-31 20:52:00'),
 Timestamp('2023-11-03 20:52:00'),
 Timestamp('2023-11-03 20:52:00'),
 Timestamp('2023-11-08 20:52:00'),
 Timestamp('2023-11-10 20:52:00'),
 Timestamp('2023-11-10 20:52:00'),
 Timestamp('2023-11-10 20:52:00'),
 Timestamp('2023-11-10 20:52:00'),
 Timestamp('2023-11-12 20:52:00'),
 Timestamp('2023-11-12 20:52:00'),
 Timestamp('2023-11-13 20:52:00'),
 Timestamp('2023-11-13 20:52:00'),
 Timestamp('2023-11-14 20:52:00'),
 Timestamp('2023-11-15 20:52:00'),
 Timestamp('2023-11-17 20:52:00'),
 Timestamp('2023-11-17 20:52:00'),
 Timestamp('2023-11-19 20:52:00'),
 Timestamp('2023-11-22 20:52:00'),
 Timestamp('2023-11-23 20:52:00'),
 Timestamp('2023-11-23 20:52:00'),
 Timestamp('2023-11-24 20:52:00'),
 Timestamp('2023-11-25 20:52:00'),
 Timestamp('2023-11-25 20:52:00'),
 Timestamp('2023-11-25 20:52:00'),
 Timestamp('2023-11-26 20:52:00'),
 Timestamp('2023-11-26 20:52:00'),
 Timestamp('2023-11-28 20:52:00'),
 Timestamp('2023-11-30 20:52:00'),
 Timestamp('2023-12-07 20:52:00'),
 Timestamp('2023-12-07 20:52:00'),
 Timestamp('2023-12-07 20:52:00'),
 Timestamp('2023-12-07 20:52:00'),
 Timestamp('2023-12-08 20:52:00'),
 Timestamp('2023-12-08 20:52:00'),
 Timestamp('2023-12-09 20:52:00'),
 Timestamp('2023-12-10 20:52:00'),
 Timestamp('2023-12-11 20:52:00'),
 Timestamp('2023-12-11 20:52:00'),
 Timestamp('2023-12-12 20:52:00'),
 Timestamp('2023-12-16 20:52:00'),
 Timestamp('2023-12-19 20:52:00'),
 Timestamp('2023-12-19 20:52:00'),
 Timestamp('2023-12-19 20:52:00'),
 Timestamp('2023-12-20 20:52:00'),
 Timestamp('2023-12-21 20:52:00'),
 Timestamp('2023-12-21 20:52:00'),
 Timestamp('2023-12-22 20:52:00'),
 Timestamp('2023-12-22 20:52:00'),
 Timestamp('2023-12-23 20:52:00'),
 Timestamp('2023-12-23 20:52:00'),
 Timestamp('2023-12-23 20:52:00'),
 Timestamp('2023-12-24 20:52:00'),
 Timestamp('2023-12-24 20:52:00'),
 Timestamp('2023-12-24 20:52:00'),
 Timestamp('2023-12-24 20:52:00'),
 Timestamp('2023-12-26 20:52:00'),
 Timestamp('2023-12-29 20:52:00'),
 Timestamp('2023-12-29 20:52:00'),
 Timestamp('2024-01-01 20:52:00'),
 Timestamp('2024-01-01 20:52:00'),
 Timestamp('2024-01-02 20:52:00'),
 Timestamp('2024-01-04 20:52:00'),
 Timestamp('2024-01-05 20:52:00'),
 Timestamp('2024-01-07 20:52:00'),
 Timestamp('2024-01-08 20:52:00'),
 Timestamp('2024-01-09 20:52:00'),
 Timestamp('2024-01-11 20:52:00'),
 Timestamp('2024-01-11 20:52:00'),
 Timestamp('2024-01-15 20:52:00'),
 Timestamp('2024-01-15 20:52:00'),
 Timestamp('2024-01-17 20:52:00'),
 Timestamp('2024-01-18 20:52:00'),
 Timestamp('2024-01-18 20:52:00'),
 Timestamp('2024-01-21 20:52:00'),
 Timestamp('2024-01-22 20:52:00'),
 Timestamp('2024-01-22 20:52:00'),
 Timestamp('2024-01-23 20:52:00'),
 Timestamp('2024-01-23 20:52:00'),
 Timestamp('2024-01-24 20:52:00'),
 Timestamp('2024-01-25 20:52:00'),
 Timestamp('2024-01-27 20:52:00'),
 Timestamp('2024-01-27 20:52:00'),
 Timestamp('2024-01-27 20:52:00'),
 Timestamp('2024-01-27 20:52:00'),
 Timestamp('2024-01-28 20:52:00'),
 Timestamp('2024-01-28 20:52:00'),
 Timestamp('2024-01-28 20:52:00'),
 Timestamp('2024-01-29 20:52:00'),
 Timestamp('2024-02-05 20:52:00'),
 Timestamp('2024-02-05 20:52:00'),
 Timestamp('2024-02-06 20:52:00'),
 Timestamp('2024-02-07 20:52:00'),
 Timestamp('2024-02-07 20:52:00'),
 Timestamp('2024-02-08 20:52:00'),
 Timestamp('2024-02-09 20:52:00'),
 Timestamp('2024-02-09 20:52:00'),
 Timestamp('2024-02-11 20:52:00'),
 Timestamp('2024-02-11 20:52:00'),
 Timestamp('2024-02-12 20:52:00'),
 Timestamp('2024-02-12 20:52:00'),
 Timestamp('2024-02-13 20:52:00'),
 Timestamp('2024-02-17 20:52:00'),
 Timestamp('2024-02-17 20:52:00'),
 Timestamp('2024-02-18 20:52:00'),
 Timestamp('2024-02-20 20:52:00'),
 Timestamp('2024-02-21 20:52:00'),
 Timestamp('2024-02-21 20:52:00'),
 Timestamp('2024-02-22 20:52:00'),
 Timestamp('2024-02-22 20:52:00'),
 Timestamp('2024-02-23 20:52:00'),
 Timestamp('2024-02-25 20:52:00'),
 Timestamp('2024-02-26 20:52:00'),
 Timestamp('2024-02-26 20:52:00'),
 Timestamp('2024-02-27 20:52:00'),
 Timestamp('2024-02-28 20:52:00'),
 Timestamp('2024-02-28 20:52:00'),
 Timestamp('2024-02-29 20:52:00'),
 Timestamp('2024-03-02 20:52:00'),
 Timestamp('2024-03-02 20:52:00'),
 Timestamp('2024-03-03 20:52:00'),
 Timestamp('2024-03-05 20:52:00'),
 Timestamp('2024-03-05 20:52:00'),
 Timestamp('2024-03-07 20:52:00'),
 Timestamp('2024-03-09 20:52:00'),
 Timestamp('2024-03-10 20:52:00'),
 Timestamp('2024-03-10 20:52:00'),
 Timestamp('2024-03-11 20:52:00'),
 Timestamp('2024-03-11 20:52:00'),
 Timestamp('2024-03-11 20:52:00'),
 Timestamp('2024-03-12 20:52:00'),
 Timestamp('2024-03-13 20:52:00'),
 Timestamp('2024-03-14 20:52:00'),
 Timestamp('2024-03-14 20:52:00'),
 Timestamp('2024-03-15 20:52:00'),
 Timestamp('2024-03-16 20:52:00'),
 Timestamp('2024-03-16 20:52:00'),
 Timestamp('2024-03-17 20:52:00'),
 Timestamp('2024-03-18 20:52:00'),
 Timestamp('2024-03-21 20:52:00'),
 Timestamp('2024-03-21 20:52:00'),
 Timestamp('2024-03-21 20:52:00'),
 Timestamp('2024-03-21 20:52:00'),
 Timestamp('2024-03-22 20:52:00'),
 Timestamp('2024-03-23 20:52:00'),
 Timestamp('2024-03-25 20:52:00'),
 Timestamp('2024-03-25 20:52:00'),
 Timestamp('2024-03-26 20:52:00'),
 Timestamp('2024-03-27 20:52:00'),
 Timestamp('2024-03-27 20:52:00'),
 Timestamp('2024-03-29 20:52:00'),
 Timestamp('2024-03-29 20:52:00'),
 Timestamp('2024-03-30 20:52:00'),
 Timestamp('2024-03-30 20:52:00'),
 Timestamp('2024-04-02 20:52:00'),
 Timestamp('2024-04-02 20:52:00'),
 Timestamp('2024-04-07 20:52:00'),
 Timestamp('2024-04-07 20:52:00'),
 Timestamp('2024-04-08 20:52:00'),
 Timestamp('2024-04-09 20:52:00'),
 Timestamp('2024-04-09 20:52:00'),
 Timestamp('2024-04-09 20:52:00'),
 Timestamp('2024-04-10 20:52:00'),
 Timestamp('2024-04-14 20:52:00'),
 Timestamp('2024-04-14 20:52:00'),
 Timestamp('2024-04-15 20:52:00'),
 Timestamp('2024-04-15 20:52:00'),
 Timestamp('2024-04-16 20:52:00'),
 Timestamp('2024-04-16 20:52:00'),
 Timestamp('2024-04-17 20:52:00'),
 Timestamp('2024-04-17 20:52:00'),
 Timestamp('2024-04-19 20:52:00'),
 Timestamp('2024-04-19 20:52:00'),
 Timestamp('2024-04-20 20:52:00'),
 Timestamp('2024-04-20 20:52:00'),
 Timestamp('2024-04-20 20:52:00'),
 Timestamp('2024-04-21 20:52:00'),
 Timestamp('2024-04-22 20:52:00'),
 Timestamp('2024-04-22 20:52:00'),
 Timestamp('2024-04-22 20:52:00'),
 Timestamp('2024-04-24 20:52:00'),
 Timestamp('2024-04-25 20:52:00'),
 Timestamp('2024-04-26 20:52:00'),
 Timestamp('2024-04-28 20:52:00'),
 Timestamp('2024-04-28 20:52:00'),
 Timestamp('2024-04-29 20:52:00'),
 Timestamp('2024-04-29 20:52:00'),
 Timestamp('2024-04-30 20:52:00'),
 Timestamp('2024-04-30 20:52:00'),
 Timestamp('2024-05-02 20:52:00'),
 Timestamp('2024-05-03 20:52:00'),
 Timestamp('2024-05-04 20:52:00'),
 Timestamp('2024-05-04 20:52:00'),
 Timestamp('2024-05-05 20:52:00'),
 Timestamp('2024-05-06 20:52:00'),
 Timestamp('2024-05-07 20:52:00'),
 Timestamp('2024-05-10 20:52:00'),
 Timestamp('2024-05-10 20:52:00'),
 Timestamp('2024-05-11 20:52:00'),
 Timestamp('2024-05-13 20:52:00'),
 Timestamp('2024-05-14 20:52:00'),
 Timestamp('2024-05-15 20:52:00'),
 Timestamp('2024-05-16 20:52:00'),
 Timestamp('2024-05-17 20:52:00'),
 Timestamp('2024-05-18 20:52:00'),
 Timestamp('2024-05-18 20:52:00'),
 Timestamp('2024-05-20 20:52:00'),
 Timestamp('2024-05-20 20:52:00'),
 Timestamp('2024-05-21 20:52:00'),
 Timestamp('2024-05-21 20:52:00'),
 Timestamp('2024-05-21 20:52:00'),
 Timestamp('2024-05-21 20:52:00'),
 Timestamp('2024-05-21 20:52:00'),
 Timestamp('2024-05-25 20:52:00'),
 Timestamp('2024-05-25 20:52:00'),
 Timestamp('2024-05-25 20:52:00'),
 Timestamp('2024-05-28 20:52:00'),
 Timestamp('2024-05-28 20:52:00'),
 Timestamp('2024-05-30 20:52:00'),
 Timestamp('2024-05-30 20:52:00'),
 Timestamp('2024-05-31 20:52:00'),
 Timestamp('2024-06-01 20:52:00'),
 Timestamp('2024-06-01 20:52:00'),
 Timestamp('2024-06-01 20:52:00'),
 Timestamp('2024-06-01 20:52:00'),
 Timestamp('2024-06-03 20:52:00'),
 Timestamp('2024-06-03 20:52:00'),
 Timestamp('2024-06-05 20:52:00'),
 Timestamp('2024-06-08 20:52:00'),
 Timestamp('2024-06-09 20:52:00'),
 Timestamp('2024-06-09 20:52:00'),
 Timestamp('2024-06-09 20:52:00'),
 Timestamp('2024-06-10 20:52:00'),
 Timestamp('2024-06-10 20:52:00'),
 Timestamp('2024-06-10 20:52:00'),
 Timestamp('2024-06-11 20:52:00'),
 Timestamp('2024-06-12 20:52:00'),
 Timestamp('2024-06-13 20:52:00'),
 Timestamp('2024-06-14 20:52:00'),
 Timestamp('2024-06-16 20:52:00'),
 Timestamp('2024-06-16 20:52:00'),
 Timestamp('2024-06-17 20:52:00'),
 Timestamp('2024-06-17 20:52:00'),
 Timestamp('2024-06-17 20:52:00'),
 Timestamp('2024-06-18 20:52:00'),
 Timestamp('2024-06-18 20:52:00'),
 Timestamp('2024-06-20 20:52:00'),
 Timestamp('2024-06-21 20:52:00'),
 Timestamp('2024-06-22 20:52:00'),
 Timestamp('2024-06-22 20:52:00'),
 Timestamp('2024-06-23 20:52:00'),
 Timestamp('2024-06-23 20:52:00'),
 Timestamp('2024-06-25 20:52:00'),
 Timestamp('2024-06-28 20:52:00'),
 Timestamp('2024-06-29 20:52:00'),
 Timestamp('2024-06-30 20:52:00'),
 Timestamp('2024-06-30 20:52:00'),
 Timestamp('2024-07-01 20:52:00'),
 Timestamp('2024-07-02 20:52:00'),
 Timestamp('2024-07-04 20:52:00'),
 Timestamp('2024-07-04 20:52:00'),
 Timestamp('2024-07-05 20:52:00'),
 Timestamp('2024-07-05 20:52:00'),
 Timestamp('2024-07-08 20:52:00'),
 Timestamp('2024-07-08 20:52:00'),
 Timestamp('2024-07-09 20:52:00'),
 Timestamp('2024-07-09 20:52:00'),
 Timestamp('2024-07-10 20:52:00'),
 Timestamp('2024-07-10 20:52:00'),
 Timestamp('2024-07-11 20:52:00'),
 Timestamp('2024-07-11 20:52:00'),
 Timestamp('2024-07-12 20:52:00'),
 Timestamp('2024-07-12 20:52:00'),
 Timestamp('2024-07-13 20:52:00'),
 Timestamp('2024-07-16 20:52:00'),
 Timestamp('2024-07-17 20:52:00'),
 Timestamp('2024-07-19 20:52:00'),
 Timestamp('2024-07-20 20:52:00'),
 Timestamp('2024-07-20 20:52:00'),
 Timestamp('2024-07-20 20:52:00'),
 Timestamp('2024-07-20 20:52:00'),
 Timestamp('2024-07-21 20:52:00'),
 Timestamp('2024-07-22 20:52:00'),
 Timestamp('2024-07-22 20:52:00'),
 Timestamp('2024-07-24 20:52:00'),
 Timestamp('2024-07-26 20:52:00'),
 Timestamp('2024-07-26 20:52:00'),
 Timestamp('2024-07-27 20:52:00'),
 Timestamp('2024-07-29 20:52:00'),
 Timestamp('2024-07-29 20:52:00'),
 Timestamp('2024-07-29 20:52:00'),
 Timestamp('2024-07-29 20:52:00'),
 Timestamp('2024-07-30 20:52:00'),
 Timestamp('2024-08-01 20:52:00'),
 Timestamp('2024-08-02 20:52:00'),
 Timestamp('2024-08-02 20:52:00'),
 Timestamp('2024-08-03 20:52:00'),
 Timestamp('2024-08-03 20:52:00'),
 Timestamp('2024-08-03 20:52:00'),
 Timestamp('2024-08-05 20:52:00'),
 Timestamp('2024-08-05 20:52:00'),
 Timestamp('2024-08-12 20:52:00'),
 Timestamp('2024-08-12 20:52:00'),
 Timestamp('2024-08-13 20:52:00'),
 Timestamp('2024-08-13 20:52:00'),
 Timestamp('2024-08-14 20:52:00'),
 Timestamp('2024-08-15 20:52:00'),
 Timestamp('2024-08-18 20:52:00'),
 Timestamp('2024-08-19 20:52:00'),
 Timestamp('2024-08-19 20:52:00'),
 Timestamp('2024-08-21 20:52:00'),
 Timestamp('2024-08-22 20:52:00'),
 Timestamp('2024-08-22 20:52:00'),
 Timestamp('2024-08-23 20:52:00'),
 Timestamp('2024-08-23 20:52:00'),
 Timestamp('2024-08-25 20:52:00'),
 Timestamp('2024-08-26 20:52:00'),
 Timestamp('2024-08-26 20:52:00'),
 Timestamp('2024-08-26 20:52:00'),
 Timestamp('2024-08-27 20:52:00'),
 Timestamp('2024-08-28 20:52:00'),
 Timestamp('2024-08-28 20:52:00'),
 Timestamp('2024-08-28 20:52:00'),
 Timestamp('2024-08-29 20:52:00'),
 Timestamp('2024-08-31 20:52:00'),
 Timestamp('2024-09-01 20:52:00'),
 Timestamp('2024-09-01 20:52:00'),
 Timestamp('2024-09-02 20:52:00'),
 Timestamp('2024-09-02 20:52:00'),
 Timestamp('2024-09-07 20:52:00'),
 Timestamp('2024-09-07 20:52:00'),
 Timestamp('2024-09-09 20:52:00'),
 Timestamp('2024-09-10 20:52:00'),
 Timestamp('2024-09-11 20:52:00'),
 Timestamp('2024-09-12 20:52:00'),
 Timestamp('2024-09-13 20:52:00'),
 Timestamp('2024-09-18 20:52:00'),
 Timestamp('2024-09-18 20:52:00'),
 Timestamp('2024-09-18 20:52:00'),
 Timestamp('2024-09-19 20:52:00'),
 Timestamp('2024-09-19 20:52:00'),
 Timestamp('2024-09-20 20:52:00'),
 Timestamp('2024-09-21 20:52:00'),
 Timestamp('2024-09-22 20:52:00'),
 Timestamp('2024-09-22 20:52:00'),
 Timestamp('2024-09-23 20:52:00'),
 Timestamp('2024-09-23 20:52:00'),
 Timestamp('2024-09-24 20:52:00'),
 Timestamp('2024-09-25 20:52:00'),
 Timestamp('2024-09-26 20:52:00'),
 Timestamp('2024-09-28 20:52:00'),
 Timestamp('2024-09-28 20:52:00'),
 Timestamp('2024-09-28 20:52:00'),
 Timestamp('2024-09-28 20:52:00'),
 Timestamp('2024-09-28 20:52:00'),
 Timestamp('2024-09-29 20:52:00'),
 Timestamp('2024-09-29 20:52:00'),
 Timestamp('2024-09-30 20:52:00'),
 Timestamp('2024-10-01 20:52:00'),
 Timestamp('2024-10-03 20:52:00'),
 Timestamp('2024-10-03 20:52:00'),
 Timestamp('2024-10-04 20:52:00'),
 Timestamp('2024-10-06 20:52:00'),
 Timestamp('2024-10-07 20:52:00'),
 Timestamp('2024-10-08 20:52:00'),
 Timestamp('2024-10-09 20:52:00'),
 Timestamp('2024-10-11 20:52:00'),
 Timestamp('2024-10-11 20:52:00'),
 Timestamp('2024-10-13 20:52:00'),
 Timestamp('2024-10-14 20:52:00'),
 Timestamp('2024-10-17 20:52:00'),
 Timestamp('2024-10-19 20:52:00'),
 Timestamp('2024-10-20 20:52:00'),
 Timestamp('2024-10-20 20:52:00'),
 Timestamp('2024-10-21 20:52:00'),
 Timestamp('2024-10-25 20:52:00'),
 Timestamp('2024-10-25 20:52:00'),
 Timestamp('2024-10-25 20:52:00'),
 Timestamp('2024-10-25 20:52:00'),
 Timestamp('2024-10-27 20:52:00'),
 Timestamp('2024-10-29 20:52:00'),
 Timestamp('2024-10-29 20:52:00'),
 Timestamp('2024-10-29 20:52:00'),
 Timestamp('2024-10-30 20:52:00'),
 Timestamp('2024-10-30 20:52:00'),
 Timestamp('2024-10-30 20:52:00'),
 Timestamp('2024-11-02 20:52:00'),
 Timestamp('2024-11-03 20:52:00'),
 Timestamp('2024-11-04 20:52:00'),
 Timestamp('2024-11-04 20:52:00'),
 Timestamp('2024-11-04 20:52:00'),
 Timestamp('2024-11-06 20:52:00'),
 Timestamp('2024-11-07 20:52:00'),
 Timestamp('2024-11-07 20:52:00'),
 Timestamp('2024-11-08 20:52:00'),
 Timestamp('2024-11-09 20:52:00'),
 Timestamp('2024-11-10 20:52:00'),
 Timestamp('2024-11-13 20:52:00'),
 Timestamp('2024-11-13 20:52:00'),
 Timestamp('2024-11-13 20:52:00'),
 Timestamp('2024-11-14 20:52:00'),
 Timestamp('2024-11-16 20:52:00'),
 Timestamp('2024-11-16 20:52:00'),
 Timestamp('2024-11-16 20:52:00'),
 Timestamp('2024-11-16 20:52:00'),
 Timestamp('2024-11-17 20:52:00'),
 Timestamp('2024-11-18 20:52:00'),
 Timestamp('2024-11-18 20:52:00'),
 Timestamp('2024-11-19 20:52:00'),
 Timestamp('2024-11-20 20:52:00'),
 Timestamp('2024-11-21 20:52:00'),
 Timestamp('2024-11-21 20:52:00'),
 Timestamp('2024-11-23 20:52:00'),
 Timestamp('2024-11-23 20:52:00'),
 Timestamp('2024-11-24 20:52:00'),
 Timestamp('2024-11-25 20:52:00'),
 Timestamp('2024-11-26 20:52:00'),
 Timestamp('2024-11-28 20:52:00'),
 Timestamp('2024-11-29 20:52:00'),
 Timestamp('2024-11-29 20:52:00'),
 Timestamp('2024-12-02 20:52:00'),
 Timestamp('2024-12-02 20:52:00'),
 Timestamp('2024-12-04 20:52:00'),
 Timestamp('2024-12-04 20:52:00'),
 Timestamp('2024-12-05 20:52:00'),
 Timestamp('2024-12-07 20:52:00'),
 Timestamp('2024-12-08 20:52:00'),
 Timestamp('2024-12-09 20:52:00'),
 Timestamp('2024-12-09 20:52:00'),
 Timestamp('2024-12-09 20:52:00'),
 Timestamp('2024-12-10 20:52:00'),
 Timestamp('2024-12-10 20:52:00'),
 Timestamp('2024-12-11 20:52:00'),
 Timestamp('2024-12-12 20:52:00'),
 Timestamp('2024-12-14 20:52:00'),
 Timestamp('2024-12-15 20:52:00'),
 Timestamp('2024-12-16 20:52:00'),
 Timestamp('2024-12-17 20:52:00'),
 Timestamp('2024-12-18 20:52:00'),
 Timestamp('2024-12-18 20:52:00'),
 Timestamp('2024-12-19 20:52:00'),
 Timestamp('2024-12-19 20:52:00'),
 Timestamp('2024-12-20 20:52:00'),
 Timestamp('2024-12-21 20:52:00'),
 Timestamp('2024-12-22 20:52:00'),
 Timestamp('2024-12-22 20:52:00'),
 Timestamp('2024-12-23 20:52:00'),
 Timestamp('2024-12-23 20:52:00'),
 Timestamp('2024-12-25 20:52:00'),
 Timestamp('2024-12-25 20:52:00'),
 Timestamp('2024-12-26 20:52:00'),
 Timestamp('2024-12-26 20:52:00'),

In [556]:
bronze_menstrual_cycle_startdate_df = bronze_menstrual_cycle_diet_df[
    bronze_menstrual_cycle_diet_df['Cycle Start Date'] != '2077-08-10 20:52:00']

In [557]:
sorted(bronze_menstrual_cycle_startdate_df['Cycle Start Date'])

[Timestamp('2023-03-20 20:52:00'),
 Timestamp('2023-03-22 20:52:00'),
 Timestamp('2023-03-25 20:52:00'),
 Timestamp('2023-03-29 20:52:00'),
 Timestamp('2023-04-16 20:52:00'),
 Timestamp('2023-04-16 20:52:00'),
 Timestamp('2023-04-17 20:52:00'),
 Timestamp('2023-04-21 20:52:00'),
 Timestamp('2023-04-22 20:52:00'),
 Timestamp('2023-04-24 20:52:00'),
 Timestamp('2023-04-29 20:52:00'),
 Timestamp('2023-05-01 20:52:00'),
 Timestamp('2023-05-01 20:52:00'),
 Timestamp('2023-05-04 20:52:00'),
 Timestamp('2023-05-06 20:52:00'),
 Timestamp('2023-05-12 20:52:00'),
 Timestamp('2023-05-17 20:52:00'),
 Timestamp('2023-05-22 20:52:00'),
 Timestamp('2023-05-23 20:52:00'),
 Timestamp('2023-05-28 20:52:00'),
 Timestamp('2023-05-29 20:52:00'),
 Timestamp('2023-06-03 20:52:00'),
 Timestamp('2023-06-03 20:52:00'),
 Timestamp('2023-06-04 20:52:00'),
 Timestamp('2023-06-06 20:52:00'),
 Timestamp('2023-06-09 20:52:00'),
 Timestamp('2023-06-10 20:52:00'),
 Timestamp('2023-06-21 20:52:00'),
 Timestamp('2023-06-23 20:52:00'),
 Timestamp('2023-06-25 20:52:00'),
 Timestamp('2023-06-27 20:52:00'),
 Timestamp('2023-06-28 20:52:00'),
 Timestamp('2023-07-02 20:52:00'),
 Timestamp('2023-07-07 20:52:00'),
 Timestamp('2023-07-08 20:52:00'),
 Timestamp('2023-07-10 20:52:00'),
 Timestamp('2023-07-10 20:52:00'),
 Timestamp('2023-07-10 20:52:00'),
 Timestamp('2023-07-11 20:52:00'),
 Timestamp('2023-07-11 20:52:00'),
 Timestamp('2023-07-12 20:52:00'),
 Timestamp('2023-07-12 20:52:00'),
 Timestamp('2023-07-13 20:52:00'),
 Timestamp('2023-07-14 20:52:00'),
 Timestamp('2023-07-17 20:52:00'),
 Timestamp('2023-07-20 20:52:00'),
 Timestamp('2023-07-22 20:52:00'),
 Timestamp('2023-07-24 20:52:00'),
 Timestamp('2023-08-01 20:52:00'),
 Timestamp('2023-08-01 20:52:00'),
 Timestamp('2023-08-01 20:52:00'),
 Timestamp('2023-08-01 20:52:00'),
 Timestamp('2023-08-02 20:52:00'),
 Timestamp('2023-08-05 20:52:00'),
 Timestamp('2023-08-06 20:52:00'),
 Timestamp('2023-08-08 20:52:00'),
 Timestamp('2023-08-11 20:52:00'),
 Timestamp('2023-08-14 20:52:00'),
 Timestamp('2023-08-14 20:52:00'),
 Timestamp('2023-08-15 20:52:00'),
 Timestamp('2023-08-17 20:52:00'),
 Timestamp('2023-08-19 20:52:00'),
 Timestamp('2023-08-20 20:52:00'),
 Timestamp('2023-08-21 20:52:00'),
 Timestamp('2023-08-21 20:52:00'),
 Timestamp('2023-08-23 20:52:00'),
 Timestamp('2023-08-24 20:52:00'),
 Timestamp('2023-08-25 20:52:00'),
 Timestamp('2023-08-26 20:52:00'),
 Timestamp('2023-08-26 20:52:00'),
 Timestamp('2023-08-29 20:52:00'),
 Timestamp('2023-08-31 20:52:00'),
 Timestamp('2023-09-01 20:52:00'),
 Timestamp('2023-09-03 20:52:00'),
 Timestamp('2023-09-04 20:52:00'),
 Timestamp('2023-09-05 20:52:00'),
 Timestamp('2023-09-10 20:52:00'),
 Timestamp('2023-09-10 20:52:00'),
 Timestamp('2023-09-13 20:52:00'),
 Timestamp('2023-09-14 20:52:00'),
 Timestamp('2023-09-14 20:52:00'),
 Timestamp('2023-09-15 20:52:00'),
 Timestamp('2023-09-16 20:52:00'),
 Timestamp('2023-09-17 20:52:00'),
 Timestamp('2023-09-19 20:52:00'),
 Timestamp('2023-09-21 20:52:00'),
 Timestamp('2023-09-22 20:52:00'),
 Timestamp('2023-09-23 20:52:00'),
 Timestamp('2023-09-23 20:52:00'),
 Timestamp('2023-09-27 20:52:00'),
 Timestamp('2023-09-28 20:52:00'),
 Timestamp('2023-09-29 20:52:00'),
 Timestamp('2023-09-30 20:52:00'),
 Timestamp('2023-09-30 20:52:00'),
 Timestamp('2023-10-02 20:52:00'),
 Timestamp('2023-10-02 20:52:00'),
 Timestamp('2023-10-04 20:52:00'),
 Timestamp('2023-10-06 20:52:00'),
 Timestamp('2023-10-07 20:52:00'),
 Timestamp('2023-10-09 20:52:00'),
 Timestamp('2023-10-10 20:52:00'),
 Timestamp('2023-10-11 20:52:00'),
 Timestamp('2023-10-12 20:52:00'),
 Timestamp('2023-10-15 20:52:00'),
 Timestamp('2023-10-18 20:52:00'),
 Timestamp('2023-10-18 20:52:00'),
 Timestamp('2023-10-19 20:52:00'),
 Timestamp('2023-10-19 20:52:00'),
 Timestamp('2023-10-20 20:52:00'),
 Timestamp('2023-10-20 20:52:00'),
 Timestamp('2023-10-20 20:52:00'),
 Timestamp('2023-10-21 20:52:00'),
 Timestamp('2023-10-23 20:52:00'),
 Timestamp('2023-10-24 20:52:00'),
 Timestamp('2023-10-26 20:52:00'),
 Timestamp('2023-10-27 20:52:00'),
 Timestamp('2023-10-27 20:52:00'),
 Timestamp('2023-10-28 20:52:00'),
 Timestamp('2023-10-29 20:52:00'),
 Timestamp('2023-10-29 20:52:00'),
 Timestamp('2023-10-31 20:52:00'),
 Timestamp('2023-11-03 20:52:00'),
 Timestamp('2023-11-03 20:52:00'),
 Timestamp('2023-11-08 20:52:00'),
 Timestamp('2023-11-10 20:52:00'),
 Timestamp('2023-11-10 20:52:00'),
 Timestamp('2023-11-10 20:52:00'),
 Timestamp('2023-11-10 20:52:00'),
 Timestamp('2023-11-12 20:52:00'),
 Timestamp('2023-11-12 20:52:00'),
 Timestamp('2023-11-13 20:52:00'),
 Timestamp('2023-11-13 20:52:00'),
 Timestamp('2023-11-14 20:52:00'),
 Timestamp('2023-11-15 20:52:00'),
 Timestamp('2023-11-17 20:52:00'),
 Timestamp('2023-11-17 20:52:00'),
 Timestamp('2023-11-19 20:52:00'),
 Timestamp('2023-11-22 20:52:00'),
 Timestamp('2023-11-23 20:52:00'),
 Timestamp('2023-11-23 20:52:00'),
 Timestamp('2023-11-24 20:52:00'),
 Timestamp('2023-11-25 20:52:00'),
 Timestamp('2023-11-25 20:52:00'),
 Timestamp('2023-11-25 20:52:00'),
 Timestamp('2023-11-26 20:52:00'),
 Timestamp('2023-11-26 20:52:00'),
 Timestamp('2023-11-28 20:52:00'),
 Timestamp('2023-11-30 20:52:00'),
 Timestamp('2023-12-07 20:52:00'),
 Timestamp('2023-12-07 20:52:00'),
 Timestamp('2023-12-07 20:52:00'),
 Timestamp('2023-12-07 20:52:00'),
 Timestamp('2023-12-08 20:52:00'),
 Timestamp('2023-12-08 20:52:00'),
 Timestamp('2023-12-09 20:52:00'),
 Timestamp('2023-12-10 20:52:00'),
 Timestamp('2023-12-11 20:52:00'),
 Timestamp('2023-12-11 20:52:00'),
 Timestamp('2023-12-12 20:52:00'),
 Timestamp('2023-12-16 20:52:00'),
 Timestamp('2023-12-19 20:52:00'),
 Timestamp('2023-12-19 20:52:00'),
 Timestamp('2023-12-19 20:52:00'),
 Timestamp('2023-12-20 20:52:00'),
 Timestamp('2023-12-21 20:52:00'),
 Timestamp('2023-12-21 20:52:00'),
 Timestamp('2023-12-22 20:52:00'),
 Timestamp('2023-12-22 20:52:00'),
 Timestamp('2023-12-23 20:52:00'),
 Timestamp('2023-12-23 20:52:00'),
 Timestamp('2023-12-23 20:52:00'),
 Timestamp('2023-12-24 20:52:00'),
 Timestamp('2023-12-24 20:52:00'),
 Timestamp('2023-12-24 20:52:00'),
 Timestamp('2023-12-24 20:52:00'),
 Timestamp('2023-12-26 20:52:00'),
 Timestamp('2023-12-29 20:52:00'),
 Timestamp('2023-12-29 20:52:00'),
 Timestamp('2024-01-01 20:52:00'),
 Timestamp('2024-01-01 20:52:00'),
 Timestamp('2024-01-02 20:52:00'),
 Timestamp('2024-01-04 20:52:00'),
 Timestamp('2024-01-05 20:52:00'),
 Timestamp('2024-01-07 20:52:00'),
 Timestamp('2024-01-08 20:52:00'),
 Timestamp('2024-01-09 20:52:00'),
 Timestamp('2024-01-11 20:52:00'),
 Timestamp('2024-01-11 20:52:00'),
 Timestamp('2024-01-15 20:52:00'),
 Timestamp('2024-01-15 20:52:00'),
 Timestamp('2024-01-17 20:52:00'),
 Timestamp('2024-01-18 20:52:00'),
 Timestamp('2024-01-18 20:52:00'),
 Timestamp('2024-01-21 20:52:00'),
 Timestamp('2024-01-22 20:52:00'),
 Timestamp('2024-01-22 20:52:00'),
 Timestamp('2024-01-23 20:52:00'),
 Timestamp('2024-01-23 20:52:00'),
 Timestamp('2024-01-24 20:52:00'),
 Timestamp('2024-01-25 20:52:00'),
 Timestamp('2024-01-27 20:52:00'),
 Timestamp('2024-01-27 20:52:00'),
 Timestamp('2024-01-27 20:52:00'),
 Timestamp('2024-01-27 20:52:00'),
 Timestamp('2024-01-28 20:52:00'),
 Timestamp('2024-01-28 20:52:00'),
 Timestamp('2024-01-28 20:52:00'),
 Timestamp('2024-01-29 20:52:00'),
 Timestamp('2024-02-05 20:52:00'),
 Timestamp('2024-02-05 20:52:00'),
 Timestamp('2024-02-06 20:52:00'),
 Timestamp('2024-02-07 20:52:00'),
 Timestamp('2024-02-07 20:52:00'),
 Timestamp('2024-02-08 20:52:00'),
 Timestamp('2024-02-09 20:52:00'),
 Timestamp('2024-02-09 20:52:00'),
 Timestamp('2024-02-11 20:52:00'),
 Timestamp('2024-02-11 20:52:00'),
 Timestamp('2024-02-12 20:52:00'),
 Timestamp('2024-02-12 20:52:00'),
 Timestamp('2024-02-13 20:52:00'),
 Timestamp('2024-02-17 20:52:00'),
 Timestamp('2024-02-17 20:52:00'),
 Timestamp('2024-02-18 20:52:00'),
 Timestamp('2024-02-20 20:52:00'),
 Timestamp('2024-02-21 20:52:00'),
 Timestamp('2024-02-21 20:52:00'),
 Timestamp('2024-02-22 20:52:00'),
 Timestamp('2024-02-22 20:52:00'),
 Timestamp('2024-02-23 20:52:00'),
 Timestamp('2024-02-25 20:52:00'),
 Timestamp('2024-02-26 20:52:00'),
 Timestamp('2024-02-26 20:52:00'),
 Timestamp('2024-02-27 20:52:00'),
 Timestamp('2024-02-28 20:52:00'),
 Timestamp('2024-02-28 20:52:00'),
 Timestamp('2024-02-29 20:52:00'),
 Timestamp('2024-03-02 20:52:00'),
 Timestamp('2024-03-02 20:52:00'),
 Timestamp('2024-03-03 20:52:00'),
 Timestamp('2024-03-05 20:52:00'),
 Timestamp('2024-03-05 20:52:00'),
 Timestamp('2024-03-07 20:52:00'),
 Timestamp('2024-03-09 20:52:00'),
 Timestamp('2024-03-10 20:52:00'),
 Timestamp('2024-03-10 20:52:00'),
 Timestamp('2024-03-11 20:52:00'),
 Timestamp('2024-03-11 20:52:00'),
 Timestamp('2024-03-11 20:52:00'),
 Timestamp('2024-03-12 20:52:00'),
 Timestamp('2024-03-13 20:52:00'),
 Timestamp('2024-03-14 20:52:00'),
 Timestamp('2024-03-14 20:52:00'),
 Timestamp('2024-03-15 20:52:00'),
 Timestamp('2024-03-16 20:52:00'),
 Timestamp('2024-03-16 20:52:00'),
 Timestamp('2024-03-17 20:52:00'),
 Timestamp('2024-03-18 20:52:00'),
 Timestamp('2024-03-21 20:52:00'),
 Timestamp('2024-03-21 20:52:00'),
 Timestamp('2024-03-21 20:52:00'),
 Timestamp('2024-03-21 20:52:00'),
 Timestamp('2024-03-22 20:52:00'),
 Timestamp('2024-03-23 20:52:00'),
 Timestamp('2024-03-25 20:52:00'),
 Timestamp('2024-03-25 20:52:00'),
 Timestamp('2024-03-26 20:52:00'),
 Timestamp('2024-03-27 20:52:00'),
 Timestamp('2024-03-27 20:52:00'),
 Timestamp('2024-03-29 20:52:00'),
 Timestamp('2024-03-29 20:52:00'),
 Timestamp('2024-03-30 20:52:00'),
 Timestamp('2024-03-30 20:52:00'),
 Timestamp('2024-04-02 20:52:00'),
 Timestamp('2024-04-02 20:52:00'),
 Timestamp('2024-04-07 20:52:00'),
 Timestamp('2024-04-07 20:52:00'),
 Timestamp('2024-04-08 20:52:00'),
 Timestamp('2024-04-09 20:52:00'),
 Timestamp('2024-04-09 20:52:00'),
 Timestamp('2024-04-09 20:52:00'),
 Timestamp('2024-04-10 20:52:00'),
 Timestamp('2024-04-14 20:52:00'),
 Timestamp('2024-04-14 20:52:00'),
 Timestamp('2024-04-15 20:52:00'),
 Timestamp('2024-04-15 20:52:00'),
 Timestamp('2024-04-16 20:52:00'),
 Timestamp('2024-04-16 20:52:00'),
 Timestamp('2024-04-17 20:52:00'),
 Timestamp('2024-04-17 20:52:00'),
 Timestamp('2024-04-19 20:52:00'),
 Timestamp('2024-04-19 20:52:00'),
 Timestamp('2024-04-20 20:52:00'),
 Timestamp('2024-04-20 20:52:00'),
 Timestamp('2024-04-20 20:52:00'),
 Timestamp('2024-04-21 20:52:00'),
 Timestamp('2024-04-22 20:52:00'),
 Timestamp('2024-04-22 20:52:00'),
 Timestamp('2024-04-22 20:52:00'),
 Timestamp('2024-04-24 20:52:00'),
 Timestamp('2024-04-25 20:52:00'),
 Timestamp('2024-04-26 20:52:00'),
 Timestamp('2024-04-28 20:52:00'),
 Timestamp('2024-04-28 20:52:00'),
 Timestamp('2024-04-29 20:52:00'),
 Timestamp('2024-04-29 20:52:00'),
 Timestamp('2024-04-30 20:52:00'),
 Timestamp('2024-04-30 20:52:00'),
 Timestamp('2024-05-02 20:52:00'),
 Timestamp('2024-05-03 20:52:00'),
 Timestamp('2024-05-04 20:52:00'),
 Timestamp('2024-05-04 20:52:00'),
 Timestamp('2024-05-05 20:52:00'),
 Timestamp('2024-05-06 20:52:00'),
 Timestamp('2024-05-07 20:52:00'),
 Timestamp('2024-05-10 20:52:00'),
 Timestamp('2024-05-10 20:52:00'),
 Timestamp('2024-05-11 20:52:00'),
 Timestamp('2024-05-13 20:52:00'),
 Timestamp('2024-05-14 20:52:00'),
 Timestamp('2024-05-15 20:52:00'),
 Timestamp('2024-05-16 20:52:00'),
 Timestamp('2024-05-17 20:52:00'),
 Timestamp('2024-05-18 20:52:00'),
 Timestamp('2024-05-18 20:52:00'),
 Timestamp('2024-05-20 20:52:00'),
 Timestamp('2024-05-20 20:52:00'),
 Timestamp('2024-05-21 20:52:00'),
 Timestamp('2024-05-21 20:52:00'),
 Timestamp('2024-05-21 20:52:00'),
 Timestamp('2024-05-21 20:52:00'),
 Timestamp('2024-05-21 20:52:00'),
 Timestamp('2024-05-25 20:52:00'),
 Timestamp('2024-05-25 20:52:00'),
 Timestamp('2024-05-25 20:52:00'),
 Timestamp('2024-05-28 20:52:00'),
 Timestamp('2024-05-28 20:52:00'),
 Timestamp('2024-05-30 20:52:00'),
 Timestamp('2024-05-30 20:52:00'),
 Timestamp('2024-05-31 20:52:00'),
 Timestamp('2024-06-01 20:52:00'),
 Timestamp('2024-06-01 20:52:00'),
 Timestamp('2024-06-01 20:52:00'),
 Timestamp('2024-06-01 20:52:00'),
 Timestamp('2024-06-03 20:52:00'),
 Timestamp('2024-06-03 20:52:00'),
 Timestamp('2024-06-05 20:52:00'),
 Timestamp('2024-06-08 20:52:00'),
 Timestamp('2024-06-09 20:52:00'),
 Timestamp('2024-06-09 20:52:00'),
 Timestamp('2024-06-09 20:52:00'),
 Timestamp('2024-06-10 20:52:00'),
 Timestamp('2024-06-10 20:52:00'),
 Timestamp('2024-06-10 20:52:00'),
 Timestamp('2024-06-11 20:52:00'),
 Timestamp('2024-06-12 20:52:00'),
 Timestamp('2024-06-13 20:52:00'),
 Timestamp('2024-06-14 20:52:00'),
 Timestamp('2024-06-16 20:52:00'),
 Timestamp('2024-06-16 20:52:00'),
 Timestamp('2024-06-17 20:52:00'),
 Timestamp('2024-06-17 20:52:00'),
 Timestamp('2024-06-17 20:52:00'),
 Timestamp('2024-06-18 20:52:00'),
 Timestamp('2024-06-18 20:52:00'),
 Timestamp('2024-06-20 20:52:00'),
 Timestamp('2024-06-21 20:52:00'),
 Timestamp('2024-06-22 20:52:00'),
 Timestamp('2024-06-22 20:52:00'),
 Timestamp('2024-06-23 20:52:00'),
 Timestamp('2024-06-23 20:52:00'),
 Timestamp('2024-06-25 20:52:00'),
 Timestamp('2024-06-28 20:52:00'),
 Timestamp('2024-06-29 20:52:00'),
 Timestamp('2024-06-30 20:52:00'),
 Timestamp('2024-06-30 20:52:00'),
 Timestamp('2024-07-01 20:52:00'),
 Timestamp('2024-07-02 20:52:00'),
 Timestamp('2024-07-04 20:52:00'),
 Timestamp('2024-07-04 20:52:00'),
 Timestamp('2024-07-05 20:52:00'),
 Timestamp('2024-07-05 20:52:00'),
 Timestamp('2024-07-08 20:52:00'),
 Timestamp('2024-07-08 20:52:00'),
 Timestamp('2024-07-09 20:52:00'),
 Timestamp('2024-07-09 20:52:00'),
 Timestamp('2024-07-10 20:52:00'),
 Timestamp('2024-07-10 20:52:00'),
 Timestamp('2024-07-11 20:52:00'),
 Timestamp('2024-07-11 20:52:00'),
 Timestamp('2024-07-12 20:52:00'),
 Timestamp('2024-07-12 20:52:00'),
 Timestamp('2024-07-13 20:52:00'),
 Timestamp('2024-07-16 20:52:00'),
 Timestamp('2024-07-17 20:52:00'),
 Timestamp('2024-07-19 20:52:00'),
 Timestamp('2024-07-20 20:52:00'),
 Timestamp('2024-07-20 20:52:00'),
 Timestamp('2024-07-20 20:52:00'),
 Timestamp('2024-07-20 20:52:00'),
 Timestamp('2024-07-21 20:52:00'),
 Timestamp('2024-07-22 20:52:00'),
 Timestamp('2024-07-22 20:52:00'),
 Timestamp('2024-07-24 20:52:00'),
 Timestamp('2024-07-26 20:52:00'),
 Timestamp('2024-07-26 20:52:00'),
 Timestamp('2024-07-27 20:52:00'),
 Timestamp('2024-07-29 20:52:00'),
 Timestamp('2024-07-29 20:52:00'),
 Timestamp('2024-07-29 20:52:00'),
 Timestamp('2024-07-29 20:52:00'),
 Timestamp('2024-07-30 20:52:00'),
 Timestamp('2024-08-01 20:52:00'),
 Timestamp('2024-08-02 20:52:00'),
 Timestamp('2024-08-02 20:52:00'),
 Timestamp('2024-08-03 20:52:00'),
 Timestamp('2024-08-03 20:52:00'),
 Timestamp('2024-08-03 20:52:00'),
 Timestamp('2024-08-05 20:52:00'),
 Timestamp('2024-08-05 20:52:00'),
 Timestamp('2024-08-12 20:52:00'),
 Timestamp('2024-08-12 20:52:00'),
 Timestamp('2024-08-13 20:52:00'),
 Timestamp('2024-08-13 20:52:00'),
 Timestamp('2024-08-14 20:52:00'),
 Timestamp('2024-08-15 20:52:00'),
 Timestamp('2024-08-18 20:52:00'),
 Timestamp('2024-08-19 20:52:00'),
 Timestamp('2024-08-19 20:52:00'),
 Timestamp('2024-08-21 20:52:00'),
 Timestamp('2024-08-22 20:52:00'),
 Timestamp('2024-08-22 20:52:00'),
 Timestamp('2024-08-23 20:52:00'),
 Timestamp('2024-08-23 20:52:00'),
 Timestamp('2024-08-25 20:52:00'),
 Timestamp('2024-08-26 20:52:00'),
 Timestamp('2024-08-26 20:52:00'),
 Timestamp('2024-08-26 20:52:00'),
 Timestamp('2024-08-27 20:52:00'),
 Timestamp('2024-08-28 20:52:00'),
 Timestamp('2024-08-28 20:52:00'),
 Timestamp('2024-08-28 20:52:00'),
 Timestamp('2024-08-29 20:52:00'),
 Timestamp('2024-08-31 20:52:00'),
 Timestamp('2024-09-01 20:52:00'),
 Timestamp('2024-09-01 20:52:00'),
 Timestamp('2024-09-02 20:52:00'),
 Timestamp('2024-09-02 20:52:00'),
 Timestamp('2024-09-07 20:52:00'),
 Timestamp('2024-09-07 20:52:00'),
 Timestamp('2024-09-09 20:52:00'),
 Timestamp('2024-09-10 20:52:00'),
 Timestamp('2024-09-11 20:52:00'),
 Timestamp('2024-09-12 20:52:00'),
 Timestamp('2024-09-13 20:52:00'),
 Timestamp('2024-09-18 20:52:00'),
 Timestamp('2024-09-18 20:52:00'),
 Timestamp('2024-09-18 20:52:00'),
 Timestamp('2024-09-19 20:52:00'),
 Timestamp('2024-09-19 20:52:00'),
 Timestamp('2024-09-20 20:52:00'),
 Timestamp('2024-09-21 20:52:00'),
 Timestamp('2024-09-22 20:52:00'),
 Timestamp('2024-09-22 20:52:00'),
 Timestamp('2024-09-23 20:52:00'),
 Timestamp('2024-09-23 20:52:00'),
 Timestamp('2024-09-24 20:52:00'),
 Timestamp('2024-09-25 20:52:00'),
 Timestamp('2024-09-26 20:52:00'),
 Timestamp('2024-09-28 20:52:00'),
 Timestamp('2024-09-28 20:52:00'),
 Timestamp('2024-09-28 20:52:00'),
 Timestamp('2024-09-28 20:52:00'),
 Timestamp('2024-09-28 20:52:00'),
 Timestamp('2024-09-29 20:52:00'),
 Timestamp('2024-09-29 20:52:00'),
 Timestamp('2024-09-30 20:52:00'),
 Timestamp('2024-10-01 20:52:00'),
 Timestamp('2024-10-03 20:52:00'),
 Timestamp('2024-10-03 20:52:00'),
 Timestamp('2024-10-04 20:52:00'),
 Timestamp('2024-10-06 20:52:00'),
 Timestamp('2024-10-07 20:52:00'),
 Timestamp('2024-10-08 20:52:00'),
 Timestamp('2024-10-09 20:52:00'),
 Timestamp('2024-10-11 20:52:00'),
 Timestamp('2024-10-11 20:52:00'),
 Timestamp('2024-10-13 20:52:00'),
 Timestamp('2024-10-14 20:52:00'),
 Timestamp('2024-10-17 20:52:00'),
 Timestamp('2024-10-19 20:52:00'),
 Timestamp('2024-10-20 20:52:00'),
 Timestamp('2024-10-20 20:52:00'),
 Timestamp('2024-10-21 20:52:00'),
 Timestamp('2024-10-25 20:52:00'),
 Timestamp('2024-10-25 20:52:00'),
 Timestamp('2024-10-25 20:52:00'),
 Timestamp('2024-10-25 20:52:00'),
 Timestamp('2024-10-27 20:52:00'),
 Timestamp('2024-10-29 20:52:00'),
 Timestamp('2024-10-29 20:52:00'),
 Timestamp('2024-10-29 20:52:00'),
 Timestamp('2024-10-30 20:52:00'),
 Timestamp('2024-10-30 20:52:00'),
 Timestamp('2024-10-30 20:52:00'),
 Timestamp('2024-11-02 20:52:00'),
 Timestamp('2024-11-03 20:52:00'),
 Timestamp('2024-11-04 20:52:00'),
 Timestamp('2024-11-04 20:52:00'),
 Timestamp('2024-11-04 20:52:00'),
 Timestamp('2024-11-06 20:52:00'),
 Timestamp('2024-11-07 20:52:00'),
 Timestamp('2024-11-07 20:52:00'),
 Timestamp('2024-11-08 20:52:00'),
 Timestamp('2024-11-09 20:52:00'),
 Timestamp('2024-11-10 20:52:00'),
 Timestamp('2024-11-13 20:52:00'),
 Timestamp('2024-11-13 20:52:00'),
 Timestamp('2024-11-13 20:52:00'),
 Timestamp('2024-11-14 20:52:00'),
 Timestamp('2024-11-16 20:52:00'),
 Timestamp('2024-11-16 20:52:00'),
 Timestamp('2024-11-16 20:52:00'),
 Timestamp('2024-11-16 20:52:00'),
 Timestamp('2024-11-17 20:52:00'),
 Timestamp('2024-11-18 20:52:00'),
 Timestamp('2024-11-18 20:52:00'),
 Timestamp('2024-11-19 20:52:00'),
 Timestamp('2024-11-20 20:52:00'),
 Timestamp('2024-11-21 20:52:00'),
 Timestamp('2024-11-21 20:52:00'),
 Timestamp('2024-11-23 20:52:00'),
 Timestamp('2024-11-23 20:52:00'),
 Timestamp('2024-11-24 20:52:00'),
 Timestamp('2024-11-25 20:52:00'),
 Timestamp('2024-11-26 20:52:00'),
 Timestamp('2024-11-28 20:52:00'),
 Timestamp('2024-11-29 20:52:00'),
 Timestamp('2024-11-29 20:52:00'),
 Timestamp('2024-12-02 20:52:00'),
 Timestamp('2024-12-02 20:52:00'),
 Timestamp('2024-12-04 20:52:00'),
 Timestamp('2024-12-04 20:52:00'),
 Timestamp('2024-12-05 20:52:00'),
 Timestamp('2024-12-07 20:52:00'),
 Timestamp('2024-12-08 20:52:00'),
 Timestamp('2024-12-09 20:52:00'),
 Timestamp('2024-12-09 20:52:00'),
 Timestamp('2024-12-09 20:52:00'),
 Timestamp('2024-12-10 20:52:00'),
 Timestamp('2024-12-10 20:52:00'),
 Timestamp('2024-12-11 20:52:00'),
 Timestamp('2024-12-12 20:52:00'),
 Timestamp('2024-12-14 20:52:00'),
 Timestamp('2024-12-15 20:52:00'),
 Timestamp('2024-12-16 20:52:00'),
 Timestamp('2024-12-17 20:52:00'),
 Timestamp('2024-12-18 20:52:00'),
 Timestamp('2024-12-18 20:52:00'),
 Timestamp('2024-12-19 20:52:00'),
 Timestamp('2024-12-19 20:52:00'),
 Timestamp('2024-12-20 20:52:00'),
 Timestamp('2024-12-21 20:52:00'),
 Timestamp('2024-12-22 20:52:00'),
 Timestamp('2024-12-22 20:52:00'),
 Timestamp('2024-12-23 20:52:00'),
 Timestamp('2024-12-23 20:52:00'),
 Timestamp('2024-12-25 20:52:00'),
 Timestamp('2024-12-25 20:52:00'),
 Timestamp('2024-12-26 20:52:00'),
 Timestamp('2024-12-26 20:52:00'),

In [558]:
bronze_menstrual_cycle_startdate_df['Next Cycle Start Date'] = pd.to_datetime(bronze_menstrual_cycle_startdate_df['Next Cycle Start Date'], format='%d/%m/%Y %H:%M')

C:\Users\cadav\AppData\Local\Temp\ipykernel_11152\2543635064.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bronze_menstrual_cycle_startdate_df['Next Cycle Start Date'] = pd.to_datetime(bronze_menstrual_cycle_startdate_df['Next Cycle Start Date'], format='%d/%m/%Y %H:%M')

In [559]:
bronze_menstrual_cycle_startdate_df.head()

,User ID,Age,Stress Level,Exercise Frequency,Sleep Hours,Diet,Cycle Start Date,Cycle Length,Period Length,Next Cycle Start Date,Symptoms,BMI,_BronzeTimestamp
0,1.0,18.0,2.0,Moderate,54.0,Low Carb,2024-11-13 20:52:00,26,7.0,2024-12-09 20:52:00,Headache,29.28,2025-11-06 19:16:40.445350
1,1.0,18.0,2.0,Moderate,54.0,Low Carb,2024-12-09 20:52:00,32,5.0,2025-01-10 20:52:00,Fatigue,29.28,2025-11-06 19:16:40.445350
2,1.0,18.0,2.0,Moderate,54.0,Low Carb,2025-01-10 20:52:00,41,7.0,2025-02-20 20:52:00,Fatigue,29.28,2025-11-06 19:16:40.445350
3,1.0,18.0,2.0,Moderate,54.0,Low Carb,2025-02-20 20:52:00,27,3.0,2025-03-19 20:52:00,Fatigue,29.28,2025-11-06 19:16:40.445350
4,1.0,18.0,2.0,Moderate,54.0,Low Carb,2025-03-19 20:52:00,42,5.0,2025-04-30 20:52:00,Cramps,29.28,2025-11-06 19:16:40.445350

In [549]:
bronze_menstrual_cycle_startdate_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 862 entries, 0 to 894
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   User ID                862 non-null    float64
 1   Age                    862 non-null    float64
 2   Stress Level           862 non-null    float64
 3   Exercise Frequency     862 non-null    object
 4   Sleep Hours            862 non-null    float64
 5   Diet                   862 non-null    object
 6   Cycle Start Date       862 non-null    datetime64[ns]
 7   Cycle Length           862 non-null    int64
 8   Period Length          862 non-null    float64
 9   Next Cycle Start Date  862 non-null    datetime64[ns]
 10  Symptoms               862 non-null    object
 11  BMI                    862 non-null    float64
 12  _BronzeTimestamp       862 non-null    datetime64[us]
dtypes: datetime64[ns](2), datetime64[us](1), float64(6), int64(1), object(3)
memory usage: 94.3+ KB

In [560]:
sorted(bronze_menstrual_cycle_startdate_df['Next Cycle Start Date'])

[Timestamp('2023-04-17 20:52:00'),
 Timestamp('2023-04-22 20:52:00'),
 Timestamp('2023-04-29 20:52:00'),
 Timestamp('2023-05-01 20:52:00'),
 Timestamp('2023-05-12 20:52:00'),
 Timestamp('2023-05-17 20:52:00'),
 Timestamp('2023-05-22 20:52:00'),
 Timestamp('2023-05-23 20:52:00'),
 Timestamp('2023-05-29 20:52:00'),
 Timestamp('2023-06-03 20:52:00'),
 Timestamp('2023-06-03 20:52:00'),
 Timestamp('2023-06-04 20:52:00'),
 Timestamp('2023-06-06 20:52:00'),
 Timestamp('2023-06-09 20:52:00'),
 Timestamp('2023-06-10 20:52:00'),
 Timestamp('2023-06-23 20:52:00'),
 Timestamp('2023-06-27 20:52:00'),
 Timestamp('2023-06-28 20:52:00'),
 Timestamp('2023-07-02 20:52:00'),
 Timestamp('2023-07-07 20:52:00'),
 Timestamp('2023-07-10 20:52:00'),
 Timestamp('2023-07-10 20:52:00'),
 Timestamp('2023-07-11 20:52:00'),
 Timestamp('2023-07-12 20:52:00'),
 Timestamp('2023-07-13 20:52:00'),
 Timestamp('2023-07-14 20:52:00'),
 Timestamp('2023-07-17 20:52:00'),
 Timestamp('2023-07-20 20:52:00'),
 Timestamp('2023-07-24 20:52:00'),
 Timestamp('2023-08-01 20:52:00'),
 Timestamp('2023-08-02 20:52:00'),
 Timestamp('2023-08-05 20:52:00'),
 Timestamp('2023-08-06 20:52:00'),
 Timestamp('2023-08-11 20:52:00'),
 Timestamp('2023-08-14 20:52:00'),
 Timestamp('2023-08-14 20:52:00'),
 Timestamp('2023-08-15 20:52:00'),
 Timestamp('2023-08-17 20:52:00'),
 Timestamp('2023-08-19 20:52:00'),
 Timestamp('2023-08-20 20:52:00'),
 Timestamp('2023-08-21 20:52:00'),
 Timestamp('2023-08-21 20:52:00'),
 Timestamp('2023-08-23 20:52:00'),
 Timestamp('2023-08-24 20:52:00'),
 Timestamp('2023-08-25 20:52:00'),
 Timestamp('2023-08-26 20:52:00'),
 Timestamp('2023-08-26 20:52:00'),
 Timestamp('2023-08-29 20:52:00'),
 Timestamp('2023-09-01 20:52:00'),
 Timestamp('2023-09-03 20:52:00'),
 Timestamp('2023-09-04 20:52:00'),
 Timestamp('2023-09-05 20:52:00'),
 Timestamp('2023-09-10 20:52:00'),
 Timestamp('2023-09-10 20:52:00'),
 Timestamp('2023-09-13 20:52:00'),
 Timestamp('2023-09-14 20:52:00'),
 Timestamp('2023-09-14 20:52:00'),
 Timestamp('2023-09-15 20:52:00'),
 Timestamp('2023-09-16 20:52:00'),
 Timestamp('2023-09-17 20:52:00'),
 Timestamp('2023-09-19 20:52:00'),
 Timestamp('2023-09-21 20:52:00'),
 Timestamp('2023-09-22 20:52:00'),
 Timestamp('2023-09-23 20:52:00'),
 Timestamp('2023-09-27 20:52:00'),
 Timestamp('2023-09-28 20:52:00'),
 Timestamp('2023-09-29 20:52:00'),
 Timestamp('2023-09-30 20:52:00'),
 Timestamp('2023-10-02 20:52:00'),
 Timestamp('2023-10-04 20:52:00'),
 Timestamp('2023-10-06 20:52:00'),
 Timestamp('2023-10-07 20:52:00'),
 Timestamp('2023-10-09 20:52:00'),
 Timestamp('2023-10-10 20:52:00'),
 Timestamp('2023-10-11 20:52:00'),
 Timestamp('2023-10-12 20:52:00'),
 Timestamp('2023-10-15 20:52:00'),
 Timestamp('2023-10-18 20:52:00'),
 Timestamp('2023-10-18 20:52:00'),
 Timestamp('2023-10-19 20:52:00'),
 Timestamp('2023-10-20 20:52:00'),
 Timestamp('2023-10-20 20:52:00'),
 Timestamp('2023-10-21 20:52:00'),
 Timestamp('2023-10-23 20:52:00'),
 Timestamp('2023-10-26 20:52:00'),
 Timestamp('2023-10-27 20:52:00'),
 Timestamp('2023-10-27 20:52:00'),
 Timestamp('2023-10-29 20:52:00'),
 Timestamp('2023-10-31 20:52:00'),
 Timestamp('2023-11-03 20:52:00'),
 Timestamp('2023-11-03 20:52:00'),
 Timestamp('2023-11-10 20:52:00'),
 Timestamp('2023-11-10 20:52:00'),
 Timestamp('2023-11-10 20:52:00'),
 Timestamp('2023-11-12 20:52:00'),
 Timestamp('2023-11-12 20:52:00'),
 Timestamp('2023-11-13 20:52:00'),
 Timestamp('2023-11-13 20:52:00'),
 Timestamp('2023-11-14 20:52:00'),
 Timestamp('2023-11-15 20:52:00'),
 Timestamp('2023-11-17 20:52:00'),
 Timestamp('2023-11-17 20:52:00'),
 Timestamp('2023-11-19 20:52:00'),
 Timestamp('2023-11-22 20:52:00'),
 Timestamp('2023-11-23 20:52:00'),
 Timestamp('2023-11-23 20:52:00'),
 Timestamp('2023-11-24 20:52:00'),
 Timestamp('2023-11-25 20:52:00'),
 Timestamp('2023-11-25 20:52:00'),
 Timestamp('2023-11-25 20:52:00'),
 Timestamp('2023-11-26 20:52:00'),
 Timestamp('2023-11-26 20:52:00'),
 Timestamp('2023-11-28 20:52:00'),
 Timestamp('2023-11-30 20:52:00'),
 Timestamp('2023-12-07 20:52:00'),
 Timestamp('2023-12-07 20:52:00'),
 Timestamp('2023-12-07 20:52:00'),
 Timestamp('2023-12-08 20:52:00'),
 Timestamp('2023-12-08 20:52:00'),
 Timestamp('2023-12-09 20:52:00'),
 Timestamp('2023-12-09 20:52:00'),
 Timestamp('2023-12-11 20:52:00'),
 Timestamp('2023-12-11 20:52:00'),
 Timestamp('2023-12-12 20:52:00'),
 Timestamp('2023-12-16 20:52:00'),
 Timestamp('2023-12-16 20:52:00'),
 Timestamp('2023-12-17 20:52:00'),
 Timestamp('2023-12-19 20:52:00'),
 Timestamp('2023-12-19 20:52:00'),
 Timestamp('2023-12-20 20:52:00'),
 Timestamp('2023-12-21 20:52:00'),
 Timestamp('2023-12-21 20:52:00'),
 Timestamp('2023-12-22 20:52:00'),
 Timestamp('2023-12-22 20:52:00'),
 Timestamp('2023-12-23 20:52:00'),
 Timestamp('2023-12-23 20:52:00'),
 Timestamp('2023-12-24 20:52:00'),
 Timestamp('2023-12-24 20:52:00'),
 Timestamp('2023-12-24 20:52:00'),
 Timestamp('2023-12-26 20:52:00'),
 Timestamp('2023-12-29 20:52:00'),
 Timestamp('2023-12-29 20:52:00'),
 Timestamp('2024-01-01 20:52:00'),
 Timestamp('2024-01-02 20:52:00'),
 Timestamp('2024-01-04 20:52:00'),
 Timestamp('2024-01-05 20:52:00'),
 Timestamp('2024-01-07 20:52:00'),
 Timestamp('2024-01-09 20:52:00'),
 Timestamp('2024-01-11 20:52:00'),
 Timestamp('2024-01-11 20:52:00'),
 Timestamp('2024-01-15 20:52:00'),
 Timestamp('2024-01-15 20:52:00'),
 Timestamp('2024-01-17 20:52:00'),
 Timestamp('2024-01-17 20:52:00'),
 Timestamp('2024-01-18 20:52:00'),
 Timestamp('2024-01-18 20:52:00'),
 Timestamp('2024-01-18 20:52:00'),
 Timestamp('2024-01-21 20:52:00'),
 Timestamp('2024-01-22 20:52:00'),
 Timestamp('2024-01-22 20:52:00'),
 Timestamp('2024-01-23 20:52:00'),
 Timestamp('2024-01-23 20:52:00'),
 Timestamp('2024-01-24 20:52:00'),
 Timestamp('2024-01-25 20:52:00'),
 Timestamp('2024-01-27 20:52:00'),
 Timestamp('2024-01-27 20:52:00'),
 Timestamp('2024-01-27 20:52:00'),
 Timestamp('2024-01-27 20:52:00'),
 Timestamp('2024-01-28 20:52:00'),
 Timestamp('2024-01-28 20:52:00'),
 Timestamp('2024-01-28 20:52:00'),
 Timestamp('2024-01-29 20:52:00'),
 Timestamp('2024-02-05 20:52:00'),
 Timestamp('2024-02-05 20:52:00'),
 Timestamp('2024-02-06 20:52:00'),
 Timestamp('2024-02-07 20:52:00'),
 Timestamp('2024-02-07 20:52:00'),
 Timestamp('2024-02-08 20:52:00'),
 Timestamp('2024-02-08 20:52:00'),
 Timestamp('2024-02-09 20:52:00'),
 Timestamp('2024-02-09 20:52:00'),
 Timestamp('2024-02-11 20:52:00'),
 Timestamp('2024-02-11 20:52:00'),
 Timestamp('2024-02-12 20:52:00'),
 Timestamp('2024-02-12 20:52:00'),
 Timestamp('2024-02-17 20:52:00'),
 Timestamp('2024-02-18 20:52:00'),
 Timestamp('2024-02-20 20:52:00'),
 Timestamp('2024-02-21 20:52:00'),
 Timestamp('2024-02-22 20:52:00'),
 Timestamp('2024-02-22 20:52:00'),
 Timestamp('2024-02-23 20:52:00'),
 Timestamp('2024-02-25 20:52:00'),
 Timestamp('2024-02-25 20:52:00'),
 Timestamp('2024-02-26 20:52:00'),
 Timestamp('2024-02-26 20:52:00'),
 Timestamp('2024-02-27 20:52:00'),
 Timestamp('2024-02-28 20:52:00'),
 Timestamp('2024-02-28 20:52:00'),
 Timestamp('2024-02-29 20:52:00'),
 Timestamp('2024-03-01 20:52:00'),
 Timestamp('2024-03-02 20:52:00'),
 Timestamp('2024-03-02 20:52:00'),
 Timestamp('2024-03-03 20:52:00'),
 Timestamp('2024-03-05 20:52:00'),
 Timestamp('2024-03-07 20:52:00'),
 Timestamp('2024-03-09 20:52:00'),
 Timestamp('2024-03-10 20:52:00'),
 Timestamp('2024-03-10 20:52:00'),
 Timestamp('2024-03-11 20:52:00'),
 Timestamp('2024-03-11 20:52:00'),
 Timestamp('2024-03-12 20:52:00'),
 Timestamp('2024-03-13 20:52:00'),
 Timestamp('2024-03-14 20:52:00'),
 Timestamp('2024-03-15 20:52:00'),
 Timestamp('2024-03-16 20:52:00'),
 Timestamp('2024-03-16 20:52:00'),
 Timestamp('2024-03-17 20:52:00'),
 Timestamp('2024-03-18 20:52:00'),
 Timestamp('2024-03-21 20:52:00'),
 Timestamp('2024-03-21 20:52:00'),
 Timestamp('2024-03-21 20:52:00'),
 Timestamp('2024-03-22 20:52:00'),
 Timestamp('2024-03-23 20:52:00'),
 Timestamp('2024-03-23 20:52:00'),
 Timestamp('2024-03-25 20:52:00'),
 Timestamp('2024-03-25 20:52:00'),
 Timestamp('2024-03-26 20:52:00'),
 Timestamp('2024-03-30 20:52:00'),
 Timestamp('2024-03-30 20:52:00'),
 Timestamp('2024-04-02 20:52:00'),
 Timestamp('2024-04-02 20:52:00'),
 Timestamp('2024-04-07 20:52:00'),
 Timestamp('2024-04-07 20:52:00'),
 Timestamp('2024-04-08 20:52:00'),
 Timestamp('2024-04-08 20:52:00'),
 Timestamp('2024-04-09 20:52:00'),
 Timestamp('2024-04-09 20:52:00'),
 Timestamp('2024-04-09 20:52:00'),
 Timestamp('2024-04-09 20:52:00'),
 Timestamp('2024-04-10 20:52:00'),
 Timestamp('2024-04-14 20:52:00'),
 Timestamp('2024-04-14 20:52:00'),
 Timestamp('2024-04-15 20:52:00'),
 Timestamp('2024-04-15 20:52:00'),
 Timestamp('2024-04-15 20:52:00'),
 Timestamp('2024-04-16 20:52:00'),
 Timestamp('2024-04-16 20:52:00'),
 Timestamp('2024-04-17 20:52:00'),
 Timestamp('2024-04-17 20:52:00'),
 Timestamp('2024-04-19 20:52:00'),
 Timestamp('2024-04-20 20:52:00'),
 Timestamp('2024-04-20 20:52:00'),
 Timestamp('2024-04-21 20:52:00'),
 Timestamp('2024-04-22 20:52:00'),
 Timestamp('2024-04-22 20:52:00'),
 Timestamp('2024-04-22 20:52:00'),
 Timestamp('2024-04-24 20:52:00'),
 Timestamp('2024-04-25 20:52:00'),
 Timestamp('2024-04-26 20:52:00'),
 Timestamp('2024-04-28 20:52:00'),
 Timestamp('2024-04-28 20:52:00'),
 Timestamp('2024-04-29 20:52:00'),
 Timestamp('2024-04-29 20:52:00'),
 Timestamp('2024-04-30 20:52:00'),
 Timestamp('2024-04-30 20:52:00'),
 Timestamp('2024-05-02 20:52:00'),
 Timestamp('2024-05-03 20:52:00'),
 Timestamp('2024-05-04 20:52:00'),
 Timestamp('2024-05-04 20:52:00'),
 Timestamp('2024-05-05 20:52:00'),
 Timestamp('2024-05-06 20:52:00'),
 Timestamp('2024-05-07 20:52:00'),
 Timestamp('2024-05-10 20:52:00'),
 Timestamp('2024-05-10 20:52:00'),
 Timestamp('2024-05-11 20:52:00'),
 Timestamp('2024-05-13 20:52:00'),
 Timestamp('2024-05-14 20:52:00'),
 Timestamp('2024-05-14 20:52:00'),
 Timestamp('2024-05-15 20:52:00'),
 Timestamp('2024-05-16 20:52:00'),
 Timestamp('2024-05-17 20:52:00'),
 Timestamp('2024-05-18 20:52:00'),
 Timestamp('2024-05-18 20:52:00'),
 Timestamp('2024-05-20 20:52:00'),
 Timestamp('2024-05-20 20:52:00'),
 Timestamp('2024-05-21 20:52:00'),
 Timestamp('2024-05-21 20:52:00'),
 Timestamp('2024-05-21 20:52:00'),
 Timestamp('2024-05-21 20:52:00'),
 Timestamp('2024-05-25 20:52:00'),
 Timestamp('2024-05-25 20:52:00'),
 Timestamp('2024-05-28 20:52:00'),
 Timestamp('2024-05-28 20:52:00'),
 Timestamp('2024-05-29 20:52:00'),
 Timestamp('2024-05-30 20:52:00'),
 Timestamp('2024-05-30 20:52:00'),
 Timestamp('2024-05-31 20:52:00'),
 Timestamp('2024-06-01 20:52:00'),
 Timestamp('2024-06-01 20:52:00'),
 Timestamp('2024-06-01 20:52:00'),
 Timestamp('2024-06-01 20:52:00'),
 Timestamp('2024-06-03 20:52:00'),
 Timestamp('2024-06-03 20:52:00'),
 Timestamp('2024-06-05 20:52:00'),
 Timestamp('2024-06-08 20:52:00'),
 Timestamp('2024-06-09 20:52:00'),
 Timestamp('2024-06-09 20:52:00'),
 Timestamp('2024-06-09 20:52:00'),
 Timestamp('2024-06-10 20:52:00'),
 Timestamp('2024-06-10 20:52:00'),
 Timestamp('2024-06-11 20:52:00'),
 Timestamp('2024-06-11 20:52:00'),
 Timestamp('2024-06-14 20:52:00'),
 Timestamp('2024-06-16 20:52:00'),
 Timestamp('2024-06-16 20:52:00'),
 Timestamp('2024-06-17 20:52:00'),
 Timestamp('2024-06-17 20:52:00'),
 Timestamp('2024-06-17 20:52:00'),
 Timestamp('2024-06-18 20:52:00'),
 Timestamp('2024-06-18 20:52:00'),
 Timestamp('2024-06-20 20:52:00'),
 Timestamp('2024-06-22 20:52:00'),
 Timestamp('2024-06-22 20:52:00'),
 Timestamp('2024-06-23 20:52:00'),
 Timestamp('2024-06-23 20:52:00'),
 Timestamp('2024-06-25 20:52:00'),
 Timestamp('2024-06-28 20:52:00'),
 Timestamp('2024-06-29 20:52:00'),
 Timestamp('2024-06-30 20:52:00'),
 Timestamp('2024-06-30 20:52:00'),
 Timestamp('2024-07-01 20:52:00'),
 Timestamp('2024-07-02 20:52:00'),
 Timestamp('2024-07-04 20:52:00'),
 Timestamp('2024-07-04 20:52:00'),
 Timestamp('2024-07-05 20:52:00'),
 Timestamp('2024-07-05 20:52:00'),
 Timestamp('2024-07-07 20:52:00'),
 Timestamp('2024-07-08 20:52:00'),
 Timestamp('2024-07-08 20:52:00'),
 Timestamp('2024-07-09 20:52:00'),
 Timestamp('2024-07-10 20:52:00'),
 Timestamp('2024-07-11 20:52:00'),
 Timestamp('2024-07-11 20:52:00'),
 Timestamp('2024-07-12 20:52:00'),
 Timestamp('2024-07-12 20:52:00'),
 Timestamp('2024-07-13 20:52:00'),
 Timestamp('2024-07-14 20:52:00'),
 Timestamp('2024-07-16 20:52:00'),
 Timestamp('2024-07-17 20:52:00'),
 Timestamp('2024-07-19 20:52:00'),
 Timestamp('2024-07-20 20:52:00'),
 Timestamp('2024-07-20 20:52:00'),
 Timestamp('2024-07-20 20:52:00'),
 Timestamp('2024-07-20 20:52:00'),
 Timestamp('2024-07-20 20:52:00'),
 Timestamp('2024-07-21 20:52:00'),
 Timestamp('2024-07-22 20:52:00'),
 Timestamp('2024-07-22 20:52:00'),
 Timestamp('2024-07-23 20:52:00'),
 Timestamp('2024-07-26 20:52:00'),
 Timestamp('2024-07-26 20:52:00'),
 Timestamp('2024-07-27 20:52:00'),
 Timestamp('2024-07-29 20:52:00'),
 Timestamp('2024-07-29 20:52:00'),
 Timestamp('2024-07-29 20:52:00'),
 Timestamp('2024-07-30 20:52:00'),
 Timestamp('2024-08-01 20:52:00'),
 Timestamp('2024-08-01 20:52:00'),
 Timestamp('2024-08-02 20:52:00'),
 Timestamp('2024-08-02 20:52:00'),
 Timestamp('2024-08-03 20:52:00'),
 Timestamp('2024-08-03 20:52:00'),
 Timestamp('2024-08-03 20:52:00'),
 Timestamp('2024-08-05 20:52:00'),
 Timestamp('2024-08-05 20:52:00'),
 Timestamp('2024-08-08 20:52:00'),
 Timestamp('2024-08-12 20:52:00'),
 Timestamp('2024-08-12 20:52:00'),
 Timestamp('2024-08-13 20:52:00'),
 Timestamp('2024-08-13 20:52:00'),
 Timestamp('2024-08-14 20:52:00'),
 Timestamp('2024-08-15 20:52:00'),
 Timestamp('2024-08-18 20:52:00'),
 Timestamp('2024-08-18 20:52:00'),
 Timestamp('2024-08-19 20:52:00'),
 Timestamp('2024-08-19 20:52:00'),
 Timestamp('2024-08-21 20:52:00'),
 Timestamp('2024-08-21 20:52:00'),
 Timestamp('2024-08-22 20:52:00'),
 Timestamp('2024-08-22 20:52:00'),
 Timestamp('2024-08-23 20:52:00'),
 Timestamp('2024-08-23 20:52:00'),
 Timestamp('2024-08-26 20:52:00'),
 Timestamp('2024-08-26 20:52:00'),
 Timestamp('2024-08-26 20:52:00'),
 Timestamp('2024-08-27 20:52:00'),
 Timestamp('2024-08-27 20:52:00'),
 Timestamp('2024-08-28 20:52:00'),
 Timestamp('2024-08-28 20:52:00'),
 Timestamp('2024-08-28 20:52:00'),
 Timestamp('2024-08-29 20:52:00'),
 Timestamp('2024-08-31 20:52:00'),
 Timestamp('2024-09-01 20:52:00'),
 Timestamp('2024-09-01 20:52:00'),
 Timestamp('2024-09-02 20:52:00'),
 Timestamp('2024-09-02 20:52:00'),
 Timestamp('2024-09-02 20:52:00'),
 Timestamp('2024-09-04 20:52:00'),
 Timestamp('2024-09-07 20:52:00'),
 Timestamp('2024-09-07 20:52:00'),
 Timestamp('2024-09-07 20:52:00'),
 Timestamp('2024-09-07 20:52:00'),
 Timestamp('2024-09-09 20:52:00'),
 Timestamp('2024-09-10 20:52:00'),
 Timestamp('2024-09-11 20:52:00'),
 Timestamp('2024-09-12 20:52:00'),
 Timestamp('2024-09-13 20:52:00'),
 Timestamp('2024-09-18 20:52:00'),
 Timestamp('2024-09-18 20:52:00'),
 Timestamp('2024-09-18 20:52:00'),
 Timestamp('2024-09-19 20:52:00'),
 Timestamp('2024-09-19 20:52:00'),
 Timestamp('2024-09-19 20:52:00'),
 Timestamp('2024-09-20 20:52:00'),
 Timestamp('2024-09-21 20:52:00'),
 Timestamp('2024-09-22 20:52:00'),
 Timestamp('2024-09-23 20:52:00'),
 Timestamp('2024-09-25 20:52:00'),
 Timestamp('2024-09-26 20:52:00'),
 Timestamp('2024-09-28 20:52:00'),
 Timestamp('2024-09-28 20:52:00'),
 Timestamp('2024-09-28 20:52:00'),
 Timestamp('2024-09-28 20:52:00'),
 Timestamp('2024-09-29 20:52:00'),
 Timestamp('2024-09-30 20:52:00'),
 Timestamp('2024-09-30 20:52:00'),
 Timestamp('2024-10-01 20:52:00'),
 Timestamp('2024-10-01 20:52:00'),
 Timestamp('2024-10-03 20:52:00'),
 Timestamp('2024-10-03 20:52:00'),
 Timestamp('2024-10-04 20:52:00'),
 Timestamp('2024-10-08 20:52:00'),
 Timestamp('2024-10-09 20:52:00'),
 Timestamp('2024-10-11 20:52:00'),
 Timestamp('2024-10-13 20:52:00'),
 Timestamp('2024-10-14 20:52:00'),
 Timestamp('2024-10-14 20:52:00'),
 Timestamp('2024-10-17 20:52:00'),
 Timestamp('2024-10-19 20:52:00'),
 Timestamp('2024-10-19 20:52:00'),
 Timestamp('2024-10-20 20:52:00'),
 Timestamp('2024-10-20 20:52:00'),
 Timestamp('2024-10-21 20:52:00'),
 Timestamp('2024-10-25 20:52:00'),
 Timestamp('2024-10-25 20:52:00'),
 Timestamp('2024-10-25 20:52:00'),
 Timestamp('2024-10-25 20:52:00'),
 Timestamp('2024-10-27 20:52:00'),
 Timestamp('2024-10-29 20:52:00'),
 Timestamp('2024-10-29 20:52:00'),
 Timestamp('2024-10-29 20:52:00'),
 Timestamp('2024-10-30 20:52:00'),
 Timestamp('2024-10-30 20:52:00'),
 Timestamp('2024-10-30 20:52:00'),
 Timestamp('2024-10-30 20:52:00'),
 Timestamp('2024-11-03 20:52:00'),
 Timestamp('2024-11-04 20:52:00'),
 Timestamp('2024-11-04 20:52:00'),
 Timestamp('2024-11-06 20:52:00'),
 Timestamp('2024-11-07 20:52:00'),
 Timestamp('2024-11-07 20:52:00'),
 Timestamp('2024-11-08 20:52:00'),
 Timestamp('2024-11-09 20:52:00'),
 Timestamp('2024-11-13 20:52:00'),
 Timestamp('2024-11-13 20:52:00'),
 Timestamp('2024-11-14 20:52:00'),
 Timestamp('2024-11-16 20:52:00'),
 Timestamp('2024-11-16 20:52:00'),
 Timestamp('2024-11-16 20:52:00'),
 Timestamp('2024-11-16 20:52:00'),
 Timestamp('2024-11-17 20:52:00'),
 Timestamp('2024-11-18 20:52:00'),
 Timestamp('2024-11-18 20:52:00'),
 Timestamp('2024-11-19 20:52:00'),
 Timestamp('2024-11-20 20:52:00'),
 Timestamp('2024-11-21 20:52:00'),
 Timestamp('2024-11-23 20:52:00'),
 Timestamp('2024-11-23 20:52:00'),
 Timestamp('2024-11-24 20:52:00'),
 Timestamp('2024-11-26 20:52:00'),
 Timestamp('2024-11-28 20:52:00'),
 Timestamp('2024-11-29 20:52:00'),
 Timestamp('2024-11-29 20:52:00'),
 Timestamp('2024-11-29 20:52:00'),
 Timestamp('2024-12-01 20:52:00'),
 Timestamp('2024-12-02 20:52:00'),
 Timestamp('2024-12-02 20:52:00'),
 Timestamp('2024-12-04 20:52:00'),
 Timestamp('2024-12-04 20:52:00'),
 Timestamp('2024-12-05 20:52:00'),
 Timestamp('2024-12-07 20:52:00'),
 Timestamp('2024-12-08 20:52:00'),
 Timestamp('2024-12-09 20:52:00'),
 Timestamp('2024-12-09 20:52:00'),
 Timestamp('2024-12-09 20:52:00'),
 Timestamp('2024-12-10 20:52:00'),
 Timestamp('2024-12-10 20:52:00'),
 Timestamp('2024-12-11 20:52:00'),
 Timestamp('2024-12-12 20:52:00'),
 Timestamp('2024-12-14 20:52:00'),
 Timestamp('2024-12-15 20:52:00'),
 Timestamp('2024-12-16 20:52:00'),
 Timestamp('2024-12-17 20:52:00'),
 Timestamp('2024-12-18 20:52:00'),
 Timestamp('2024-12-18 20:52:00'),
 Timestamp('2024-12-19 20:52:00'),
 Timestamp('2024-12-19 20:52:00'),
 Timestamp('2024-12-22 20:52:00'),
 Timestamp('2024-12-22 20:52:00'),
 Timestamp('2024-12-25 20:52:00'),
 Timestamp('2024-12-25 20:52:00'),
 Timestamp('2024-12-27 20:52:00'),
 Timestamp('2024-12-27 20:52:00'),
 Timestamp('2024-12-28 20:52:00'),
 Timestamp('2024-12-29 20:52:00'),
 Timestamp('2024-12-31 20:52:00'),
 Timestamp('2025-01-01 20:52:00'),
 Timestamp('2025-01-01 20:52:00'),
 Timestamp('2025-01-01 20:52:00'),
 Timestamp('2025-01-02 20:52:00'),
 Timestamp('2025-01-02 20:52:00'),
 Timestamp('2025-01-02 20:52:00'),
 Timestamp('2025-01-03 20:52:00'),
 Timestamp('2025-01-04 20:52:00'),
 Timestamp('2025-01-04 20:52:00'),
 Timestamp('2025-01-04 20:52:00'),
 Timestamp('2025-01-05 20:52:00'),
 Timestamp('2025-01-06 20:52:00'),
 Timestamp('2025-01-07 20:52:00'),
 Timestamp('2025-01-07 20:52:00'),
 Timestamp('2025-01-09 20:52:00'),
 Timestamp('2025-01-10 20:52:00'),
 Timestamp('2025-01-10 20:52:00'),
 Timestamp('2025-01-10 20:52:00'),
 Timestamp('2025-01-11 20:52:00'),
 Timestamp('2025-01-14 20:52:00'),
 Timestamp('2025-01-15 20:52:00'),
 Timestamp('2025-01-17 20:52:00'),
 Timestamp('2025-01-17 20:52:00'),
 Timestamp('2025-01-18 20:52:00'),
 Timestamp('2025-01-19 20:52:00'),
 Timestamp('2025-01-19 20:52:00'),
 Timestamp('2025-01-20 20:52:00'),
 Timestamp('2025-01-20 20:52:00'),
 Timestamp('2025-01-22 20:52:00'),
 Timestamp('2025-01-27 20:52:00'),
 Timestamp('2025-01-28 20:52:00'),
 Timestamp('2025-01-28 20:52:00'),
 Timestamp('2025-01-28 20:52:00'),
 Timestamp('2025-01-29 20:52:00'),
 Timestamp('2025-01-31 20:52:00'),
 Timestamp('2025-01-31 20:52:00'),
 Timestamp('2025-01-31 20:52:00'),
 Timestamp('2025-02-01 20:52:00'),
 Timestamp('2025-02-02 20:52:00'),
 Timestamp('2025-02-03 20:52:00'),
 Timestamp('2025-02-04 20:52:00'),
 Timestamp('2025-02-04 20:52:00'),
 Timestamp('2025-02-04 20:52:00'),
 Timestamp('2025-02-05 20:52:00'),

In [561]:
bronze_menstrual_cycle_nextstartdate_df = bronze_menstrual_cycle_startdate_df[
    bronze_menstrual_cycle_startdate_df['Next Cycle Start Date'] != '2077-08-10 20:52:00']

In [562]:
sorted(bronze_menstrual_cycle_nextstartdate_df['Next Cycle Start Date'])

[Timestamp('2023-04-17 20:52:00'),
 Timestamp('2023-04-22 20:52:00'),
 Timestamp('2023-04-29 20:52:00'),
 Timestamp('2023-05-01 20:52:00'),
 Timestamp('2023-05-12 20:52:00'),
 Timestamp('2023-05-17 20:52:00'),
 Timestamp('2023-05-22 20:52:00'),
 Timestamp('2023-05-23 20:52:00'),
 Timestamp('2023-05-29 20:52:00'),
 Timestamp('2023-06-03 20:52:00'),
 Timestamp('2023-06-03 20:52:00'),
 Timestamp('2023-06-04 20:52:00'),
 Timestamp('2023-06-06 20:52:00'),
 Timestamp('2023-06-09 20:52:00'),
 Timestamp('2023-06-10 20:52:00'),
 Timestamp('2023-06-23 20:52:00'),
 Timestamp('2023-06-27 20:52:00'),
 Timestamp('2023-06-28 20:52:00'),
 Timestamp('2023-07-02 20:52:00'),
 Timestamp('2023-07-07 20:52:00'),
 Timestamp('2023-07-10 20:52:00'),
 Timestamp('2023-07-10 20:52:00'),
 Timestamp('2023-07-11 20:52:00'),
 Timestamp('2023-07-12 20:52:00'),
 Timestamp('2023-07-13 20:52:00'),
 Timestamp('2023-07-14 20:52:00'),
 Timestamp('2023-07-17 20:52:00'),
 Timestamp('2023-07-20 20:52:00'),
 Timestamp('2023-07-24 20:52:00'),
 Timestamp('2023-08-01 20:52:00'),
 Timestamp('2023-08-02 20:52:00'),
 Timestamp('2023-08-05 20:52:00'),
 Timestamp('2023-08-06 20:52:00'),
 Timestamp('2023-08-11 20:52:00'),
 Timestamp('2023-08-14 20:52:00'),
 Timestamp('2023-08-14 20:52:00'),
 Timestamp('2023-08-15 20:52:00'),
 Timestamp('2023-08-17 20:52:00'),
 Timestamp('2023-08-19 20:52:00'),
 Timestamp('2023-08-20 20:52:00'),
 Timestamp('2023-08-21 20:52:00'),
 Timestamp('2023-08-21 20:52:00'),
 Timestamp('2023-08-23 20:52:00'),
 Timestamp('2023-08-24 20:52:00'),
 Timestamp('2023-08-25 20:52:00'),
 Timestamp('2023-08-26 20:52:00'),
 Timestamp('2023-08-26 20:52:00'),
 Timestamp('2023-08-29 20:52:00'),
 Timestamp('2023-09-01 20:52:00'),
 Timestamp('2023-09-03 20:52:00'),
 Timestamp('2023-09-04 20:52:00'),
 Timestamp('2023-09-05 20:52:00'),
 Timestamp('2023-09-10 20:52:00'),
 Timestamp('2023-09-10 20:52:00'),
 Timestamp('2023-09-13 20:52:00'),
 Timestamp('2023-09-14 20:52:00'),
 Timestamp('2023-09-14 20:52:00'),
 Timestamp('2023-09-15 20:52:00'),
 Timestamp('2023-09-16 20:52:00'),
 Timestamp('2023-09-17 20:52:00'),
 Timestamp('2023-09-19 20:52:00'),
 Timestamp('2023-09-21 20:52:00'),
 Timestamp('2023-09-22 20:52:00'),
 Timestamp('2023-09-23 20:52:00'),
 Timestamp('2023-09-27 20:52:00'),
 Timestamp('2023-09-28 20:52:00'),
 Timestamp('2023-09-29 20:52:00'),
 Timestamp('2023-09-30 20:52:00'),
 Timestamp('2023-10-02 20:52:00'),
 Timestamp('2023-10-04 20:52:00'),
 Timestamp('2023-10-06 20:52:00'),
 Timestamp('2023-10-07 20:52:00'),
 Timestamp('2023-10-09 20:52:00'),
 Timestamp('2023-10-10 20:52:00'),
 Timestamp('2023-10-11 20:52:00'),
 Timestamp('2023-10-12 20:52:00'),
 Timestamp('2023-10-15 20:52:00'),
 Timestamp('2023-10-18 20:52:00'),
 Timestamp('2023-10-18 20:52:00'),
 Timestamp('2023-10-19 20:52:00'),
 Timestamp('2023-10-20 20:52:00'),
 Timestamp('2023-10-20 20:52:00'),
 Timestamp('2023-10-21 20:52:00'),
 Timestamp('2023-10-23 20:52:00'),
 Timestamp('2023-10-26 20:52:00'),
 Timestamp('2023-10-27 20:52:00'),
 Timestamp('2023-10-27 20:52:00'),
 Timestamp('2023-10-29 20:52:00'),
 Timestamp('2023-10-31 20:52:00'),
 Timestamp('2023-11-03 20:52:00'),
 Timestamp('2023-11-03 20:52:00'),
 Timestamp('2023-11-10 20:52:00'),
 Timestamp('2023-11-10 20:52:00'),
 Timestamp('2023-11-10 20:52:00'),
 Timestamp('2023-11-12 20:52:00'),
 Timestamp('2023-11-12 20:52:00'),
 Timestamp('2023-11-13 20:52:00'),
 Timestamp('2023-11-13 20:52:00'),
 Timestamp('2023-11-14 20:52:00'),
 Timestamp('2023-11-15 20:52:00'),
 Timestamp('2023-11-17 20:52:00'),
 Timestamp('2023-11-17 20:52:00'),
 Timestamp('2023-11-19 20:52:00'),
 Timestamp('2023-11-22 20:52:00'),
 Timestamp('2023-11-23 20:52:00'),
 Timestamp('2023-11-23 20:52:00'),
 Timestamp('2023-11-24 20:52:00'),
 Timestamp('2023-11-25 20:52:00'),
 Timestamp('2023-11-25 20:52:00'),
 Timestamp('2023-11-25 20:52:00'),
 Timestamp('2023-11-26 20:52:00'),
 Timestamp('2023-11-26 20:52:00'),
 Timestamp('2023-11-28 20:52:00'),
 Timestamp('2023-11-30 20:52:00'),
 Timestamp('2023-12-07 20:52:00'),
 Timestamp('2023-12-07 20:52:00'),
 Timestamp('2023-12-07 20:52:00'),
 Timestamp('2023-12-08 20:52:00'),
 Timestamp('2023-12-08 20:52:00'),
 Timestamp('2023-12-09 20:52:00'),
 Timestamp('2023-12-09 20:52:00'),
 Timestamp('2023-12-11 20:52:00'),
 Timestamp('2023-12-11 20:52:00'),
 Timestamp('2023-12-12 20:52:00'),
 Timestamp('2023-12-16 20:52:00'),
 Timestamp('2023-12-16 20:52:00'),
 Timestamp('2023-12-17 20:52:00'),
 Timestamp('2023-12-19 20:52:00'),
 Timestamp('2023-12-19 20:52:00'),
 Timestamp('2023-12-20 20:52:00'),
 Timestamp('2023-12-21 20:52:00'),
 Timestamp('2023-12-21 20:52:00'),
 Timestamp('2023-12-22 20:52:00'),
 Timestamp('2023-12-22 20:52:00'),
 Timestamp('2023-12-23 20:52:00'),
 Timestamp('2023-12-23 20:52:00'),
 Timestamp('2023-12-24 20:52:00'),
 Timestamp('2023-12-24 20:52:00'),
 Timestamp('2023-12-24 20:52:00'),
 Timestamp('2023-12-26 20:52:00'),
 Timestamp('2023-12-29 20:52:00'),
 Timestamp('2023-12-29 20:52:00'),
 Timestamp('2024-01-01 20:52:00'),
 Timestamp('2024-01-02 20:52:00'),
 Timestamp('2024-01-04 20:52:00'),
 Timestamp('2024-01-05 20:52:00'),
 Timestamp('2024-01-07 20:52:00'),
 Timestamp('2024-01-09 20:52:00'),
 Timestamp('2024-01-11 20:52:00'),
 Timestamp('2024-01-11 20:52:00'),
 Timestamp('2024-01-15 20:52:00'),
 Timestamp('2024-01-15 20:52:00'),
 Timestamp('2024-01-17 20:52:00'),
 Timestamp('2024-01-17 20:52:00'),
 Timestamp('2024-01-18 20:52:00'),
 Timestamp('2024-01-18 20:52:00'),
 Timestamp('2024-01-18 20:52:00'),
 Timestamp('2024-01-21 20:52:00'),
 Timestamp('2024-01-22 20:52:00'),
 Timestamp('2024-01-22 20:52:00'),
 Timestamp('2024-01-23 20:52:00'),
 Timestamp('2024-01-23 20:52:00'),
 Timestamp('2024-01-24 20:52:00'),
 Timestamp('2024-01-25 20:52:00'),
 Timestamp('2024-01-27 20:52:00'),
 Timestamp('2024-01-27 20:52:00'),
 Timestamp('2024-01-27 20:52:00'),
 Timestamp('2024-01-27 20:52:00'),
 Timestamp('2024-01-28 20:52:00'),
 Timestamp('2024-01-28 20:52:00'),
 Timestamp('2024-01-28 20:52:00'),
 Timestamp('2024-01-29 20:52:00'),
 Timestamp('2024-02-05 20:52:00'),
 Timestamp('2024-02-05 20:52:00'),
 Timestamp('2024-02-06 20:52:00'),
 Timestamp('2024-02-07 20:52:00'),
 Timestamp('2024-02-07 20:52:00'),
 Timestamp('2024-02-08 20:52:00'),
 Timestamp('2024-02-08 20:52:00'),
 Timestamp('2024-02-09 20:52:00'),
 Timestamp('2024-02-09 20:52:00'),
 Timestamp('2024-02-11 20:52:00'),
 Timestamp('2024-02-11 20:52:00'),
 Timestamp('2024-02-12 20:52:00'),
 Timestamp('2024-02-12 20:52:00'),
 Timestamp('2024-02-17 20:52:00'),
 Timestamp('2024-02-18 20:52:00'),
 Timestamp('2024-02-20 20:52:00'),
 Timestamp('2024-02-21 20:52:00'),
 Timestamp('2024-02-22 20:52:00'),
 Timestamp('2024-02-22 20:52:00'),
 Timestamp('2024-02-23 20:52:00'),
 Timestamp('2024-02-25 20:52:00'),
 Timestamp('2024-02-25 20:52:00'),
 Timestamp('2024-02-26 20:52:00'),
 Timestamp('2024-02-26 20:52:00'),
 Timestamp('2024-02-27 20:52:00'),
 Timestamp('2024-02-28 20:52:00'),
 Timestamp('2024-02-28 20:52:00'),
 Timestamp('2024-02-29 20:52:00'),
 Timestamp('2024-03-01 20:52:00'),
 Timestamp('2024-03-02 20:52:00'),
 Timestamp('2024-03-02 20:52:00'),
 Timestamp('2024-03-03 20:52:00'),
 Timestamp('2024-03-05 20:52:00'),
 Timestamp('2024-03-07 20:52:00'),
 Timestamp('2024-03-09 20:52:00'),
 Timestamp('2024-03-10 20:52:00'),
 Timestamp('2024-03-10 20:52:00'),
 Timestamp('2024-03-11 20:52:00'),
 Timestamp('2024-03-11 20:52:00'),
 Timestamp('2024-03-12 20:52:00'),
 Timestamp('2024-03-13 20:52:00'),
 Timestamp('2024-03-14 20:52:00'),
 Timestamp('2024-03-15 20:52:00'),
 Timestamp('2024-03-16 20:52:00'),
 Timestamp('2024-03-16 20:52:00'),
 Timestamp('2024-03-17 20:52:00'),
 Timestamp('2024-03-18 20:52:00'),
 Timestamp('2024-03-21 20:52:00'),
 Timestamp('2024-03-21 20:52:00'),
 Timestamp('2024-03-21 20:52:00'),
 Timestamp('2024-03-22 20:52:00'),
 Timestamp('2024-03-23 20:52:00'),
 Timestamp('2024-03-23 20:52:00'),
 Timestamp('2024-03-25 20:52:00'),
 Timestamp('2024-03-25 20:52:00'),
 Timestamp('2024-03-26 20:52:00'),
 Timestamp('2024-03-30 20:52:00'),
 Timestamp('2024-03-30 20:52:00'),
 Timestamp('2024-04-02 20:52:00'),
 Timestamp('2024-04-02 20:52:00'),
 Timestamp('2024-04-07 20:52:00'),
 Timestamp('2024-04-07 20:52:00'),
 Timestamp('2024-04-08 20:52:00'),
 Timestamp('2024-04-08 20:52:00'),
 Timestamp('2024-04-09 20:52:00'),
 Timestamp('2024-04-09 20:52:00'),
 Timestamp('2024-04-09 20:52:00'),
 Timestamp('2024-04-09 20:52:00'),
 Timestamp('2024-04-10 20:52:00'),
 Timestamp('2024-04-14 20:52:00'),
 Timestamp('2024-04-14 20:52:00'),
 Timestamp('2024-04-15 20:52:00'),
 Timestamp('2024-04-15 20:52:00'),
 Timestamp('2024-04-15 20:52:00'),
 Timestamp('2024-04-16 20:52:00'),
 Timestamp('2024-04-16 20:52:00'),
 Timestamp('2024-04-17 20:52:00'),
 Timestamp('2024-04-17 20:52:00'),
 Timestamp('2024-04-19 20:52:00'),
 Timestamp('2024-04-20 20:52:00'),
 Timestamp('2024-04-20 20:52:00'),
 Timestamp('2024-04-21 20:52:00'),
 Timestamp('2024-04-22 20:52:00'),
 Timestamp('2024-04-22 20:52:00'),
 Timestamp('2024-04-22 20:52:00'),
 Timestamp('2024-04-24 20:52:00'),
 Timestamp('2024-04-25 20:52:00'),
 Timestamp('2024-04-26 20:52:00'),
 Timestamp('2024-04-28 20:52:00'),
 Timestamp('2024-04-28 20:52:00'),
 Timestamp('2024-04-29 20:52:00'),
 Timestamp('2024-04-29 20:52:00'),
 Timestamp('2024-04-30 20:52:00'),
 Timestamp('2024-04-30 20:52:00'),
 Timestamp('2024-05-02 20:52:00'),
 Timestamp('2024-05-03 20:52:00'),
 Timestamp('2024-05-04 20:52:00'),
 Timestamp('2024-05-04 20:52:00'),
 Timestamp('2024-05-05 20:52:00'),
 Timestamp('2024-05-06 20:52:00'),
 Timestamp('2024-05-07 20:52:00'),
 Timestamp('2024-05-10 20:52:00'),
 Timestamp('2024-05-10 20:52:00'),
 Timestamp('2024-05-11 20:52:00'),
 Timestamp('2024-05-13 20:52:00'),
 Timestamp('2024-05-14 20:52:00'),
 Timestamp('2024-05-14 20:52:00'),
 Timestamp('2024-05-15 20:52:00'),
 Timestamp('2024-05-16 20:52:00'),
 Timestamp('2024-05-17 20:52:00'),
 Timestamp('2024-05-18 20:52:00'),
 Timestamp('2024-05-18 20:52:00'),
 Timestamp('2024-05-20 20:52:00'),
 Timestamp('2024-05-20 20:52:00'),
 Timestamp('2024-05-21 20:52:00'),
 Timestamp('2024-05-21 20:52:00'),
 Timestamp('2024-05-21 20:52:00'),
 Timestamp('2024-05-21 20:52:00'),
 Timestamp('2024-05-25 20:52:00'),
 Timestamp('2024-05-25 20:52:00'),
 Timestamp('2024-05-28 20:52:00'),
 Timestamp('2024-05-28 20:52:00'),
 Timestamp('2024-05-29 20:52:00'),
 Timestamp('2024-05-30 20:52:00'),
 Timestamp('2024-05-30 20:52:00'),
 Timestamp('2024-05-31 20:52:00'),
 Timestamp('2024-06-01 20:52:00'),
 Timestamp('2024-06-01 20:52:00'),
 Timestamp('2024-06-01 20:52:00'),
 Timestamp('2024-06-01 20:52:00'),
 Timestamp('2024-06-03 20:52:00'),
 Timestamp('2024-06-03 20:52:00'),
 Timestamp('2024-06-05 20:52:00'),
 Timestamp('2024-06-08 20:52:00'),
 Timestamp('2024-06-09 20:52:00'),
 Timestamp('2024-06-09 20:52:00'),
 Timestamp('2024-06-09 20:52:00'),
 Timestamp('2024-06-10 20:52:00'),
 Timestamp('2024-06-10 20:52:00'),
 Timestamp('2024-06-11 20:52:00'),
 Timestamp('2024-06-11 20:52:00'),
 Timestamp('2024-06-14 20:52:00'),
 Timestamp('2024-06-16 20:52:00'),
 Timestamp('2024-06-16 20:52:00'),
 Timestamp('2024-06-17 20:52:00'),
 Timestamp('2024-06-17 20:52:00'),
 Timestamp('2024-06-17 20:52:00'),
 Timestamp('2024-06-18 20:52:00'),
 Timestamp('2024-06-18 20:52:00'),
 Timestamp('2024-06-20 20:52:00'),
 Timestamp('2024-06-22 20:52:00'),
 Timestamp('2024-06-22 20:52:00'),
 Timestamp('2024-06-23 20:52:00'),
 Timestamp('2024-06-23 20:52:00'),
 Timestamp('2024-06-25 20:52:00'),
 Timestamp('2024-06-28 20:52:00'),
 Timestamp('2024-06-29 20:52:00'),
 Timestamp('2024-06-30 20:52:00'),
 Timestamp('2024-06-30 20:52:00'),
 Timestamp('2024-07-01 20:52:00'),
 Timestamp('2024-07-02 20:52:00'),
 Timestamp('2024-07-04 20:52:00'),
 Timestamp('2024-07-04 20:52:00'),
 Timestamp('2024-07-05 20:52:00'),
 Timestamp('2024-07-05 20:52:00'),
 Timestamp('2024-07-07 20:52:00'),
 Timestamp('2024-07-08 20:52:00'),
 Timestamp('2024-07-08 20:52:00'),
 Timestamp('2024-07-09 20:52:00'),
 Timestamp('2024-07-10 20:52:00'),
 Timestamp('2024-07-11 20:52:00'),
 Timestamp('2024-07-11 20:52:00'),
 Timestamp('2024-07-12 20:52:00'),
 Timestamp('2024-07-12 20:52:00'),
 Timestamp('2024-07-13 20:52:00'),
 Timestamp('2024-07-14 20:52:00'),
 Timestamp('2024-07-16 20:52:00'),
 Timestamp('2024-07-17 20:52:00'),
 Timestamp('2024-07-19 20:52:00'),
 Timestamp('2024-07-20 20:52:00'),
 Timestamp('2024-07-20 20:52:00'),
 Timestamp('2024-07-20 20:52:00'),
 Timestamp('2024-07-20 20:52:00'),
 Timestamp('2024-07-20 20:52:00'),
 Timestamp('2024-07-21 20:52:00'),
 Timestamp('2024-07-22 20:52:00'),
 Timestamp('2024-07-22 20:52:00'),
 Timestamp('2024-07-23 20:52:00'),
 Timestamp('2024-07-26 20:52:00'),
 Timestamp('2024-07-26 20:52:00'),
 Timestamp('2024-07-27 20:52:00'),
 Timestamp('2024-07-29 20:52:00'),
 Timestamp('2024-07-29 20:52:00'),
 Timestamp('2024-07-29 20:52:00'),
 Timestamp('2024-07-30 20:52:00'),
 Timestamp('2024-08-01 20:52:00'),
 Timestamp('2024-08-01 20:52:00'),
 Timestamp('2024-08-02 20:52:00'),
 Timestamp('2024-08-02 20:52:00'),
 Timestamp('2024-08-03 20:52:00'),
 Timestamp('2024-08-03 20:52:00'),
 Timestamp('2024-08-03 20:52:00'),
 Timestamp('2024-08-05 20:52:00'),
 Timestamp('2024-08-05 20:52:00'),
 Timestamp('2024-08-08 20:52:00'),
 Timestamp('2024-08-12 20:52:00'),
 Timestamp('2024-08-12 20:52:00'),
 Timestamp('2024-08-13 20:52:00'),
 Timestamp('2024-08-13 20:52:00'),
 Timestamp('2024-08-14 20:52:00'),
 Timestamp('2024-08-15 20:52:00'),
 Timestamp('2024-08-18 20:52:00'),
 Timestamp('2024-08-18 20:52:00'),
 Timestamp('2024-08-19 20:52:00'),
 Timestamp('2024-08-19 20:52:00'),
 Timestamp('2024-08-21 20:52:00'),
 Timestamp('2024-08-21 20:52:00'),
 Timestamp('2024-08-22 20:52:00'),
 Timestamp('2024-08-22 20:52:00'),
 Timestamp('2024-08-23 20:52:00'),
 Timestamp('2024-08-23 20:52:00'),
 Timestamp('2024-08-26 20:52:00'),
 Timestamp('2024-08-26 20:52:00'),
 Timestamp('2024-08-26 20:52:00'),
 Timestamp('2024-08-27 20:52:00'),
 Timestamp('2024-08-27 20:52:00'),
 Timestamp('2024-08-28 20:52:00'),
 Timestamp('2024-08-28 20:52:00'),
 Timestamp('2024-08-28 20:52:00'),
 Timestamp('2024-08-29 20:52:00'),
 Timestamp('2024-08-31 20:52:00'),
 Timestamp('2024-09-01 20:52:00'),
 Timestamp('2024-09-01 20:52:00'),
 Timestamp('2024-09-02 20:52:00'),
 Timestamp('2024-09-02 20:52:00'),
 Timestamp('2024-09-02 20:52:00'),
 Timestamp('2024-09-04 20:52:00'),
 Timestamp('2024-09-07 20:52:00'),
 Timestamp('2024-09-07 20:52:00'),
 Timestamp('2024-09-07 20:52:00'),
 Timestamp('2024-09-07 20:52:00'),
 Timestamp('2024-09-09 20:52:00'),
 Timestamp('2024-09-10 20:52:00'),
 Timestamp('2024-09-11 20:52:00'),
 Timestamp('2024-09-12 20:52:00'),
 Timestamp('2024-09-13 20:52:00'),
 Timestamp('2024-09-18 20:52:00'),
 Timestamp('2024-09-18 20:52:00'),
 Timestamp('2024-09-18 20:52:00'),
 Timestamp('2024-09-19 20:52:00'),
 Timestamp('2024-09-19 20:52:00'),
 Timestamp('2024-09-19 20:52:00'),
 Timestamp('2024-09-20 20:52:00'),
 Timestamp('2024-09-21 20:52:00'),
 Timestamp('2024-09-22 20:52:00'),
 Timestamp('2024-09-23 20:52:00'),
 Timestamp('2024-09-25 20:52:00'),
 Timestamp('2024-09-26 20:52:00'),
 Timestamp('2024-09-28 20:52:00'),
 Timestamp('2024-09-28 20:52:00'),
 Timestamp('2024-09-28 20:52:00'),
 Timestamp('2024-09-28 20:52:00'),
 Timestamp('2024-09-29 20:52:00'),
 Timestamp('2024-09-30 20:52:00'),
 Timestamp('2024-09-30 20:52:00'),
 Timestamp('2024-10-01 20:52:00'),
 Timestamp('2024-10-01 20:52:00'),
 Timestamp('2024-10-03 20:52:00'),
 Timestamp('2024-10-03 20:52:00'),
 Timestamp('2024-10-04 20:52:00'),
 Timestamp('2024-10-08 20:52:00'),
 Timestamp('2024-10-09 20:52:00'),
 Timestamp('2024-10-11 20:52:00'),
 Timestamp('2024-10-13 20:52:00'),
 Timestamp('2024-10-14 20:52:00'),
 Timestamp('2024-10-14 20:52:00'),
 Timestamp('2024-10-17 20:52:00'),
 Timestamp('2024-10-19 20:52:00'),
 Timestamp('2024-10-19 20:52:00'),
 Timestamp('2024-10-20 20:52:00'),
 Timestamp('2024-10-20 20:52:00'),
 Timestamp('2024-10-21 20:52:00'),
 Timestamp('2024-10-25 20:52:00'),
 Timestamp('2024-10-25 20:52:00'),
 Timestamp('2024-10-25 20:52:00'),
 Timestamp('2024-10-25 20:52:00'),
 Timestamp('2024-10-27 20:52:00'),
 Timestamp('2024-10-29 20:52:00'),
 Timestamp('2024-10-29 20:52:00'),
 Timestamp('2024-10-29 20:52:00'),
 Timestamp('2024-10-30 20:52:00'),
 Timestamp('2024-10-30 20:52:00'),
 Timestamp('2024-10-30 20:52:00'),
 Timestamp('2024-10-30 20:52:00'),
 Timestamp('2024-11-03 20:52:00'),
 Timestamp('2024-11-04 20:52:00'),
 Timestamp('2024-11-04 20:52:00'),
 Timestamp('2024-11-06 20:52:00'),
 Timestamp('2024-11-07 20:52:00'),
 Timestamp('2024-11-07 20:52:00'),
 Timestamp('2024-11-08 20:52:00'),
 Timestamp('2024-11-09 20:52:00'),
 Timestamp('2024-11-13 20:52:00'),
 Timestamp('2024-11-13 20:52:00'),
 Timestamp('2024-11-14 20:52:00'),
 Timestamp('2024-11-16 20:52:00'),
 Timestamp('2024-11-16 20:52:00'),
 Timestamp('2024-11-16 20:52:00'),
 Timestamp('2024-11-16 20:52:00'),
 Timestamp('2024-11-17 20:52:00'),
 Timestamp('2024-11-18 20:52:00'),
 Timestamp('2024-11-18 20:52:00'),
 Timestamp('2024-11-19 20:52:00'),
 Timestamp('2024-11-20 20:52:00'),
 Timestamp('2024-11-21 20:52:00'),
 Timestamp('2024-11-23 20:52:00'),
 Timestamp('2024-11-23 20:52:00'),
 Timestamp('2024-11-24 20:52:00'),
 Timestamp('2024-11-26 20:52:00'),
 Timestamp('2024-11-28 20:52:00'),
 Timestamp('2024-11-29 20:52:00'),
 Timestamp('2024-11-29 20:52:00'),
 Timestamp('2024-11-29 20:52:00'),
 Timestamp('2024-12-01 20:52:00'),
 Timestamp('2024-12-02 20:52:00'),
 Timestamp('2024-12-02 20:52:00'),
 Timestamp('2024-12-04 20:52:00'),
 Timestamp('2024-12-04 20:52:00'),
 Timestamp('2024-12-05 20:52:00'),
 Timestamp('2024-12-07 20:52:00'),
 Timestamp('2024-12-08 20:52:00'),
 Timestamp('2024-12-09 20:52:00'),
 Timestamp('2024-12-09 20:52:00'),
 Timestamp('2024-12-09 20:52:00'),
 Timestamp('2024-12-10 20:52:00'),
 Timestamp('2024-12-10 20:52:00'),
 Timestamp('2024-12-11 20:52:00'),
 Timestamp('2024-12-12 20:52:00'),
 Timestamp('2024-12-14 20:52:00'),
 Timestamp('2024-12-15 20:52:00'),
 Timestamp('2024-12-16 20:52:00'),
 Timestamp('2024-12-17 20:52:00'),
 Timestamp('2024-12-18 20:52:00'),
 Timestamp('2024-12-18 20:52:00'),
 Timestamp('2024-12-19 20:52:00'),
 Timestamp('2024-12-19 20:52:00'),
 Timestamp('2024-12-22 20:52:00'),
 Timestamp('2024-12-22 20:52:00'),
 Timestamp('2024-12-25 20:52:00'),
 Timestamp('2024-12-25 20:52:00'),
 Timestamp('2024-12-27 20:52:00'),
 Timestamp('2024-12-27 20:52:00'),
 Timestamp('2024-12-28 20:52:00'),
 Timestamp('2024-12-29 20:52:00'),
 Timestamp('2024-12-31 20:52:00'),
 Timestamp('2025-01-01 20:52:00'),
 Timestamp('2025-01-01 20:52:00'),
 Timestamp('2025-01-01 20:52:00'),
 Timestamp('2025-01-02 20:52:00'),
 Timestamp('2025-01-02 20:52:00'),
 Timestamp('2025-01-02 20:52:00'),
 Timestamp('2025-01-03 20:52:00'),
 Timestamp('2025-01-04 20:52:00'),
 Timestamp('2025-01-04 20:52:00'),
 Timestamp('2025-01-04 20:52:00'),
 Timestamp('2025-01-05 20:52:00'),
 Timestamp('2025-01-06 20:52:00'),
 Timestamp('2025-01-07 20:52:00'),
 Timestamp('2025-01-07 20:52:00'),
 Timestamp('2025-01-09 20:52:00'),
 Timestamp('2025-01-10 20:52:00'),
 Timestamp('2025-01-10 20:52:00'),
 Timestamp('2025-01-10 20:52:00'),
 Timestamp('2025-01-11 20:52:00'),
 Timestamp('2025-01-14 20:52:00'),
 Timestamp('2025-01-15 20:52:00'),
 Timestamp('2025-01-17 20:52:00'),
 Timestamp('2025-01-17 20:52:00'),
 Timestamp('2025-01-18 20:52:00'),
 Timestamp('2025-01-19 20:52:00'),
 Timestamp('2025-01-19 20:52:00'),
 Timestamp('2025-01-20 20:52:00'),
 Timestamp('2025-01-20 20:52:00'),
 Timestamp('2025-01-22 20:52:00'),
 Timestamp('2025-01-27 20:52:00'),
 Timestamp('2025-01-28 20:52:00'),
 Timestamp('2025-01-28 20:52:00'),
 Timestamp('2025-01-28 20:52:00'),
 Timestamp('2025-01-29 20:52:00'),
 Timestamp('2025-01-31 20:52:00'),
 Timestamp('2025-01-31 20:52:00'),
 Timestamp('2025-01-31 20:52:00'),
 Timestamp('2025-02-01 20:52:00'),
 Timestamp('2025-02-02 20:52:00'),
 Timestamp('2025-02-03 20:52:00'),
 Timestamp('2025-02-04 20:52:00'),
 Timestamp('2025-02-04 20:52:00'),
 Timestamp('2025-02-04 20:52:00'),
 Timestamp('2025-02-05 20:52:00'),

In [553]:
bronze_menstrual_cycle_nextstartdate_df.head()

,User ID,Age,Stress Level,Exercise Frequency,Sleep Hours,Diet,Cycle Start Date,Cycle Length,Period Length,Next Cycle Start Date,Symptoms,BMI,_BronzeTimestamp
0,1.0,18.0,2.0,Moderate,54.0,Low Carb,2024-11-13 20:52:00,26,7.0,2024-12-09 20:52:00,Headache,29.28,2025-11-06 19:16:40.445350
1,1.0,18.0,2.0,Moderate,54.0,Low Carb,2024-12-09 20:52:00,32,5.0,2025-01-10 20:52:00,Fatigue,29.28,2025-11-06 19:16:40.445350
2,1.0,18.0,2.0,Moderate,54.0,Low Carb,2025-01-10 20:52:00,41,7.0,2025-02-20 20:52:00,Fatigue,29.28,2025-11-06 19:16:40.445350
3,1.0,18.0,2.0,Moderate,54.0,Low Carb,2025-02-20 20:52:00,27,3.0,2025-03-19 20:52:00,Fatigue,29.28,2025-11-06 19:16:40.445350
4,1.0,18.0,2.0,Moderate,54.0,Low Carb,2025-03-19 20:52:00,42,5.0,2025-04-30 20:52:00,Cramps,29.28,2025-11-06 19:16:40.445350

## Guardar

In [554]:
os.makedirs(silver_path, exist_ok=True)

In [563]:
bronze_menstrual_cycle_nextstartdate_df.to_parquet(silver_file_path)