# Load file to bronze

## Imports

In [7]:
import os
from datetime import datetime
import pandas as pd

## Parameters

In [8]:
source_file_path = os.path.join(os.curdir, "menstrual_cycle_editado.csv")

In [9]:
os.listdir()

['.git',
 'Data_Lake',
 'menstrual_cycle.csv',
 'menstrual_cycle_editado.csv',
 'NB_MC_BR_SL.ipynb',
 'NB_MC_FILE_BR.ipynb',
 'README.md']

In [10]:
bronze_file_name = "menstrual_cycle_bronze.parquet"
bronze_path = os.path.join(os.curdir, "Data_Lake","Bronze")
bronze_file_path = os.path.join(bronze_path, bronze_file_name)

In [11]:
os.makedirs(bronze_path, exist_ok = True)

## Main

### Cargar el csv a un DataFrame

In [17]:
menstrual_cycle_df = pd.read_csv(source_file_path,sep=";")

In [18]:
# Comprobamos si el fichero se ha cargado correctamente
menstrual_cycle_df.head()

,User ID,Age,Stress Level,Exercise Frequency,Sleep Hours,Diet,Cycle Start Date,Cycle Length,Period Length,Next Cycle Start Date,Symptoms,BMI
0,1.0,18.0,2.0,Moderate,54.0,Low Carb,13/11/2024 20:52,26,7.0,09/12/2024 20:52,Headache,29.28
1,1.0,18.0,2.0,Moderate,54.0,Low Carb,09/12/2024 20:52,32,5.0,10/01/2025 20:52,Fatigue,29.28
2,1.0,18.0,2.0,Moderate,54.0,Low Carb,10/01/2025 20:52,41,7.0,20/02/2025 20:52,Fatigue,29.28
3,1.0,18.0,2.0,Moderate,54.0,Low Carb,20/02/2025 20:52,27,3.0,19/03/2025 20:52,Fatigue,29.28
4,1.0,18.0,2.0,Moderate,54.0,Low Carb,19/03/2025 20:52,42,5.0,30/04/2025 20:52,Cramps,29.28

### Añadir el timestamp de carga

In [19]:
menstrual_cycle_df['_BronzeTimestamp'] = datetime.now()

In [20]:
menstrual_cycle_df.head()

,User ID,Age,Stress Level,Exercise Frequency,Sleep Hours,Diet,Cycle Start Date,Cycle Length,Period Length,Next Cycle Start Date,Symptoms,BMI,_BronzeTimestamp
0,1.0,18.0,2.0,Moderate,54.0,Low Carb,13/11/2024 20:52,26,7.0,09/12/2024 20:52,Headache,29.28,2025-11-06 19:16:40.445350
1,1.0,18.0,2.0,Moderate,54.0,Low Carb,09/12/2024 20:52,32,5.0,10/01/2025 20:52,Fatigue,29.28,2025-11-06 19:16:40.445350
2,1.0,18.0,2.0,Moderate,54.0,Low Carb,10/01/2025 20:52,41,7.0,20/02/2025 20:52,Fatigue,29.28,2025-11-06 19:16:40.445350
3,1.0,18.0,2.0,Moderate,54.0,Low Carb,20/02/2025 20:52,27,3.0,19/03/2025 20:52,Fatigue,29.28,2025-11-06 19:16:40.445350
4,1.0,18.0,2.0,Moderate,54.0,Low Carb,19/03/2025 20:52,42,5.0,30/04/2025 20:52,Cramps,29.28,2025-11-06 19:16:40.445350

### Guardar el DataFrame en parquet

In [21]:
menstrual_cycle_df.to_parquet(bronze_file_path, index=False)